### ISSUE TITLE
could not determine kind of name for C.GtkActionBar

### ISSUE THREAD

**Issue by Xymist** [gotk3/gotk3#108]
Full output below. I've upgraded GTK and GDK to their latest versions. Go get was performed today.

Is this a known problem?

--------------------

\#github.com/gotk3/gotk3/gtk
could not determine kind of name for C.GtkActionBar
could not determine kind of name for C.gtk_action_bar_get_center_widget
could not determine kind of name for C.gtk_action_bar_get_type
could not determine kind of name for C.gtk_action_bar_new
could not determine kind of name for C.gtk_action_bar_pack_end
could not determine kind of name for C.gtk_action_bar_pack_start
could not determine kind of name for C.gtk_action_bar_set_center_widget

gcc errors for preamble:
In file included from golang/src/github.com/gotk3/gotk3/gtk/actionbar_since_3_12.go:30:0:
actionbar_since_3_12.go.h:21:1: error: unknown type name 'GtkActionBar'
 static GtkActionBar *
 ^

**Comment by yamnikov-oleg** [comment]
What is your version of gtk? It must be greater than 3.12 to build the package with GtkActionBar support. 

If it's not - use this command to build the package:
(Replace `gtk_3_10` with an appropriate tag for your gtk version).

```
go install -tags gtk_3_10 github.com/gotk3/gotk3/gtk
```

**Comment by Xymist** [comment]
Thank you, that solved it; at least for the time being. Apparently 3.10.8 is considered 'latest' GTK for Mint 17.3!
