### ISSUE TITLE
Install errors using "go get..."

### ISSUE THREAD

**Issue by peteArnt** [gotk3/gotk3#110]
**From my 64-bit Linux Mint system, gcc version 4.8.4, go version 1.6**

 ~/mygo $ go get github.com/gotk3/gotk3/gtk
github.com/gotk3/gotk3/gtk
could not determine kind of name for C.GtkActionBar
could not determine kind of name for C.gtk_action_bar_get_center_widget
could not determine kind of name for C.gtk_action_bar_get_type
could not determine kind of name for C.gtk_action_bar_new
could not determine kind of name for C.gtk_action_bar_pack_end
could not determine kind of name for C.gtk_action_bar_pack_start
could not determine kind of name for C.gtk_action_bar_set_center_widget

gcc errors for preamble:
In file included from src/github.com/gotk3/gotk3/gtk/actionbar_since_3_12.go:30:0:
actionbar_since_3_12.go.h:21:1: error: unknown type name 'GtkActionBar'
 static GtkActionBar *
 ^

**Comment by petard** [comment]
I have same issue on Ubuntu 14.04

**Comment by yamnikov-oleg** [comment]
It appears that you're using gtk 3.10, though GtkActionBar is only available since 3.12. Please rebuild the package using the command:

```
go install -tags gtk_3_10 github.com/gotk3/gotk3/gtk
```

PS. I've added a note [at the wiki](https://github.com/gotk3/gotk3/wiki) describing installation process more closely.
