### ISSUE TITLE
GtkColorButton and other widgets missing from WrapMap

### ISSUE THREAD

**Issue by gbl08ma** [gotk3/gotk3#113]
After adding a ColorButton to my UI (I'm using GtkBuilder), to my surprise GetObject returned an error saying:

`unrecognized class name 'GtkColorButton'`

which I traced back to the lack of an entry for this widget in the WrapMap map in gtk.go. Adding its name and wrapping function to the map, I can now use this widget without problems.

Other widgets are missing, including (but possibly not limited to) all the GtkColor* ones.

**Comment by rafaelcn** [comment]
Could you do a fix and send a PR? I think they would love to accept help.

**Comment by gbl08ma** [comment]
This was fixed in #121
