### ISSUE TITLE
FileChooser dialog setting select multiple

### ISSUE THREAD

**Issue by r3s** [gotk3/gotk3#125]
Is there a way to allow selecting multiple files from the FileChooserDialog (New, NewWith1Button, NewWith2Buttons)?
If this feature is currently missing, it'd be great to have something like

`dialog.SetSelectMultiple(true)`

**Comment by sqp** [comment]
use the property?

https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#GtkFileChooser--select-multiple

filechooser.Set("select-multiple", true)

**Comment by r3s** [comment]
@sqp Setting the "select-multiple" property to true using Set didn't work. Still only able to select a single file

**Comment by andre-hub** [comment]
close after loog time
