### ISSUE TITLE
Installation on Windows error libintl.h not found

### ISSUE THREAD

**Issue by ganlub** [gotk3/gotk3#130]
I followed the wiki guide and I'm getting this error:
![gotk3-error](https://cloud.githubusercontent.com/assets/1272617/17619699/677961de-6087-11e6-82b5-174a534d9cd8.png)

I installed the exact same versions mentionend on the guide, the only difference was that `mingw-builds-install` was not working so I downloaded `x64-4.8.1-release-posix-seh-rev5.7z` and uncompressed it on C, also modified the enviroment PATHS accordingly.

Any ideas?
BTW, is it possible to cross compile it from linux?

**Comment by ganlub** [comment]
Anyone?

**Comment by juniorz** [comment]
This seems to be due a missing gettext installation.

**Comment by tommyshem** [comment]
If you type in the below command in the terminal and check the paths to see if the C header files needed to link the go files to the c library gtk3 are correct.

`pkg-config --cflags --libs gtk+-3.0`
the file Libintl.h is missing from the path from the screen shot above.

If you have the file in a different location you could copy it in to one of the paths it looks in.

You might not have all the installed packages needed for gtk3?

The paths could be pointing to the wrong locations if it is not setup correctly.

**Comment by zet4** [comment]
I am having same issue right now, I am certain I got all the dependencies listed on the install guide on the wiki (also a note the url for fedora 20 packages is out of date/404, I used https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/20/Everything/i386/os/Packages/m/ instead) and here are the outputs of my commands:
```
$  pkg-config --cflags --libs gtk+-3.0
-mms-bitfields -IC:/Fedora/include/gtk-3.0 -IC:/Fedora/include/atk-1.0 -IC:/Fedora/include/cairo -IC:/Fedora/include/gdk-pixbuf-2.0 -IC:/Fedora/include/glib-2.0 -IC:/Fedora/lib/glib-2.0/include -IC:/Fedora/include/pango-1.0 -IC:/Fedora/include/pixman-1 -IC:/Fedora/include -IC:/Fedora/include/freetype2 -I/usr/i686-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/i686-w64-mingw32/sys-root/mingw/include -IC:/Fedora/include/libpng16 -IC:/Fedora/include/harfbuzz  -Wl,-luuid -LC:/Fedora/lib -L/usr/i686-w64-mingw32/sys-root/mingw/lib -lgtk-3 -lgdk-3 -limm32 -lshell32 -lole32 -lwinmm -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpangoft2-1.0 -lpangowin32-1.0 -lgdi32 -lfontconfig -lfreetype -lpango-1.0 -lm -lcairo -lgobject-2.0 -lglib-2.0 -lintl
```

```
$ go get github.com/gotk3/gotk3/gtk
# github.com/gotk3/gotk3/glib
In file included from ./glib.go.h:31:0,
                 from H:\gopath\src\github.com\gotk3\gotk3\glib\application.go:7:
C:/Fedora/include/glib-2.0/glib/gi18n.h:25:21: fatal error: libintl.h: No such file or directory
compilation terminated.
```

**Comment by juniorz** [comment]
Glib uses gettext (https://developer.gnome.org/glib/stable/glib-I18N.html) for internationalization so you might need to install libintl for windows (http://gnuwin32.sourceforge.net/packages/libintl.htm).

**Comment by gandalfmagic** [comment]
Hi guys,
resolved for my build by changing **glib-2.0.pc**

Last line of the file, from:
`Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -mms-bitfields`

to:
`Cflags: -I${includedir} -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -mms-bitfields`

**Comment by arpitjindal97** [comment]
Doesn't work for me

**Comment by juniorz** [comment]
@arpitjindal97, you can try to double check if your system has the required dependencies as documented here: https://github.com/gotk3/gotk3/wiki#installation

You can also compare your installation with how we install it to run the automated tests on travis: https://github.com/gotk3/gotk3/blob/master/.travis.yml#L15

**Comment by juniorz** [comment]
Oh, I see. I have zero experience in cross-compiling golang for Windows using cgo.
