### ISSUE TITLE
Menubar/Menu questions

### ISSUE THREAD

**Issue by Woodhacker** [gotk3/gotk3#134]
To create the menus (File, edit, etc) for a menubar, you use MenuNew() for the menu, MenuItemNewWithLabel() for the text header (ie. File) and then add menu items to the menu.

However to attach the menu to the menubar, (in C) you use gtk_menu_shell_append, which is a method in MenuNew's parent (in go = func (v *MenuShell) Append(child IMenuItem)).  How do you get MenuShell from Menu?

**Comment by pekim** [comment]
https://developer.gnome.org/gtk3/stable/GtkMenuShell.html
> A GtkMenuShell is the abstract base class used to derive the GtkMenu and GtkMenuBar subclasses.

https://developer.gnome.org/gtk-tutorial/stable/x1577.html
```c
gtk_menu_shell_append (GTK_MENU_SHELL (menu), menu_items);
```

So I would have though it would be something like this.
```go
	menu, _ := gtk.MenuNew()
	menuShell := menu.(*gtk.MenuShell)
```
But that results in an invalid type assertion.

So I wonder if there's something wrong with gotk3's implementation of these types?

**Comment by andre-hub** [comment]
is this really a bug?

**Comment by pekim** [comment]
No, it is not a bug.

`gtk.Menu` embeds `gtk.MenuShell`.
https://github.com/gotk3/gotk3/blob/master/gtk/gtk.go#L5002
```go
// Menu is a representation of GTK's GtkMenu.
type Menu struct {
	MenuShell
}
```
And `gtk.MenuShell` is a `gtk.Container`.
``` go
// MenuShell is a representation of GTK's GtkMenuShell.
type MenuShell struct {
	Container
}
```

So something like this (ignoring error checking) will work.
```go
menu, _ := gtk.MenuNew()
menuItem, _ := gtk.MenuItemNewWithLabel("...")

menu.Append(menuItem)
```
