### ISSUE TITLE
Build failed: unrecognized relocation (0x2a) in section `.text'

### ISSUE THREAD

**Issue by ilius** [gotk3/gotk3#147]
Tried to build [simple.go](https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/simple/simple.go)

    $ go build -tags gtk_3_14 simple.go

    # command-line-arguments
    /usr/lib/go-1.7/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
    /usr/bin/ld: /tmp/go-link-073651445/000001.o: unrecognized relocation (0x2a) in section `.text'
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status

_______________________________

OS: Debian GNU/Linux 8

Package: libgtk-3-0
Version: 3.14.5-1+deb8u1

Package: libgtk-3-dev
Version: 3.14.5-1+deb8u1

$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2

(Also tried with gcc 4.8.4 as default version)

**Comment by ilius** [comment]
Problem solved by renaming `/usr/lib/go-1.7/pkg/linux_amd64`

**Comment by bothra90** [comment]
@ilius What did you rename it to?

**Comment by ilius** [comment]
I don't remember, but I think it didn't matter. The same as removing it.

**Comment by crashtua** [comment]
@ilius thanks a lot. Your suggestion to remove this folder helped me too.

**Comment by junmei** [comment]
For me the above does not work. But remove files in the GOCACHE worked.

$go env
GOCACHE="~/.cache/go-build"

$ rm -rf ~/.cache/go-build/*

**Comment by howson** [comment]
@junmei Thanks!!!! That worked for me

**Comment by xionghengheng** [comment]
https://zhuanlan.zhihu.com/p/405683882
