### ISSUE TITLE
Are the handlers?

### ISSUE THREAD

**Issue by nexcode** [gotk3/gotk3#148]
Hi. Thanks for this project!

I use glade for design ui. I add handler on button (myhandler on clicked signal), but it does not call the handler from code. How do I properly declare it in the code?

P.S. Сonnect to the signals works (I caught the "clicked" signal)

![2016-11-23 01-22-15](https://cloud.githubusercontent.com/assets/10132325/20544467/5217033e-b11b-11e6-8bda-ea886f3263bf.png)

**Comment by undreren** [comment]
Well, you have to connect the handlers.

	package main

	import "github.com/gotk3/gotk3/gtk"

	func main() {
		gtk.Init(nil)

		builder, _ := gtk.BuilderNew()
		_ := builder.AddFromFile("./gui.glade")

		// do setup of application window and stuff
		// ...

		signals := make(map[string]interface{})
		signals["myhandler"] = MyHandlerFunc

		builder.ConnectSignals(signals)

		gtk.Main()
	}

Have you tried this?

**Comment by nexcode** [comment]
It works. Thanks.
