### ISSUE TITLE
How to pass data to the handler?

### ISSUE THREAD

**Issue by nexcode** [gotk3/gotk3#149]
Glade: https://yadi.sk/i/TnaMLyrw32P86v

Code:
> signals := map[string]interface{}{
		"myhandler": func(e *gtk.Button) {
			fmt.Println(e.GetLabel())
		},
	}

If I add another variable to the function, it will error:
> "myhandler": func(e *gtk.Button, obj interface{}) {

How to get "txt" object in handler?

**Comment by ERnsTL** [comment]
1. Using the ```userdata``` parameter like so: 
  ```
  button.Connect("clicked", func (btn *gtk.Button, mydata string) {
    //....
  }, userdatatobepassed_upon_call)
  ```
2. Using the way Go closures work, which is that they inherit the variable context of the calling function:
  ```
  for i := 0; i < 10; i++ {
    myvar := i  // make copy of value, otherwise all button clicks will be passed the same value
    button.Connect("clicked", func (btn *gtk.Button) {
      fmt.Println("Button number", myvar, "was clicked")
    })
  }
  ```
