### ISSUE TITLE
Split the gtk.go file topic-based smaller files

### ISSUE THREAD

**Issue by andre-hub** [gotk3/gotk3#15]
The gtk.go file is very big and we need a better way more tests and overview the sourcecode.

**Comment by andre-hub** [comment]
work on progress issue
current gtk.go lines: _9169_

**Comment by andre-hub** [comment]
current gtk.go lines: 8790

**Comment by rafaelcn** [comment]
I'm wiilling to contribute to this project, and it would be awesome if we have some orientation (read list) in how to split the `gtk.go` file in smaller files, and maybe target it to a milestone as well. 😄

**Comment by andre-hub** [comment]
welcome @rafaelcn 
you need a milestone :-)

the target to the end of year 2016 3000 lines for gtk.go

or you mean otherwise?

**Comment by rafaelcn** [comment]
Yes indeed, a milestone containing what we should and are doing would be clarifying to new developers. When I get my hands on my Linux machine I will try to set up everything and then begin to code.
