### ISSUE TITLE
MaxWidthChars for Entry control (incl. patch)

### ISSUE THREAD

**Issue by ERnsTL** [gotk3/gotk3#153]
I wanted to set the maximum visible width of an ```Entry``` control today for an entry form. For example, only 10 characters should be visible = control width. I noticed that

* ```Entry.SetMaxLength``` sets the maximum characters the user can enter (useful),
* ```Entry.SetWidth(charcount)``` sends a resize request, but when an ```Entry``` is inside a container (```Grid``` in my case), then this is not enough. Therefore, the ...
* ```Entry.SetMaxWidthChars(charcount)``` function is needed.

Unfortunately, this function is not wrapped in gotk3.

See the gtk3 documentation about the functions here:

* [gtk_entry_get_max_width_chars](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-get-max-width-chars)
* [gtk_entry_set_max_width_chars](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-max-width-chars)

**Patch for gotk3:** Paste the following into ```gtk/gtk.go``` file:

```
// SetMaxWidthChars() is a wrapper around gtk_entry_set_max_width_chars().
func (v *Entry) SetMaxWidthChars(nChars int) {
	C.gtk_entry_set_max_width_chars(v.native(), C.gint(nChars))
}

// GetMaxWidthChars() is a wrapper around gtk_entry_get_max_width_chars().
func (v *Entry) GetMaxWidthChars() int {
	c := C.gtk_entry_get_max_width_chars(v.native())
	return int(c)
}
```

Already tested this today. I am using libgtk-3.0 version 3.18.9 for reference.

I could file a PR, but it's really just a matter of copy & paste into any place in ```gtk/gtk.go```.

Please include this change into gotk3.

**Comment by juniorz** [comment]
Please send a pull request, even for small changes. It will trigger the automated test suite and help us to make sure everything is fine.

Thank you.
