### ISSUE TITLE
Win8.1x64: libintl.h: No such file or directory

### ISSUE THREAD

**Issue by Visteras** [gotk3/gotk3#156]
Sorry for my bad english...
I used https://github.com/gotk3/gotk3/wiki/Installing-on-Windows
`pkg-config --cflags --libs gtk+-3.0` - no error
`go get github.com/gotk3/gotk3/gtk` return:

    # github.com/gotk3/gotk3/glib
    In file included from ./glib.go.h:31:0,
                     from D:\GOPATH\src\github.com\gotk3\gotk3\glib\application.go:7:
    C:/Fedora/include/glib-2.0/glib/gi18n.h:25:21: fatal error: libintl.h: No such file or directory
     #include <libintl.h>
                         ^
    compilation terminated.

GOPATH: `D:\GOPATH`
GOROOT: `C:\Go\`
Path: `;C:\Fedora\include;C:\Fedora\bin;C:\Program Files\mingw-builds\x64-4.8.1-posix-seh-rev5\mingw64\bin;C:\mingw64\bin;C:\mingw\bin`

File `libintl.h` exist in `C:\Fedora\include`
I really do not know how to solve this problem...

**Comment by Visteras** [comment]
P.S. In https://github.com/gotk3/gotk3/issues/130 solution not found...
Pls help me. What am I doing wrong?

**Comment by andre-hub** [comment]
too long open - without answer, sorry.
