### ISSUE TITLE
Activity pulsing for ProgressBar (incl. patch)

### ISSUE THREAD

**Issue by ERnsTL** [gotk3/gotk3#160]
GTK3 ```ProgressBar``` supports showing activity on the progress bar, without knowing how far the progress went / what its impact on progress was. This is shown by a bar moving back and forth inside the ```ProgressBar```.

To go into this "activity" mode, call ```Pulse()``` - depending on how often you call it in your work loop, you can adjust the moving speed using ```pb.SetPulseStep()```. Switching into fraction-mode is done using just setting regular ```pb.SetFraction()``` function.

Unfortunately, this is not currently wrapped by gotk3.

**Patch follows:**

1. Open ```gotk3/gtk/gtk.go```.
2. Somewhere around ```func (v *ProgressBar) SetFraction(```, insert:

```
// SetPulseStep is a wrapper around gtk_progress_bar_set_pulse_step().
func (v *ProgressBar) SetPulseStep(fraction float64) {
	C.gtk_progress_bar_set_pulse_step(v.native(), C.gdouble(fraction))
}

// GetPulseStep is a wrapper around gtk_progress_bar_get_pulse_step().
func (v *ProgressBar) GetPulseStep() float64 {
	c := C.gtk_progress_bar_get_pulse_step(v.native())
	return float64(c)
}

// Pulse is a wrapper arountd gtk_progress_bar_pulse().
func (v *ProgressBar) Pulse() {
	C.gtk_progress_bar_pulse(v.native())
}
```
3. Recompile your gotk3-based application, which will also re-compile gotk3/gtk.

**Comment by andre-hub** [comment]
added in https://github.com/gotk3/gotk3/commit/bf58a1263d47a75ed76dbb17b1d1bfbc32ee800b
