### ISSUE TITLE
Vertical orientation for ProgressBar (incl. patch)

### ISSUE THREAD

**Issue by ERnsTL** [gotk3/gotk3#161]
GTK3 ```ProgressBar```s support ```GtkOrientable``` in order to produce vertical progress bars or "fillbars" to show some fill level, buffer fill level, memory fill level or similar.

Unfortunately, this is not wrapped in gotk3.

**Patch follows:**

1. Open ```gotk3/gtk/gtk.go```.
2. Add ```Orientable``` interface to ```ProgressBar```. Change:

	```
	// ProgressBar is a representation of GTK's GtkProgressBar.
	type ProgressBar struct {
		Widget
	}
	```

to

	```
	// ProgressBar is a representation of GTK's GtkProgressBar.
	type ProgressBar struct {
		Widget

		// Interfaces
		Orientable
	}
	```

in a fashion similar to (what I used as template)

	```
	type Grid struct {
		Container

		// Interfaces
		Orientable
	}
	```

3. Change:

	```
	func wrapProgressBar(obj *glib.Object) *ProgressBar {
		return &ProgressBar{Widget{glib.InitiallyUnowned{obj}}}
	}
	```

to

	```
	func wrapProgressBar(obj *glib.Object) *ProgressBar {
		o := wrapOrientable(obj)
		return &ProgressBar{Widget{glib.InitiallyUnowned{obj}}, *o}
	}
	```

in a fashion similar to

	```
	func wrapGrid(obj *glib.Object) *Grid {
		o := wrapOrientable(obj)
		return &Grid{Container{Widget{glib.InitiallyUnowned{obj}}}, *o}
	}
	```
	
  just without the Container{}, because ProgressBar is not a container.

4. Recompile your gotk3-based application, which will also re-compile gotk3/gtk.

**Comment by andre-hub** [comment]
added in eb834a999198fd87e43c9c979a6dfadea40f063f
