### ISSUE TITLE
Inverted fill direction eg. bottom-up for ProgressBar (incl. patch)

### ISSUE THREAD

**Issue by ERnsTL** [gotk3/gotk3#162]
GTK3 ```ProgressBar``` supports the ability to invert the fill direction. This is useful in conjunction with vertical progress bars. By default these fill up top to bottom, but if a "fill level"-like display is desired, then the inversion function is needed. Is allows to realize fill-level like progress (consuming a buffer, filling up a buffer).

This is related to issue #161.

**Patch follows:**

1. Open ```gotk3/gtk/gtk.go```.
2. After ```func (v *ProgressBar) GetShowText```, insert:
```
// SetInverted is a wrapper around gtk_progress_bar_set_inverted().
func (v *ProgressBar) SetInverted(inverted bool) {
	C.gtk_progress_bar_set_inverted(v.native(), gbool(inverted))
}

// GetInverted is a wrapper around gtk_progress_bar_get_inverted().
func (v *ProgressBar) GetInverted() bool {
	c := C.gtk_progress_bar_get_inverted(v.native())
	return gobool(c)
}
```
3. Recompile your gotk3-based application, which will also re-compile gotk3/gtk.

**Comment by andre-hub** [comment]
added in eb834a999198fd87e43c9c979a6dfadea40f063f
