### ISSUE TITLE
HeaderBar

### ISSUE THREAD

**Issue by SuburbanFilth** [gotk3/gotk3#174]
Hey guys, 

thank you for the awesome work you are doing and please do not read this as a complaint, but more like a lack of understanding question.

I am learning GO and wanted to build a simple Note gui. I was looking at the Header struct and i wanted to add some buttons on it. The thing is that it does not render as a HeaderBar, but as normal grid box inside the app. What I mean is below :

What it should be : 

![screenshot from 2017-07-05 13 57 43](https://user-images.githubusercontent.com/7538637/27861545-f6e4d660-6189-11e7-9581-73c8868ef974.png)

What Im getting : 

![screenshot from 2017-07-05 13 58 38](https://user-images.githubusercontent.com/7538637/27861579-13dd9d92-618a-11e7-9438-5aaa365f4c6d.png)

The "ds" button and the label should be in the header as in the first screenshot. 

Here is my code :

![screenshot from 2017-07-05 14 00 57](https://user-images.githubusercontent.com/7538637/27861666-68e0c864-618a-11e7-886a-0a4da012a485.png)

Is this the intention ? Am I missing something ?

**Comment by errz99** [comment]
You must not add the header directly to the window. Windows can have only one widget inside. You must first add a container (probably a vertical box) to the window and then add the header (probably inside another horizontal box with the button) to that vertical box.

**Comment by SuburbanFilth** [comment]
It does not work. I add a vertical box inside the window and then a horizontal one inside of it. When I add the header and the button I get the following :

![screenshot from 2017-07-05 14 52 09](https://user-images.githubusercontent.com/7538637/27863194-a6a0d0de-6191-11e7-9ad1-e403dca37a11.png)

![dsadsadsa](https://user-images.githubusercontent.com/7538637/27863196-aa71059e-6191-11e7-9627-d87665bebba0.png)

**Comment by errz99** [comment]
Well, those steps where necessary but not the only ones. Try to set homogeneous to false in the MainBox. I don't know exactly now. Maybe in half an hour can try to write it myself.

**Comment by SuburbanFilth** [comment]
alright, thank you for the help!

**Comment by errz99** [comment]
You're welcome.
This seems to work for me:

```
func main() {	
	gtk.Init(nil)
	
	window, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	window.SetDefaultSize(1000, 800)
	window.Connect("destroy", gtk.MainQuit)
	
	mainBox, _ := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	header, _  := gtk.HeaderBarNew()
	button, _  := gtk.ButtonNewWithLabel("Dsa")
	
	header.PackEnd(button)
	
	mainBox.Add(header)
	window.Add(mainBox)
	window.ShowAll()
	
	gtk.Main()
	
}

```

**Comment by SuburbanFilth** [comment]
I got the same result as before with just the button on the right instead of left. Can you send me a screenshot of what you got exactly ?

**Comment by errz99** [comment]
With PackStart you add at the beginning and with PackEnd at the end of the container. Or use simply Add. I tried to solve your first problem of not getting the header box at the top of the window. This is how it looks like (now with PackStart):

![headerbar](https://user-images.githubusercontent.com/6728014/27865608-8a02b238-6193-11e7-9eae-1c194ce5ed5a.png)

**Comment by SuburbanFilth** [comment]
alright, I guess I did not explain the problem well enough. The issue is to get the buttons in the place where it says ''headerbox'' in you screenshot, not below them in a different container. Like shown here : 

http://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html#headerbar

**Comment by errz99** [comment]
Well, maybe this gets closer: undecorate the main window and translate some lines from the python code.

```
func main() {
	gtk.Init(nil)
	
	window, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	window.SetDefaultSize(600, 400)
	window.SetDecorated(false)
	window.Connect("destroy", gtk.MainQuit)
	
	mainBox, _ := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	header, _  := gtk.HeaderBarNew()
	
	header.SetShowCloseButton(true)
	header.SetTitle("HeaderBar example")
	
	button, _  := gtk.ButtonNewWithLabel("Dsa")
	header.PackStart(button)
	
	mainBox.Add(header)
	window.Add(mainBox)
	window.ShowAll()
	
	gtk.Main()
}

```

![headerbar2](https://user-images.githubusercontent.com/6728014/27867473-0518e7de-619a-11e7-8ad0-42638f0293b8.png)

**Comment by SuburbanFilth** [comment]
Its perfect, thank you very much for the effort :)

**Comment by errz99** [comment]
De nada ... and good luck with the rest of your code :-)
