### ISSUE TITLE
callback in glib.TimeoutAdd only executed once

### ISSUE THREAD

**Issue by errz99** [gotk3/gotk3#179]
Hi
Using glib.TimeoutAdd, my function passed is called only once, even after returning true.
It's something similar to this:

`glib.TimeoutAdd(wait_time, my_function, my_data)
`

Tried the same in C and worked fine.
It seems an old issue as I found here:

https://github.com/conformal/gotk3/pull/91

but maybe I'm missing something...
any idea?
Thanks

**Comment by vit1251** [comment]
I have similar problem. Now I resolve by adding new timeout call but I feel that it may cause a internal resource leak.

**Comment by grandchild** [comment]
Here is a minimal (non-)working example showing the bug.
https://gist.github.com/grandchild/690b42ae4c0673954001f8c96ec53d09
