### ISSUE TITLE
Compile error on ARM

### ISSUE THREAD

**Issue by ghjp** [gotk3/gotk3#180]
When I compile my application on an ARM platform with the 1.8.3 go compiler with the actual version of gotk3 I get the following error:

../../github.com/gotk3/gotk3/gtk/print.go:1502: type [1073741824]C.struct__GtkPageRange larger than address space
../../github.com/gotk3/gotk3/gtk/print.go:1502: type [1073741824]C.struct__GtkPageRange too large

It seems that the array size of "1 << 30" is too big on arm platforms. The question here is nonetheless
why such a big value is used here.

On amd64 platform everything is ok.

**Comment by mklimuk** [comment]
Same here. This is kind of weird as maximum slice size on arm should be max(int) and though 0x7FFFFFFF (as int is 32-bit signed number).  1 << 30 is 0x40000000 which is less. Or am I missing something?

**Comment by juniorz** [comment]
This seems to be a lame implementation: the return type `PageRanges` wraps an array of `*C.GtkPageRange` as a slice containing the same pointers, but gives no way to access the individual `*C.GtkPageRange` (since the type does not export any of its fields, or have any method).

**Comment by juniorz** [comment]
Closed by 58b15d7
