### ISSUE TITLE
Build bindings to gtk with c-for-go

### ISSUE THREAD

**Issue by harisvsulaiman** [gotk3/gotk3#189]
Building binding for gtk by hand will be tedious, I think we should move on to autogenerated bindings.
My first guess was using GObject introspection metadata but this project https://github.com/xlab/c-for-go has somewhat proven itself to be capable of generating bindings.

I would like to hear your thoughts on this.

**Comment by harisvsulaiman** [comment]
@r03 Yes but we will get feature parity with the whole of glib and gtk. A high-level wrapper will be needed but to quote the repo readme
> The resulting bindings are as low-level as C code, i.e. it would require knowledge of memory management to carefully use the resulting code, however no more C code is needed to make things done. Eventually some functions can be replaced manually with pure-Go analogs. Also usually a high-level wrapper is created by hand, to introduce Object Oriented Design into API, manage inner state and memory, thus making things safe and lifting the mental overhead.

**Comment by andre-hub** [comment]
I think the c-for-go project is a good way for fast creating a c wrapper.
But this gtk wrapper has now to many memory leaks and we have more control with manual writing code.

You can even try to check whether the generator creates human-readable and changeable source code. It would be useful for the pull request to without the generator or other dependencies in this project. Perhaps you can make sure that the source code does not differ from the previous project style.
