### ISSUE TITLE
Finalizers can be called prematurely

### ISSUE THREAD

**Issue by hitchfred** [gotk3/gotk3#192]
Sometimes Go will notice that a gotk3 wrapper object is unreachable and run the finalizer, unrefing the underlying object,  while a call into C is made. I made a demo that can stress this here: https://github.com/hitchfred/gotk3-pixbufloader 

I think the answer is to add calls to runtime.KeepAlive() in key spots in gotk3 to make sure that objects aren't unrefed while C functions are called. Uncommenting the runtime.KeepAlive() call in the demo fixes the issue: https://github.com/hitchfred/gotk3-pixbufloader/blob/master/main.go#L45

I've run into this issue on go1.8.3 windows/amd64 and go1.9 linux/amd64 

See also: https://golang.org/pkg/runtime/#KeepAlive

**Comment by juniorz** [comment]
I'm investigating this.

**Comment by juniorz** [comment]
@hitchfred, can you explain how to reproduce this?

I'm running you example with 1, 10, 100, 1000, 10000 iterations on a single image and I get no 0 failures.

**Comment by hitchfred** [comment]
I'm still getting Gtk assertion errors and occasional nil pixbufs on Windows and FreeBSD with Go 1.8 and 1.9, respectfully:

`$ gotk3-pixbufloader.exe -iterations 3000 pix/*`

What version of Go are you using? runtime.KeepAlive was added in Go 1.7 I think. The way Go does garbage collection might've changed in newer versions. 

This thread might be of interest:
https://groups.google.com/forum/#!topic/golang-nuts/LIWj6Gl--es

> It used to be.  Before Go 1.7, we used to keep all arguments alive throughout the function.  It was kind of a hack, mostly to work around the lack of something like runtime.KeepAlive.  Keeping arguments live throughout the function often lead to objects being retained longer than necessary (the opposite problem from what you are observing).
We didn't see a way to solve this problem automatically.  We decided to use the minimal live ranges and provide runtime.KeepAlive so you can extend the live range.  I think the other direction (keeping the longer live ranges and providing a runtime.AssertThisIsDead) wouldn't work.

**Comment by juniorz** [comment]
Thanks. I have been testing on Linux, golang 1.9.1. Also I have been testing loading a single image.
I am testing with the code with `runtime.KeepAlive()` commented out. 

I noticed you are testing with more than one image. Does it change your result (with the KeepAlive commented out)?

**Comment by juniorz** [comment]
I'm curious not only about the number of images but also their size.

**Comment by juniorz** [comment]
I think I understand what happens: `loadPixbuf` is called on a goroutine which may block during the invocation of `loader.GetPixbuf`. As 'loader' in unreachable its finalizer is invoked if this makes the GC to run.

**Comment by hitchfred** [comment]
I originally bumped into this issue downloading groups of thumbnails. the images aren't that large at all, a few kbytes each at most. But I was loading them in batches of 20-50 at a time in goroutines. I do think loading in batches like that stresses things a bit.  I dont trigger the failure either when I supply just one image to the test program.

the test images:
https://github.com/hitchfred/gotk3-pixbufloader/tree/master/pix

**Comment by juniorz** [comment]
I noticed the `gdk` package was missing automatic memory management. Could you try to reproduce the issue against 8137f9007e8c1164020fefc272287994b62e86c2?

**Comment by hitchfred** [comment]
Ran the test again with your patch and there are no more pixbufloader failures! But I do get high memory usage (6 gigs resident) after some iterations, and it starts to swap.. It didn't climb as high before.

**Comment by juniorz** [comment]
Yes, this is expected. You must release objects by calling 'Unref()' when you don't need them anymore, as you would do when using pure gtk+ APIS. This cant be done automatically because golang does not have a feature like destructors.

**Comment by hitchfred** [comment]
Thanks. With the Unref() it's working fine.

**Comment by hitchfred** [comment]
Will close since it seems to be fixed
