### ISSUE TITLE
Suggestion for a complete example

### ISSUE THREAD

**Issue by BharatKalluri** [gotk3/gotk3#199]
A complete example using all the different types of the widgets that are supported by gotk3 in a single program would serve as a great reference. 

For example, ```gtk3-widget-factory``` runs a program which shows all the widgets which can be implemented using gtk3. And ```gtk3-demo``` runs a program which shows a reference to all the types of gtk widgets with the code used to create them in C++. Implementing any one of those with the source code on GitHub would prove to be really useful.

If there was something like that for gotk3 it would be fantastic. If there is anything I can do please let me know!

**Comment by vit1251** [comment]
I also searched and found https://github.com/gotk3/gotk3-examples
