### ISSUE TITLE
Add bindings for GtkFileChooser gtk_file_chooser_get_filenames, gtk_file_chooser_get_uris functions

### ISSUE THREAD

**Issue by heisantosh** [gotk3/gotk3#214]
Currently, I see only the bindings for gtk_file_chooser_get_filename(), gtk_file_chooser_get_uri(). The bindings for gtk_file_chooser_get_filenames(), gtk_file_chooser_get_uris() are missing.

**Comment by Bios-Marcel** [comment]
For the record, `gtk_file_chooser_get_filenames()` was added with 812534837ca8bb8796183762a69435dc7eb50aac, but `gtk_file_chooser_get_uris()` is still missing.
