### ISSUE TITLE
Add support for gtk_toggle_button_set_mode

### ISSUE THREAD

**Issue by JamesDunne** [gotk3/gotk3#228]
See https://developer.gnome.org/gtk3/stable/GtkToggleButton.html#gtk-toggle-button-set-mode

This property allows a RadioButton to be displayed like a normal button, i.e. allowing a group of buttons to act like a StackSwitcher to be mutually exclusive but without showing the radio indicator.

**Comment by founderio** [comment]
Is this fixed with your PR or is something still missing?

**Comment by JamesDunne** [comment]
Yes this is fixed with the PR.
