### ISSUE TITLE
Implement Label.SetAttributes()

### ISSUE THREAD

**Issue by ns-cweber** [gotk3/gotk3#243]
Label.SetAttributes() is missing. This can probably be worked around by Label.SetMarkup().

**Comment by ns-cweber** [comment]
Implementing this seems straightforward, but testing it seems less so. In particular, the test case should probably be "put some attrs into SetAttributes() and make sure the same are returned by GetAttributes()"; however, reading the `*pango.AttrList` returned by `GetAttributes()` seems to require `pango_attr_list_get_iterator()` which requires that the `AttrList` is not modified until the iterator is freed.

This pretty much precludes `runtime.SetFinalizer()` for freeing the iterator; we would probably need to give the iterator a `Close()` method or some such, but we would still probably want to panic explicitly if the user modifies the `AttrList` before `Close()` is called (as opposed to whatever unspecified behavior results from modifying the list before freeing the iterator). At least this approach seems more Go-idiomatic.

Anyway, I wanted feedback about this approach before I went about implementing any particular thing. Specifically, is there already a pattern for this sort of scenario?

**Comment by sameraga** [comment]
what about this function func (v *Label) SetFont(font string)
I don`t found it
I have this error
label1.SetFont undefined (type *gtk.Label has no field or method SetFont)

**Comment by hfmrow** [comment]
I think i'm not wrong saying:
This function does not exist ... [GtkLabel](https://developer.gnome.org/gtk3/stable/GtkLabel.html)
You can workaround using [Pango](https://developer.gnome.org/pango/1.44/) markup style.
ie:
`<span font_size="font-description">TEXT TO DISPLAY</span>`

using: [gtk.Label.SetMarkup](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-markup)

**"font-description"**: A font description string, such as "Sans Italic 12". See pango_font_description_from_string() for a description of the format of the
		string representation.
