### ISSUE TITLE
undefined symbol: gtk_stack_sidebar_get_type

### ISSUE THREAD

**Issue by jeancarlos1111** [gotk3/gotk3#247]
./main: symbol lookup error: ./main: undefined symbol: gtk_stack_sidebar_get_type 
After build with the command go build main.go and create the executable, I transfer it to another computer and throw that error at me.
![captura de pantalla de 2018-02-28 11-58-19](https://user-images.githubusercontent.com/10359567/36797298-f85e4896-1c7d-11e8-8753-1686dc788a65.png)

**Comment by founderio** [comment]
Did you check the gtk version on that computer?
gtk_stack_sidebar_get_type seems to have been added with gtk 3.16, maybe you have an earlier version?

**Comment by jeancarlos1111** [comment]
Versión 3.22.25-0ubuntu0.1

**Comment by andre-hub** [comment]
@jeancarlos1111  have you now this bug with you actual software versions?

**Comment by andre-hub** [comment]
There was no reaction now. However, the error message appears to be that the target computer does not have the same GTK version installed. The execution file is built against certain versions of the libs, and it will run with those.
