### ISSUE TITLE
crash at gtk.Main

### ISSUE THREAD

**Issue by hopkings2008** [gotk3/gotk3#251]
@sqs I use the gotk3 for webloop and it always crashed at the gtk.Main func. below is the stack trace:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xbbadbeef pc=0x7f79b1c7a9fc]

runtime stack:
runtime.throw(0xba858c, 0x2a)
	/home/user_w/tools/go/src/runtime/panic.go:619 +0x81
runtime.sigpanic()
	/home/user_w/tools/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x9f7f60, 0xc420495fc0, 0x0)
	/home/user_w/tools/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420495f90 sp=0xc420495f58 pc=0x462bf4
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:12810 +0x41 fp=0xc420495fc0 sp=0xc420495f90 pc=0x85d651
github.com/gotk3/gotk3/gtk.Main()
	/home/user_w/go/src/github.com/gotk3/gotk3/gtk/gtk.go:929 +0x20 fp=0xc420495fd0 sp=0xc420495fc0 pc=0x8924a0
main.main.func1()

it seems that the underline C binding throws the exception.
Could you help to check this problem? thanks a lot.

**Comment by ns-cweber** [comment]
I don't think this is documented, but I'm pretty sure you need to pin `gtk.Main()` to the OS thread via `runtime.LockOSThread()`. This is just a guess from experience though.

**Comment by Diceshake** [comment]
> I don't think this is documented, but I'm pretty sure you need to pin `gtk.Main()` to the OS thread via `runtime.LockOSThread()`. This is just a guess from experience though.

I lock gtk.Main() and any goroutine that updates the UI - it has solved my intermittent crashing

**Comment by hopkings2008** [comment]
ok, thanks a lot

**Comment by yuancpfive** [comment]
@hopkings2008 
hi, It seem to that I meet the similar problem by using webloop, 
would you please tell me what's your code about using webloop in gotk3?
thanks a lot.

**Comment by hopkings2008** [comment]
> @hopkings2008
> hi, It seems that that I meet the similar problem by using webloop,
> would you please tell me what's your code about using webloop in gotk3, and give me some suggestions.
> thanks a lot.

just use the method proposed above
