### ISSUE TITLE
Using deprecated GtkStatusIcon parallel to current features not possible

### ISSUE THREAD

**Issue by founderio** [gotk3/gotk3#253]
GtkStatusIcon is deprecated, but there is no real replacement.
The GTK maintainers want us to use notifications it seems, but that might not be an option depending on the use case.
Unfortunately, GtkStatusIcon is not compiled unless we specify the correct build tag, `gtk_3_12` or earlier in this case. This has a side effect of disabling features that came with or after gtk 3.14.

I suggest an additional build tag `gtk_deprecated` that allows compiling deprecated features that sill work with more recent versions of gtk. After all, there might be a reason to use deprecated functions.

This way I can target a newer version of gtk, say 3.18 and keep using older APIs: `go get -t -tags "gtk_3_18 gtk_deprecated" github.com/gotk3...`

To avoid accidentally compiling code for later versions, that would probably require multiple tags, though..

I assume the deprecated pieces were removed because of these pesky compiler warnings? Would it be an option to hide them and keep the deprecated code always active?

**Comment by ergoz** [comment]
have same problem. I need status icon on windows in system tray to create menu in tray without application window. But i cant make it. Is there are any work-around for this?
