### ISSUE TITLE
Why not use gobject-introspection...?

### ISSUE THREAD

**Issue by grimmy** [gotk3/gotk3#269]
I'm curious why you decided to maintain your own manual language bindings when we have [gobject-intropsection](https://github.com/GNOME/gobject-introspection) and [go-gir-generator](https://github.com/linuxdeepin/go-gir-generator).

**Comment by russel** [comment]
The go-gir-generator project does say support for GTK+ and GDK is not yet complete, till then is it a viable option? Once that is complete then to switch to using GIR-based binding generation (as D and Rust have) is surely the right way forward.

**Comment by andreygursky** [comment]
> The go-gir-generator project does say support for GTK+ and GDK is not yet complete,..

Unfortunately, yes. But gotk3 suffers from the similar problem:
> Partial binding support for the following libraries is currently implemented ...

**Comment by grimmy** [comment]
Even if `go-gir-generator` needs work, it seems like the likely place for work to be done as all libraries are free then.  For example, [lgi](https://github.com/pavouk/lgi) can load anything that has a gir file, as does [gnomejs](https://gitlab.gnome.org/GNOME/gjs/wikis/Home) and [pygobject](http://pygobject.readthedocs.io/en/latest/getting_started.html).

As a third party library/application developer that exports a gir file, options like this are amazing as my maintenance cost goes nearly to zero, and when there are issues in the gir, once they're fixed they're fixed for all languages.  On top of that, there's no more language specific bindings for every application, they're just free via gobject-introspection.

**Comment by russel** [comment]
@grimmy I am very much in favour of not having pure manual binding creation, but I am not sure your comment "there's no more language specific bindings for every application" is actually right. Each language must still create a binding, it is just that the bulk of construction of the binding is automated. gtk-rs and GtkD are the examples I am using just now. gtkmm for C++, and gotk3 for Go do not use GIR files and so are not automatically created idiomatic bindings. gtk-rs and GtkD show the way forward for how to create language idiomatic bindings that are always up-to-date with each release.

**Comment by andreygursky** [comment]
> "there's no more language specific bindings for every application"

Indeed, I guess @grimmy means, that by using gobject introspection, there is no need to write manual bindings (in Go) for each GTK, GLib, GDK-Pixbuf and many other GObject base libraries. It is enough to get it *once* in something like go-gir-...

BTW, besides of the manually bindings writing approach (gotk3) and automatically generated (go-gir-...) there is yet another one. You don't even need to (automatically) generate them statically beforehand, simply use GObject based libraries through gcall: https://github.com/reusee/gcall (like with libffi).

**Comment by russel** [comment]
@andreygursky Yes you can simply call the C functions using libffi, but the really good thing about having a from GIR created binding is that the binding is idiomatic to the programming language. I tried using GTK in Kotlin/Native, which just uses the libffi approach, and it is awkward and irritating. Using the binding as per gtk-rs and GtkD makes for a much nicer programming experience, both writing and reading.

The sooner gotk3 switches from manual construction to using the GIR files, the better.

**Comment by grimmy** [comment]
Sorry I should have clarified... There is some manual bindings yes.. but that's for gobject-introspection in the each language.  However, there is literally no language bindings that need to be written for other applications.  So if I export a gir file, you can just it in say nodejs using NodeGir, and I as the provider of the library with the gir don't have to do anything.

**Comment by andre-hub** [comment]
https://github.com/gotk3/gotk3/wiki/gotk3-without-generator
