### ISSUE TITLE
 About cross compiling issue 

### ISSUE THREAD

**Issue by guomingyi** [gotk3/gotk3#270]
Hello,

I want to cross compiling gotk3 form archlinux to windows64 application referance from "https://github.com/gotk3/gotk3/wiki/Cross-Compiling", 
see bellow steep:

1. install depens:
sh-4.4# pacman -Sy --asdeps mingw-w64-cairo-bootstrap mingw-w64-freetype2-bootstrap -- success
sh-4.4# pacman -Sy --asdeps mingw-w64-gtk3 -- success

2. go get
sh-4.4# go get github.com/gotk3/gotk3/gtk
├── bin
│   └── dep
├── pkg
│   └── linux_amd64
│       └── github.com
│           └── gotk3
└── src
    ├── github.com
    │   └── gotk3
    │       ├── gotk3
    │       └── gtk-examples

--- success

3. go install
sh-4.4# sudo PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig GOPATH=$PWD CGO_ENABLED=1 CC=x86_64-w64-mingw32-cc GOOS=windows GOARCH=amd64 go install github.com/gotk3/gotk3/gtk
go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid

---- failed, what is wrong with me? 
Thanks for you answer.

**Comment by theZacAttacks** [comment]
I was running into the same issues, but I figured out the issue and was able to fix it!

It's probably not the best way, but it seemed to work for me 

you'll need to go and edit the following files:
/usr/x86_64-w64-mingw32/lib/pkgconfig/gdk-3.0.pc
 /usr/x86_64-w64-mingw32/lib/pkgconfig/gdk-broadway-3.0.pc
 /usr/x86_64-w64-mingw32/lib/pkgconfig/gdk-win32-3.0.pc

in the section "Libs" there should be a line with -Wl,-luuid
erase "-Wl," leaving "-luuid" and then try compiling again!
the rest of the cross-compiling guide worked for me!

however, I also had to copy over libfribidi-0.dll and had to rename libjasper-4.dll to libjasper.dll

Hope this helped!
