### ISSUE TITLE
I want to drop file.

### ISSUE THREAD

**Issue by mondy** [gotk3/gotk3#271]
I started making applications using gotk3.
I want to get file information dropped in an application.
But gotk3 does not appear implement a function related to file drop.
Is it possible to implement these functions?

We kindly ask for your consideration.

**Comment by BigFartTheory** [comment]
see there https://github.com/gotk3/gotk3/issues/326

**Comment by hfmrow** [comment]
Hi,
I was confronted with this problem,
check at: https://github.com/gotk3/gotk3/issues/343
this allowed me with the help of a connoisseur to understand why and so how to get file information and retrieve its data and use it.
I hope this will help you, even if your question is a bit old.
