### ISSUE TITLE
Container.GetChildren returns only widgets

### ISSUE THREAD

**Issue by danields761** [gotk3/gotk3#272]
Hi!

I'm using gtk.Builder to build UI for my app, that approach leads to necessary to obtain widgets from top-level widgets, which returned from builder. I'm using recursive traversal for it described [here](https://stackoverflow.com/questions/5401327/finding-children-of-a-gtkwidget).

But, currently, that's not possible because Container.GetChildren returns glib.List object, where `DataWrapper` wraps pointer only to gtk.Widget, and not uses private `cast` function. See [code here](https://github.com/gotk3/gotk3/blob/master/gtk/gtk.go#L2506).

There is a lot of workarounds, but some of them leads to copy whole `cast` function and to set `DataWrapper` on returned list manually, or wraps returned widget by mysel etc. but it would be nice to have official straight descision.

Thx!

**Comment by csoriano1618** [comment]
FWIW other bindings such as Rust convert all GList* to native Rust arrays. I think it's the best solution for bindings, although it has an increased performance impact.
