### ISSUE TITLE
Build fails with GTK 3.22

### ISSUE THREAD

**Issue by nilclass** [gotk3/gotk3#283]
I'm running on debian, with GTK packages:
```
$ dpkg -l libgtk-3\*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  libgtk-3-0:amd64                  3.22.11-1             amd64                 GTK+ graphical user interface library
ii  libgtk-3-bin                      3.22.11-1             amd64                 programs for the GTK+ graphical user interface library
ii  libgtk-3-common                   3.22.11-1             all                   common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64                3.22.11-1             amd64                 development files for the GTK+ library
```

The build fails as follows:
```
$ go get -v -tags gtk_3_22 github.com/gotk3/gotk3/gtk
github.com/gotk3/gotk3/glib
github.com/gotk3/gotk3/cairo
github.com/gotk3/gotk3/gdk
github.com/gotk3/gotk3/pango
github.com/gotk3/gotk3/gtk
# github.com/gotk3/gotk3/gtk
cgo-gcc-prolog: In function ‘_cgo_ec24e68943f7_Cfunc_gtk_widget_override_background_color’:
cgo-gcc-prolog:305:2: warning: ‘gtk_widget_override_background_color’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:8:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1148:14: note: declared here
 void         gtk_widget_override_background_color (GtkWidget     *widget,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/gotk3/gotk3/gtk
cgo-gcc-prolog: In function ‘_cgo_ec24e68943f7_Cfunc_gtk_widget_override_font’:
cgo-gcc-prolog:617:2: warning: ‘gtk_widget_override_font’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../../go/src/github.com/gotk3/gotk3/gtk/label.go:6:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1153:14: note: declared here
 void         gtk_widget_override_font             (GtkWidget                  *widget,
              ^~~~~~~~~~~~~~~~~~~~~~~~
# github.com/gotk3/gotk3/gtk
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:66: cannot use (*C.gchar)(cstr) (type *C.gchar) as type *C.char in argument to func literal
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:71: cannot use (func literal)(v.native()) (type *C.char) as type *C.gchar in argument to stringReturn
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:190: cannot use (*C.gchar)(cstr) (type *C.gchar) as type *C.char in argument to func literal
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:195: cannot use (func literal)(v.native()) (type *C.char) as type *C.gchar in argument to stringReturn
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:202: cannot use (*C.gchar)(cstr) (type *C.gchar) as type *C.char in argument to func literal
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:207: cannot use (func literal)(v.native()) (type *C.char) as type *C.gchar in argument to stringReturn
../../go/src/github.com/gotk3/gotk3/gtk/gtk_since_3_20.go:212: cannot use _Cfunc_CString(color) (type *C.char) as type *C.gchar in argument to _Cfunc_gdk_rgba_parse
```

The behavior is the same with and without `-tags gtk_3_22`.

**Comment by SMerrony** [comment]
Same here on up-to-date Msys64 on Windows.

**Comment by nilclass** [comment]
@SMerrony does https://github.com/gotk3/gotk3/pull/284 work for you?

**Comment by SMerrony** [comment]
@nilclass  - No it doesn't seem to make any difference.  The errors (warnings actually) are about deprecated functions so I wouldn't expect that PR to be relevant.

**Comment by utahcon** [comment]
Just ran into this myself

```
Fedora 29
gtk3-devel.x86_64 3.24.1 (3.24.1-1.fc29)
cairo-devel.x86_64 1.16.0 (1.16.0-1.fc29)
glib-devel.x86_64 1.2.10 (1:1.2.10-53.fc29)
```

**Comment by SamWhited** [comment]
I'm seeing this on Arch when trying to build the simple example in the README, which may be similar (except that I'm on 3.24)?

```
/usr/bin/ld: $WORK/b035/_x002.o: undefined reference to symbol 'g_value_get_enum'
/usr/bin/ld: /usr/lib/libgobject-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

```
$ pacman -Q gtk3
gtk3 3.24.2+7+g43aeb52b73-1
```

**Comment by Bios-Marcel** [comment]
@SamWhited In your case it just can't find the library I'd say. Probably not a gotk3 bug though, but some problem with your setup.

**Comment by akarl** [comment]
@SamWhited I'm having the same issue (also Arch). Have you found any solution?

**Comment by SamWhited** [comment]
@akarl no, I used Rust and gtk-rs for the project instead; I wanted Go for another unrelated library, but Rust has better C integration and the project needs to be in GTK3 so ¯\\\_(ツ)_/¯

**Comment by orivej** [comment]
@SamWhited's problem is that the program is linked without `-lgobject-2.0` flag. What is the output of `pkg-config --libs gobject-2.0`? Could you open a new issue, since it is not relevant to the issue originally reported here?

**Comment by SamWhited** [comment]
@orivej is this actually a problem with gotk3 somehow then? I'd think it would be a cgo thing in that case. Happy to file an issue if so though. Output is:

```
-lgobject-2.0 -lglib-2.0
```

**Comment by orivej** [comment]
That output is correct…

I don't know if the problem is in gotk3 or not, but I'm uncomfortable discussing it in an unrelated issue.

I have checked with this dockerfile and the example was built successfully:
```
from base/archlinux
run pacman -Sy
run pacman -S --noconfirm gcc git go gtk3 pkgconfig
run go get -v github.com/gotk3/gotk3-examples/gtk-examples/simple
```

If `go get github.com/gotk3/gotk3-examples/gtk-examples/simple` fails on your host with `undefined reference to symbol 'g_value_get_enum'`, it would help if you could install [fptrace](https://github.com/orivej/fptrace), trace building the example, and attach `/tmp/trace.json`:
```
go get github.com/orivej/fptrace
go generate github.com/orivej/fptrace
fptrace -d /tmp/trace.json go build github.com/gotk3/gotk3-examples/gtk-examples/simple
```

**Comment by SamWhited** [comment]
@orivej is this actually a problem with gotk3 somehow then? I'd think it would be a cgo thing in that case. Happy to file an issue if so though. Output is:

```
-lgobject-2.0 -lglib-2.
```

**Comment by SamWhited** [comment]
Sorry, there doesn't appear to be an Arch package and I don't have the time to vet it and build it myself right now. If you have some specific information you need that I can get with more standard tooling I'll try to help though.

**Comment by Sergii-Kirichok** [comment]
> @SamWhited, #318 has just been reported and it looks the same. `fptrace` of any `go build` failing with `g_value_get_enum` would be very useful.

I decided to reinstall all and wrote spet by step what I did.

- Downloaded and install latest msys from http://repo.msys2.org/distrib/x86_64/
- run msys pacman -Syu close window by pressing X 
- run msys again and run pacman -Su
- then run pacman --noconfirm -S mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk3
- run pacman -S mingw-w64-x86_64-go //Install GO directly to msys
- run bash -c "sed -i -e 's/-Wl,-luuid/-luuid/g' C:/msys64/mingw64/lib/pkgconfig/gdk-3.0.pc"
- edit path, added C:\msys64\mingw64\bin
- Create vatiable GOPATH c:\GoPath
- Create valiable GOROOT C:\msys64\mingw64\lib\go\
- then I run cmd and run go get github.com/gotk3/gotk3/gtk
and got the same error

    C:\Users\111>go get github.com/gotk3/gotk3/gtk
    # github.com/gotk3/gotk3/pango
    C:\Users\111\AppData\Local\Temp\go-build113739042\b034\_x002.o: In function 
    `_cgo_d7fe93989068_Cfunc_g_value_get_enum':
    /tmp/go-build/cgo-gcc-prolog:56: undefined reference to `g_value_get_enum'
    C:\Users\111\AppData\Local\Temp\go-build113739042\b034\_x004.o: In function 
    `_cgo_d7fe93989068_Cfunc_g_value_get_boxed':
    /tmp/go-build/cgo-gcc-prolog:62: undefined reference to `g_value_get_boxed'
    collect2.exe: error: ld returned 1 exit status

Then I run your example
C:\GoPath\src\Home\GuiTest>go get -v github.com/gotk3/gotk3-examples/gtk-examples/simple
github.com/gotk3/gotk3-examples (download)
github.com/gotk3/gotk3/pango
# github.com/gotk3/gotk3/pango
C:\Users\111\AppData\Local\Temp\go-build561467870\b035\_x002.o: In function `_cgo_d7fe93989068_Cfunc_g_value_get_enum':
/tmp/go-build/cgo-gcc-prolog:56: undefined reference to `g_value_get_enum'
C:\Users\111\AppData\Local\Temp\go-build561467870\b035\_x004.o: In function `_cgo_d7fe93989068_Cfunc_g_value_get_boxed':
/tmp/go-build/cgo-gcc-prolog:62: undefined reference to `g_value_get_boxed'
collect2.exe: error: ld returned 1 exit status

and finaly I did 
go get github.com/orivej/fptrace
C:\GoPath\src\Home\GuiTest>go get github.com/orivej/fptrace
# github.com/orivej/fptrace
..\..\github.com\orivej\fptrace\main.go:28:2: undefined: syscall.PTRACE_EVENT_FORK
..\..\github.com\orivej\fptrace\main.go:29:2: undefined: syscall.PTRACE_EVENT_VFORK
..\..\github.com\orivej\fptrace\main.go:30:2: undefined: syscall.PTRACE_EVENT_VFORK_DONE
..\..\github.com\orivej\fptrace\main.go:31:2: undefined: syscall.PTRACE_EVENT_CLONE
..\..\github.com\orivej\fptrace\main.go:183:8: undefined: syscall.PTRACE_EVENT_FORK
..\..\github.com\orivej\fptrace\main.go:184:4: undefined: syscall.PTRACE_EVENT_VFORK
..\..\github.com\orivej\fptrace\main.go:185:4: undefined: syscall.PTRACE_EVENT_VFORK_DONE
..\..\github.com\orivej\fptrace\main.go:186:4: undefined: syscall.PTRACE_EVENT_CLONE
..\..\github.com\orivej\fptrace\main.go:188:20: undefined: syscall.PtraceGetEventMsg
..\..\github.com\orivej\fptrace\trace.go:17:24: undefined: syscall.PtraceRegs
..\..\github.com\orivej\fptrace\main.go:188:20: too many errors
