### ISSUE TITLE
Installing gotk3 on Windows 10 (msys2)

### ISSUE THREAD

**Issue by ghost** [gotk3/gotk3#288]
I've been trying to install gotk3 for the past few days now, and I'm getting this error:

`go\src\github.com\gotk3\gotk3\glib\application.go:157:2: could not determine kind of name for C.g_application_send_notification
go\src\github.com\gotk3\gotk3\glib\application.go:165:2: could not determine kind of name for C.g_application_withdraw_notification
cgo:
gcc errors for preamble:
In file included from go\src\github.com\gotk3\gotk3\glib\application.go:7:
./glib.go.h:95:8: error: unknown type name 'GNotification'
 static GNotification *
        ^~~~~~~~~~~~~
` when running `go get github.com/gotk3/gotk3/gtk`

I've followed the guide (using old Fedora 20 rpms, and using msys2 to install mingw because the links in the guide don't work)

My path has C:\Fedora, the gopath and gohome, and it has the msys2/mingw64/bin folders.

**Comment by Bios-Marcel** [comment]
I'd say your version of glib is outdated.

Check this out: https://github.com/UwUNote/uwunote/issues/1#issuecomment-414850043

**Comment by Bios-Marcel** [comment]
I have updated the guide on the wiki, it should work now if you follow that:

https://github.com/gotk3/gotk3/wiki/Installing-on-Windows
