### ISSUE TITLE
Question: How to statically build for Windows on Windows

### ISSUE THREAD

**Issue by Bios-Marcel** [gotk3/gotk3#292]
Hey,

I am trying to ship my application as a single executable file, but I have no clue how to do that using msys2.

I have tried this:
```
go build -ldflags "-H windowsgui -linkmode external -extldflags -static" main.go 
```
but gtk and gdk libs can't be found:
```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgtk-3
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgdk-3                                                            
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgdk-3
collect2.exe: error: ld returned 1 exit status      
```

How'd I solve that?

**Comment by founderio** [comment]
Speaking from my experiences on cross-compiling on Linux, for Windows, you might need to do a `go install` for the relevant libraries.

Try something like this:
```
go install -v github.com/gotk3/gotk3/gtk
go install -v github.com/gotk3/gotk3/gdk
go build ...
```

**Comment by Bios-Marcel** [comment]
1. I am not crosscompiling
2. I do have the neccessary dependencies (go code and external dependencies)

What I am trying is to create a static executable file (.exe) for windows. Currently anyone that wants to run the app has to install gtk, gdk, glib and so on. Obviously no user can be arsed to do that. So i was wondering how I'd make a statically compiled executable that contains all neccessary dependencies.

**Comment by founderio** [comment]
Yes, I'm aware of numer 1 and 2 :)
Sorry for being unclear.

My assumption was that you need to compile the dependent libraries first.

If not, maybe your library search paths are incomplete..

If it helps your issue (for now), this step is in my compile process:
```
cp -v $(USR_MINGW)/bin/{libgcc_s_seh-1.dll,libatk-1.0-0.dll,libbz2-1.dll,libcairo-2.dll,libcairo-gobject-2.dll,libepoxy-0.dll,libexpat-1.dll,libffi-6.dll,libfontconfig-1.dll,libfreetype-6.dll,libgdk-3-0.dll,libgdk_pixbuf-2.0-0.dll,libgio-2.0-0.dll,libglib-2.0-0.dll,libgmodule-2.0-0.dll,libgobject-2.0-0.dll,libgraphite2.dll,libgtk-3-0.dll,libharfbuzz-0.dll,libiconv-2.dll,libintl-8.dll,libjasper.dll,libjpeg-8.dll,libpango-1.0-0.dll,libpangocairo-1.0-0.dll,libpangoft2-1.0-0.dll,libpangowin32-1.0-0.dll,libpcre-1.dll,libpixman-1-0.dll,libpng16-16.dll,libstdc++-6.dll,libwinpthread-1.dll,zlib1.dll} $(OUT)/
```

Basically copy all the dependent dlls with your app.. This of course does not produce a single binary.

**Comment by Bios-Marcel** [comment]
Well I thought of that as a possible approach, but what I see as a downside is having to hardcode the libraries that are necessary. If creating a static binary in a simple way would be possible, that'd really be helpful. Also having multiple files makes updating much more complex. I think there is nothing easier than just having a single binary.

Anyways, thanks for the tip. I might just do that until I figure out an easier way.

**Comment by zhaiguanjie7** [comment]
Is there a easier way now ?
