### ISSUE TITLE
Windows Installation seems broken

### ISSUE THREAD

**Issue by Wulfheart** [gotk3/gotk3#296]
Hello,

in my opinion the windows installation process isn't working anymore as there are some download links who don't work anymore. Any way to simplify this?
Thank you in advance

**Comment by Bios-Marcel** [comment]
https://github.com/UwUNote/uwunote/issues/1

Check my comments on this.

**Comment by deef0000dragon1** [comment]
I have been trying to get this to work for a few hours now, but even following the comments and trying to set the proper vars, I keep getting 
`go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid`

what is the exact regex and variable name that I need to set that you got to work? Do i set it in user or system?

**Comment by Wulfheart** [comment]
Is there any way to provide a simple patch?

**Comment by Bios-Marcel** [comment]
I simply ran `sed` to fix the broken pkg-config file:

```
bash -c "sed -i -e 's/-Wl,-luuid/-luuid/g' C:/msys64/mingw64/lib/pkgconfig/gdk-3.0.pc"
```

**Comment by deef0000dragon1** [comment]
thanks. It appears that I can now get it to start compiling, however, I run into compilation issues instead
` cgo-gcc-prolog:317:2: warning: 'gtk_widget_override_background_color' is deprecated [-Wdeprecated-declarations]` 
etc. trying to compile the grid example. 

The only other talk that I have seen about this says to add -x -work and see what it is doing, but I cant get any extra information out of that compared to what has already been printed.

**Comment by Bios-Marcel** [comment]
Its a deprecation warning, not an error. Ignore it for now, it's gotk3 that needs to fix it.

**Comment by deef0000dragon1** [comment]
I would, except I dont know how. First time working with cgo/c warnings in go. I dont actually know how to force it to give me an executable.

**Comment by deef0000dragon1** [comment]
ok, so I tried setting the output manually, and that managed to get it to work to where I have an executable, however, it appears that I cant run the executable. I get a "This app cant run on your PC." I did set GOOS and GOARCH. Both manually before, and using my compile command `GOOS=windows GOARCH=amd64 go build -o output.exe` Neither worked.

**Comment by Bios-Marcel** [comment]
Do you know where the output `This app cant run on your PC` comes from? I have never seen that before. What OS are you on, Windows, MacOS, BSD or Linux? Did you want to crosscompile? Did you compile on the same platform as you tried running your executable on?

**Comment by deef0000dragon1** [comment]
yeah. that's a windows dialog I get when trying to run it from the windows file explorer. 
command line gives me, 
```
$ ./output.exe
./output.exe: line 1: syntax error near unexpected token `newline'
./output.exe: line 1: `!<arch>'
```
opening the exe in a text editor, because why not, I get 
```
!<arch>
__.PKGDEF       0           0     0     644     161       `
go object windows amd64 go1.11 X:framepointer
build id "LPbjz1t4zJvMqKw3XmLa/Xqa_AieVi_UNEeeb081s"
----
```

I am on windows. Trying to compile one of the example programs to windows. Eventually want to be able to cross compile it to Linux as well. Ideally anyway.

**Comment by Wulfheart** [comment]
Ok. This begins to suck. Definitely gonna switch to Linux.

**Comment by Jacalz** [comment]
This seems to be broken again. I can’t get the Mingw installer to work and in general the whole windows install section seems out of date. I am a Linux user but I have written an app with this package and I really need to build it for Windows since it’s a school project.

**Comment by wrycode** [comment]
The wiki instructions are out of date. I was able to get my program working on Windows 10 after reading this: https://gianlucacosta.info/blog/go-gui-apps-on-windows

He includes a few extra steps that might not be necessary. Basically, install the GTK libraries using MSYS2 using the instructions from the GTK website: https://www.gtk.org/download/windows.php
You also need to install GCC through pacman. You DO need to add the correct msys folders to your PATH (in Windows, not your .bashrc in MSYS).

Then install Go, Git, and your project and its dependencies and "go build" and "go install" should work fine.

**Comment by wrycode** [comment]
In regards to the `go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid` error that @deef0000dragon1 was having, for me this was due to pkg-config being installed from a different source (the "MinGW Installation Manager", I think) vs MSYS and pacman.

**Comment by wrycode** [comment]
> In regards to the `go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid` error that @deef0000dragon1 was having, for me this was due to pkg-config being installed from a different source (the "MinGW Installation Manager", I think) vs MSYS and pacman.

Nevermind, this is incorrect. Still, following the "Using GTK from MSYS2 packages" header on the gtk website worked better for me than downloading from the mingw-w64 website suggested in the wiki.

**Comment by Jacalz** [comment]
I am getting this error when installing:
```
..\github.com\gotk3\gotk3\gtk\gtk_since_3_16.go:158:8: could not determine kind of name for C.free
```

**Comment by hfmrow** [comment]
@Jacalz 
Hi,
look at https://github.com/gotk3/gotk3/issues/444
there is a linux user with same issue.

**Comment by andre-hub** [comment]
You still have that problem?

Have you ever tried following the [instructions described in our Wiki](https://github.com/gotk3/gotk3/wiki/Installing-on-Windows).

**Comment by andre-hub** [comment]
There has been no feedback on whether the problem continues. I am therefore closing this issue until further notice. If there is still a need, please open this issue again and add a current problem description.
