### ISSUE TITLE
Easier/faster way to get objects from Glade file?

### ISSUE THREAD

**Issue by pycebs** [gotk3/gotk3#298]
I'm using gotk3 with Glade. I use a function like this to get all my buttons:

```
func getButton(b *gtk.Builder, name string) (*gtk.Button, error) {

	obj, err := b.GetObject(name)
	if err != nil {
		return nil, err
	}

	button, ok := obj.(*gtk.Button)
	if !ok {
		return nil, err
	}

	return button, nil
}
```
Then I can just use something like

```
firstButton, _ := getButton(bldr, "first_button")
secondButton, _ := getButton(bldr, "second_button")
// and so on...
```

That works, but I also have a headerbar, panes, GtkBoxes, and loads of other types of Gtk objects. And for each object class/type I need a new function like "getButton". (i.E. getWindow, getPopover, getGtkbox, and so on.)

Isn't there an easier way to do this?

I used to use PyGObject and it was fairly simple:

```
self.builder = Gtk.Builder()
self.builder.add_from_file("gui.glade")

# And now I can get all types with just one line like so:
self.headerbar = self.builder.get_object("headerbar")
self.some_button = self.builder.get_object("some_button")
self.some_paned = self.builder.get_object("some_paned")
self.some_window = self.builder.get_object("some_window")
# and so on...
```
Is there a way to do this in gotk3 as well? So that I don't need to have an extra init function for each type of Gtk object/class?

**Comment by Bios-Marcel** [comment]
I think.the initial Design idea in gotk3 was to not risk letting you run into a `nil` dereferencing error. Therefore this probably won't be introduced.

**Comment by pycebs** [comment]
Alright. Thanks for your input!
