### ISSUE TITLE
Not comma separating build tags breaks build

### ISSUE THREAD

**Issue by freddieptf** [gotk3/gotk3#300]
I just stumbled into this issue where builds would fail when i passed a build tag because the build tags defined in the new files introduced in #299 were not comma separated. 

https://github.com/gotk3/gotk3/blob/de3c6aa936d239fd2d27c351ecb71883aa4f2c5c/gdk/gdk_since_3_22.go#L1

I'm on ubuntu 16.04, gtk 3.18.9. I changed it to [this](https://github.com/freddieptf/gotk3/blob/6f5ec39a2fd3da65cda9a832fc3fbb02575968fe/gdk/gdk_since_3_22.go#L1) and it worked

**Comment by andre-hub** [comment]
thanks for you infomation, i have forgot check this line.
