### ISSUE TITLE
Add support for: gdk_pixbuf_new_from_data, gdk_pixbuf_new_from_bytes

### ISSUE THREAD

**Issue by AnimusPEXUS** [gotk3/gotk3#301]

**Comment by Bios-Marcel** [comment]
FYI, you can already create a `pixbuf` from `[]byte`:

```
pixbufLoader, _ := gdk.PixbufLoaderNew()
iconAsPixbuf, _ := pixbufLoader.WriteAndReturnPixbuf(Icon)
```

**Comment by AnimusPEXUS** [comment]
TY. this covers My need.

**Comment by Bios-Marcel** [comment]
I was wondering ... don't we already have `GdkPixbuf` specific code inside of the `Gdk` package? If so, how'd we separate it without breaking code? Should we just make delegation functions?

**Comment by andre-hub** [comment]
I'm afraid it's all jumbled up in just two namespaces. Maybe we really should use some type of delegation function.

**Comment by andre-hub** [comment]
yes, we have pixbuf

https://pkg.go.dev/github.com/gotk3/gotk3/gdk?tab=doc#Pixbuf

but exactly these two methods are missing

**Comment by MJacred** [comment]
wrote bindings for the two missing funcs.

@Bios-Marcel, @andre-hub:
we should probably split this like Gtk (as mentioned above) and make a gdk-pixbuf package (on the same level as gtk, gdk, cairo, etc.) and implement it for v0.6.0. If that's fine, I'll open a new issue with the info
