### ISSUE TITLE
How to find which radio button is selected?

### ISSUE THREAD

**Issue by Northern-Lights** [gotk3/gotk3#306]
I am attempting to find which radio button in a group is the selected one.  I am able to get the group using [`RadioButton.GetGroup()`](https://godoc.org/github.com/gotk3/gotk3/gtk#RadioButton.GetGroup), but this returns a `glib.SList`.  It is unclear to me how to use this pointer to obtain a `*gtk.RadioButton` back in the Go world.  Any tips are appreciated.

Thanks in advance.

**Comment by Bios-Marcel** [comment]
For the sake of having a proper API you might just write your own group, but still use the gtk approach internally. Not sure if that's overengineering though ^^

**Comment by Bios-Marcel** [comment]
As far as I can see, there isn't really a correct answer to this question, if nobody interjects, I am going to close this issue tomorrow.

**Comment by Northern-Lights** [comment]
Agreed. Would it be out of the scope of the gtk package to write some functions handling, specifically, radio button groups? I may want to try my hand at it in the future.

**Comment by Bios-Marcel** [comment]
In my opinion it shouldn't be part of the gotk3 package, as it is `Go bindings for GTK+3 and dependent projects`. Maybe we could make a new project that belongs to the gotk3 organization though? However, I don't have the permission to decide that. You can however start it as your own project and ask for permission to move it into gotk3, maybe as a separate repository, as I mentioned.
