### ISSUE TITLE
Can't find gdk_cairo_create(GdkWindow *window)

### ISSUE THREAD

**Issue by Litarvan** [gotk3/gotk3#308]
I need `gdk_cairo_create(GdkWindow *window);`, but i only found cairo.Create(surface *cairo.Surface) (and no cairo.Create(window *gdk.Window) even with a different name).

I opened this issue to ask if it was implemented and i just didn't find it, or if i had to implement it (If i have, is it as simple as creating a function similar to the other ones in cairo.go ?).

**Comment by Bios-Marcel** [comment]
Yup, looks like it doesn't exist, but it should be easy to add.

**Comment by Litarvan** [comment]
Managed to get the context from an event, not necessary anymore (also I saw this function is deprecated since GTK 2.22)
