### ISSUE TITLE
Can't run on win7 x64 - can't find g_value_get_enum

### ISSUE THREAD

**Issue by Sergii-Kirichok** [gotk3/gotk3#318]
Hi,
Can't run it on win7 x64. 
Installed:
    msys2-x86_64-20180531 
    go.1.11.4
    all dependencies and paths

But when I run go get gotk i got this error.

    go get -u github.com/gotk3/gotk3/gtk
    # github.com/gotk3/gotk3/pango
    C:\Users\Admin\AppData\Local\Temp\go-build135719158\b035\_x002.o: In function             
    `_cgo_d7fe93989068_Cfunc_g_value_get_enum':
    /tmp/go-build/cgo-gcc-prolog:56: undefined reference to `g_value_get_enum'
    C:\Users\Admin\AppData\Local\Temp\go-build135719158\b035\_x004.o: In function 
    `_cgo_d7fe93989068_Cfunc_g_value_get_boxed':
    /tmp/go-build/cgo-gcc-prolog:62: undefined reference to `g_value_get_boxed'
    collect2.exe: error: ld returned 1 exit status

Could you please help me with it.

**Comment by orivej** [comment]
Re. https://github.com/gotk3/gotk3/issues/283#issuecomment-451962104, could you edit `github.com/gotk3/gotk3/pango/pango-layout.go` and `pango-attributes.go` and replace
`#cgo pkg-config: pango` with `#cgo pkg-config: pango gobject-2.0` (maybe `glib-2.0` is needed too).

**Comment by Bios-Marcel** [comment]
@orivej So, can you imagine why this onlyhappens on some setups? It worked fine on my Arch and Ubuntu installation, but fails on windows. And why hasn't this happened earlier? Is there a apecific commit that caused it?

**Comment by orivej** [comment]
@Bios-Marcel It happens if `pkg-config --libs pango` does not include `-lgobject-2.0`. The following would help to determine why.

@Sergii-Kirichok or @SamWhited, could you post the output of:
```
pkg-config --libs pango
cat /usr/lib/pkgconfig/pango.pc
cat /usr/lib/pkgconfig/gobject-2.0.pc
pacman -Qo /usr/lib/pkgconfig/gobject-2.0.pc /usr/lib/pkgconfig/pango.pc
```

Certainly, this was not a change in `gotk3`, but in packaging `pango` on the affected systems. However, I think that it is a `gotk3` fault of not explicitly listing all direct dependencies. I am going to automatically update `cgo pkg-config` lines and send a PR.

**Comment by SamWhited** [comment]
Yup, good catch.

```
$ pkg-config --libs pango
-lpango-1.0
```

**Comment by Sergii-Kirichok** [comment]
> pacman -Qo /usr/lib/pkgconfig/gobject-2.0.pc /usr/lib/pkgconfig/pango.pc `which pkg-config`

Admin@Star-Office MSYS ~
# pkg-config --libs pango
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found

Admin@Star-Office MSYS ~
# cat /usr/lib/pkgconfig/pango.pc
cat: /usr/lib/pkgconfig/pango.pc: No such file or directory

Admin@Star-Office MSYS ~
# cat /usr/lib/pkgconfig/gobject-2.0.pc
cat: /usr/lib/pkgconfig/gobject-2.0.pc: No such file or directory

Admin@Star-Office MSYS ~
# pacman -Qo /usr/lib/pkgconfig/gobject-2.0.pc /usr/lib/pkgconfig/pango.pc `which pkg-config`
ошибка: Ни один пакет не содержит '/usr/lib/pkgconfig/gobject-2.0.pc'
ошибка: Ни один пакет не содержит '/usr/lib/pkgconfig/pango.pc'
ошибка: Ни один пакет не содержит '/usr/bin/pkg-config'

Admin@Star-Office MSYS ~
