### ISSUE TITLE
.GetChildren().Foreach() returns glib.InitiallyUnowned in *gtk.Widget instead of *gtk.Box

### ISSUE THREAD

**Issue by diamondburned** [gotk3/gotk3#321]
Code ([detailed implementation](https://gitlab.com/diamondburned/gtkcord/blob/master/editmsg.go)): 

```go
glib.IdleAdd(func() {
	// msgElems.MessagesBox type *gtk.Box
	msgElems.MessagesBox.GetChildren().Foreach(func(item interface{}) {
		if box, ok := item.(*gtk.Box); ok {
			log.Println("Element is a box!")
		} else {
			log.Println("Not a box!")
			spew.Dump(item)
		}
	})
})
```

Dump: 

```go
(*gtk.Widget)(0xc000190528)({
 InitiallyUnowned: (glib.InitiallyUnowned) {
  Object: (*glib.Object)(0xc000190520)({
   GObject: (*glib._Ctype_struct__GObject)(0x7ff0f44d65c0)({
    g_type_instance: (glib._Ctype_struct__GTypeInstance) {
     g_class: (*glib._Ctype_struct__GTypeClass)(0x7ff1140e53b0)({
      g_type: (glib._Ctype_ulong) 26407328
     })
    },
    ref_count: (glib._Ctype_uint) 3,
    _: ([4]uint8) (len=4 cap=4) {
     00000000  00 00 00 00                                       |....|
    },
    qdata: (*glib._Ctype_struct__GData)(<nil>)
   })
  })
 }
})
```

Expected behavior: `item` is type `*gtk.Box` as in [here](https://gitlab.com/diamondburned/gtkcord/blob/master/addmsg.go#L156)

Detailed implementation of `msgElems.MessagesBox`: 

1. [messagebox type `*gtk.Box` is created, then is set as `MessageBox` in `msgElems`](https://gitlab.com/diamondburned/gtkcord/blob/master/addmsg.go#L138)
2. [wrap type `*gtk.Box` is created then added into messagebox](https://gitlab.com/diamondburned/gtkcord/blob/master/addmsg.go#L149)
3. [Unrelated logic which adds labels, boxes, etc into wrap box](https://gitlab.com/diamondburned/gtkcord/blob/master/addmsg.go#L154)

**Comment by diamondburned** [comment]
Another test sample with unexpected behavior: https://hastebin.com/pahedafali.go

**Comment by orivej** [comment]
This works as intended: `gtk.Container.GetChildren()` returns pure `*gtk.Widget` items, not `*gtk.Box` items cast to `*gtk.Widget`. You may do this:
```go
boxType := box1.TypeFromInstance()

if item.(*gtk.Widget).IsA(boxType) {
        box := (*gtk.Box)(unsafe.Pointer(item.(*gtk.Widget)))
}
```
