### ISSUE TITLE
Add GtkPixbufAnimation

### ISSUE THREAD

**Issue by diamondburned** [gotk3/gotk3#322]
I was looking through forks and saw this guy's fork having GtkPixbufAnimation: https://github.com/d2r2/gotk3

Can we have this feature in the current gotk3 repo? I'm working on a fairly large project and that repo doesn't have what I'm using here. Funny enough, this repo doesn't have what I need from that one.

**Comment by Bios-Marcel** [comment]
You could just make a pr from his repo I think :thinking:

Or you fork his repo and make a pr from your fork.

**Comment by diamondburned** [comment]
This is already implemented.
