### ISSUE TITLE
window.SetKeepAbove not work

### ISSUE THREAD

**Issue by wocan23** [gotk3/gotk3#323]
I open a new window and want it to show above the original window,So I write below:
`newWindow.SetKeepAbove(true)`,but the new window is below ,can you give me some suggests?

**Comment by wocan23** [comment]
The code is

`
func mainFunc()  {
	// Create Gtk Application, change appID to your application domain name reversed.
	const appID = "org.gtk.es"
	application, err := gtk.ApplicationNew(appID, glib.APPLICATION_FLAGS_NONE)
	// Check to make sure no errors when creating Gtk Application
	if err != nil {
		log.Fatal("Could not create application.", err)
	}
	application.Connect("activate", func() { onActivate(application) })
	os.Exit(application.Run(os.Args))
}

func onActivate(application *gtk.Application) {
	// Create ApplicationWindow
	appWindow, err := gtk.ApplicationWindowNew(application)
	if err != nil {
		log.Fatal("Could not create application window.", err)
	}
	// Set ApplicationWindow Properties
	appWindow.SetTitle("Basic Application.")
	appWindow.SetDefaultSize(common.WindowWidth, common.WindowHeight)

	btn,_ := gtk.ButtonNewWithLabel("new window")
	btn.Connect("button_press_event", func() {
		connWin,_ :=  gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
		connWin.SetKeepAbove(true)
		connWin.SetFocusVisible(true)
		connWin.SetPosition(gtk.WIN_POS_CENTER)
		connWin.SetTitle("create conn")
		connWin.SetSizeRequest(common.ConnWindowWidth,common.ConnWindowHeight)

		label,_ := gtk.LabelNew("test")
		box,_ := gtk.BoxNew(gtk.ORIENTATION_HORIZONTAL,0)
		box.Add(label)
		connWin.Add(box)

		connWin.ShowAll()
	})
	appWindow.Add(btn)

	common.GlobalWin = appWindow
	appWindow.SetPosition(gtk.WIN_POS_CENTER)
	appWindow.SetTypeHint(gdk.WINDOW_TYPE_HINT_DIALOG)
	appWindow.ShowAll()
}
`

I want to see [https://github.com/wocan23/tmp/blob/master/QQ20190112-080250%402x.png](url)
but I see [https://github.com/wocan23/tmp/blob/master/QQ20190112-080310%402x.png](url)

**Comment by Bios-Marcel** [comment]
Your links don't work ^^

**Comment by wocan23** [comment]
[wanted](https://github.com/wocan23/tmp/blob/master/QQ20190112-080250@2x.png?raw=true)
[now](https://github.com/wocan23/tmp/blob/master/QQ20190112-080310@2x.png?raw=true)

**Comment by Bios-Marcel** [comment]
The next time you include an example, please make it as minimal, but complete as possible, so that I can just copy paste it into my editor and it works (import paths and such are missing)

**Comment by Bios-Marcel** [comment]
Okay, I just made a minimal example for you:

```go
package main

import (
	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	gtk.Init(nil)

	app, _ := gtk.ApplicationNew("just.works.iguess", glib.APPLICATION_FLAGS_NONE)
	window, _ := gtk.ApplicationWindowNew(app)

	button, _ := gtk.ButtonNewWithLabel("Show dialog")
	button.Connect("clicked", func() {
		subWindow, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)

		subWindow.SetTransientFor(window)
		subWindow.SetModal(true)
		label, _ := gtk.LabelNew("Hello world")
		subWindow.Add(label)

		subWindow.ShowAll()
	})
	window.Add(button)
	window.ShowAll()

	gtk.Main()
}
```

This creates two normal windows, one of which is transient for its parent and is modal. Disallowing the parent to be in front of the child and keeping you from interacting with the parent.

**Comment by wocan23** [comment]
Thank you very much,I will read it
