### ISSUE TITLE
Aplication closed after I change the language

### ISSUE THREAD

**Issue by Sergii-Kirichok** [gotk3/gotk3#324]
Application immediately closing after I changed the language, and don't matter do I did it by hotkeys or by mouse.
I workin on Win7 x64, go version go1.11.4 windows/amd64

    src>go run sample.go
    exit status 3221226356

If I need to place here any additional data,  please feel free to ask me. 
Just made a descigion - it crashes when I try to switch from English to Russian or from any language to Not English/

**Comment by Sergii-Kirichok** [comment]
Tryed to debug it

    >dlv debug sample.go
    Type 'help' for list of commands.
    (dlv) continue
    Stopped at: 0x772ef3b0
    =>no source available
    (dlv) continue
    Process 2700 has exited with status 3221226356
   (dlv)

When I tryed to swith language it got      Stopped at: 0x772ef3b0 =>no source available, then  I run it by continue - window closed and aplication exited.

**Comment by Bios-Marcel** [comment]
Would you mind trying to reproduce the same problem without gotk3, but with gtk3 in c or vala?

**Comment by Sergii-Kirichok** [comment]
@Boris-Marcel sure, I will try hello world on "c"

**Comment by logrusorgru** [comment]
The same on Win8.1 emulated using Virtualbox. Exit status is 127.

**Comment by logrusorgru** [comment]
Inside `gdb`.

![default](https://user-images.githubusercontent.com/4060258/51249413-3b326480-19a4-11e9-9f4c-a6a4f5a040ac.png)
Where the `main.exe` is hello world from README.

**Comment by logrusorgru** [comment]
Seems, it's about accessing invalid memory address.

**Comment by logrusorgru** [comment]
The same for this C example https://developer.gnome.org/gtk3/stable/gtk-getting-started.html#id-1.2.3.5

---
So, it's GTK+3 issue.

**Comment by Bios-Marcel** [comment]
Thanks for testing that, I'll be closing the issue then.

**Comment by logrusorgru** [comment]
Issue on GTK issue tracker: https://gitlab.gnome.org/GNOME/gtk/issues/1596
