### ISSUE TITLE
drag and drop files on gotk3 app?

### ISSUE THREAD

**Issue by BigFartTheory** [gotk3/gotk3#326]
I drag file on label and got panic. 
(panic: reflect.Value.Convert: value of type uintptr cannot be converted to type *gtk.SelectionData)
I can use "uintptr" but how to get file names?
I use Linux Mint's file nameger to drag file on go-app.

space, _ = gtk.LabelNew("")
t_uri, _ := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
space.DragDestSet(gtk.DEST_DEFAULT_ALL, []gtk.TargetEntry{*t_uri}, gdk.ACTION_COPY)
space.Connect("drag-data-received", func(g *gtk.Label, ctx *gdk.DragContext, x int, y int, data *gtk.SelectionData, info uint, _ uint) {
	// panic:
})

**Comment by GrayNerd** [comment]
Try using gtk.GetData. This code is untested but based on working code that drags files to a window.  I also used "text/plain" as the target.

space.Connect("drag-data-received", func(g *gtk.Label, ctx *gdk.DragContext, x,int y int, data uintptr, m int, t uint) {
		space.SetLabel(string(gtk.GetData(data)))
})

I also found that I need to consume the "drag-drop"event to get the drag-data-received event to work.  Although I was dragging to a window, not a label.

**Comment by BigFartTheory** [comment]
"Try using gtk.GetData" - You God Damn Right. BIG Thank you!
"also used text/plain" - try to drag selected text from notepad. "text/uri-list" is better
"I was dragging to a window, not a label" - of course =)

Now i just need to fix encoding for Russian chars ("file:///mnt/dm-1/%D0%BC%D1%83%D1%81%D0%BE%D1%80" to "file:///mnt/dm-1/мусор")
