### ISSUE TITLE
Are "gtk_drag_source_set" & "gtk_selection_data_set" functions implemented?

### ISSUE THREAD

**Issue by BigFartTheory** [gotk3/gotk3#327]
drag**DEST**set is implemened and workable
https://github.com/gotk3/gotk3/issues/326

**Comment by Bios-Marcel** [comment]
Did you check the code?

**Comment by BigFartTheory** [comment]
Yes. I use "DragDestSet", but I can't find DragSourceSet anywhere

**Comment by Bios-Marcel** [comment]
Maybe it's stil missing or accidently got removed. It might be easy to implement though.

**Comment by BigFartTheory** [comment]
Maybe It's easy to implement, but...
I don't know "c-language" and "English" good enough

It's implemented for gtk2:
https://github.com/mattn/go-gtk/blob/master/gtk/gtk.go

**Comment by Bios-Marcel** [comment]
You don't need to write c much. And english shouldn't be much of a problem either ^^

**Comment by BigFartTheory** [comment]
ok... 
I solved particually

I added to file _github.com/gotk3/gotk3/gtk/widget.go_ this code:
func (v *Widget) DragSourceSet(start_button_mask gdk.ModifierType, targets []TargetEntry, actions gdk.DragAction) {
	C.gtk_drag_source_set(v.native(), C.GdkModifierType(start_button_mask), (*C.GtkTargetEntry)(&targets[0]), C.gint(len(targets)), C.GdkDragAction(actions))
}

**Runing  it in my app:**
t_uri, _ := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
evBox.DragSourceSet(gdk.GDK_BUTTON1_MASK, []gtk.TargetEntry{*t_uri}, gdk.ACTION_COPY)
evBox.Connect("drag-begin", func(g *gtk.EventBox) {
	fmt.Println("drag-begin")
})
evBox.Connect("drag-data-get", func(g *gtk.EventBox) {
	fmt.Println("drag-data-get")
})

**Comment by BigFartTheory** [comment]
ok... 
**I kept trying to solve dragging.
Now I also added** to _github.com/gotk3/gotk3/gtk/gtk.go_ this:
func SetData(pointer uintptr, atom gdk.Atom, data []byte) {
	c := (*C.GValue)(unsafe.Pointer(pointer))
	p := (*C.GtkSelectionData)(unsafe.Pointer(c))
	C.gtk_selection_data_set(p, C.GdkAtom(unsafe.Pointer(atom)), C.gint(8), (*C.guchar)(unsafe.Pointer(&data[0])), C.gint(len(data)))
}

**my workable usage for dragging file to another application ("nemo" file manager):**
evBox.Connect("drag-data-get", func(g *gtk.EventBox, ctx *gdk.DragContext, data_pointer uintptr, _ uint, _ uint) {
	fmt.Println("drag-data-get")
	cmd := "file://" + "/mnt/dm-1/testfile.txt" + "\n"
	gtk.SetData(data_pointer, gdk.SELECTION_TYPE_STRING, []byte(cmd))
})

now I want to set icon at mouse pointer when dragging...

**Comment by Bios-Marcel** [comment]
Well, I can't tell you much about this, I have never used the drag and drop stuff. But if you get it working, feel free to create a PR ;)

**Comment by BigFartTheory** [comment]
**finally**
I added again to /home/nike/go/src/github.com/gotk3/gotk3/gtk/gtk.go this:
func DragSetIconPixbuf(context *gdk.DragContext, pixbuf *gdk.Pixbuf, hot_x int, hot_y int) {
	ctx := unsafe.Pointer(context.Native())
	pix := unsafe.Pointer(pixbuf.Native())
	C.gtk_drag_set_icon_pixbuf((*C.GdkDragContext)(ctx), (*C.GdkPixbuf)(pix), C.gint(hot_x), C.gint(hot_y))
}

**usage**:
evBox.Connect("drag-begin", func(g *gtk.EventBox, ctx *gdk.DragContext) {
	fmt.Println("drag-begin")
	pixbuf := GetIcon_PixBif_OF(64, PREFIX_DRAWONME+FILE_TYPE_UNKNOWN)
	gtk.DragSetIconPixbuf(ctx, pixbuf, 0, 0)
})

https://github.com/gotk3/gotk3/issues/327#issuecomment-464139818 Now it's **ready for Pull Request**

**Comment by SilentGopherLnx** [comment]
Looks good. Will it be commited?

**Comment by Bios-Marcel** [comment]
Well, I asked him to put this into one pull request, but he ignored me so far. Guess I'll just test it manually and merge it over the next days. Would have been great if it was a single complete PullRequest with a complete and working example ^^

**Comment by BigFartTheory** [comment]
all commited. Thank you!
