### ISSUE TITLE
Implement equal operator for widgets

### ISSUE THREAD

**Issue by csoriano1618** [gotk3/gotk3#330]
I think it's relatd to https://github.com/gotk3/gotk3/issues/306.

In general terms signals of widgets return which widget the action was performed on. However, that widget is a new wrapper over the internal GObject, so given a list (e.g. with GetChildren) it's impossible to match if the actioned widget is equal to any of those.

The workaround is to access the internal GObject and compare that, for example:
```
button.Connect("clicked", func() {
	for l := container.GetChildren(); l != nil; l = l.Next() {
		if l.Data().(*gtk.Widget).GObject == myWidget.GObject {
			fmt.Println("found")
			break
		}
	}
})
```
This is specially needed since GetChildren and such returns pure Widgets, and not its actual original object ([issue 1](https://github.com/gotk3/gotk3/issues/272), [issue 2](https://github.com/gotk3/gotk3/issues/321)).

I think a good idea would be if the equal operator would perform the comparison on the GOBject directly. It would be interesting to see what other bindings do.

**Comment by Bios-Marcel** [comment]
Uhm, I am a bit confused here. As far as I know, we can't change the behaviour of the equal operator, can we?

**Comment by csoriano1618** [comment]
:sweat_smile: me newbie with Go...

**Comment by csoriano1618** [comment]
One option would be to have an Equal method tho, does that makes more sense?

**Comment by Bios-Marcel** [comment]
Theoretically you could add a method to `Widget` ... but I don't really think it's necessary. Feel free to make a PR and let the others decide ^^

Or wait for someone else than me to answer.

**Comment by csoriano1618** [comment]
Alright. I will check what other bindings do, and if there is some agreement I can do a PR for that. iirc rust bindings had problems with this in the past too. Python and JS use inheritance, so it just works there.
