### ISSUE TITLE
ImageMenuItem

### ISSUE THREAD

**Issue by SilentGopherLnx** [gotk3/gotk3#342]
I wan use it, but it is deprecated:
"ImageMenuItem has been deprecated since GTK+ 3.10. If you want to display an icon in a menu item, you should use MenuItem and pack a Box with a Image and a Label instead. "

I can find icons on menus in all Cinnamon applications. So it's depracated. But it's works.
I tried to add box, but icon is aligned after blank space

	lbl, _ := gtk.LabelNew("Delete")
	icon, _ := gtk.ImageNew()
	icon.SetSizeRequest(16, 16)
	icon.SetFromIconName("edit-delete", gtk.ICON_SIZE_MENU)
	box, _ := gtk.BoxNew(gtk.ORIENTATION_HORIZONTAL, 0)
	box.Add(icon)
	box.Add(lbl)
	item, _ := gtk.MenuItemNew()
	item.Add(box)
return item

**Comment by Bios-Marcel** [comment]
Mind giving us a [MVCE](https://stackoverflow.com/help/mcve). Then we can just paste the complete thing and compile it ;)

**Comment by SilentGopherLnx** [comment]
my colution:		

img := image.Image ....
		if !InterfaceNil(img) {
			w := img.Bounds().Max.X
			h := img.Bounds().Max.Y
MAX_A := 65535/255
			item.Connect("draw", func(g *gtk.MenuItem, ctx *cairo.Context) {
				dx := 5
				dy := (g.GetAllocatedHeight() - h) / 2
				for y := 0; y < h; y++ {
					for x := 0; x < w; x++ {
						r, g, b, a := img.At(x, y).RGBA()
						ctx.SetSourceRGBA(float64(r/MAX_A)/255.0, float64(g/MAX_A)/255.0, float64(b/MAX_A)/255.0, float64(a/MAX_A)/255.0)
						ctx.Rectangle(float64(x+dx), float64(y+dy), float64(1), float64(1))
						ctx.Fill()
					}
				}
			})
		}
