### ISSUE TITLE
Thread-safe mutex locks for Show*

### ISSUE THREAD

**Issue by diamondburned** [gotk3/gotk3#348]
Was doing stuff, this happened: https://p.albru.me/p/NJ7B

Reckon it's due to the `ShowAll` call at L99 of the paste. Maybe wrapping Mutex around it will fix it?

**Comment by founderio** [comment]
That URL does not load for me. Any chance you could paste as a code block or github gist?

**Comment by diamondburned** [comment]
Closing this issue since it's likely a thread issue. Gtk3 is thread unsafe, so that's on me.
