### ISSUE TITLE
Windows 10 64-bit - can't create $WORK\b001\\_cgo_.o: No such file or directory

### ISSUE THREAD

**Issue by Bresenham** [gotk3/gotk3#353]
I installed the required packages and fixed the bug with `sed` command as described here (https://github.com/gotk3/gotk3/wiki/Installing-on-Windows) using msys2.

Unfortunately, after executing `go get github.com/gotk3/gotk3/gtk`  I get this error message:

```
PS C:\Users\Test\...> go get github.com/gotk3/gotk3/gtk
# github.com/gotk3/gotk3/gtk
Assembler messages:
Fatal error: can't create $WORK\b001\\_cgo_.o: No such file or Directory
```

Any help is greatly appreciated.

**Comment by drakbar** [comment]
@Bresenham try cloning the repo into your workspace, assuming that you have a normal %GOPATH% (i.e. C:\Users\username\go). 

Just navigate to go/src/github.com/gotk3 (you might have to make the folders `github.com` and `gotk3`) and do a `git clone https://github.com/gotk3/gotk3.git`.  

You should end up with a file structure that looks like this:

```
go/src/github.com
  └───gotk3
       └───gotk3
           ├───cairo
           ├───gdk
           ├───glib
           ├───gtk
           └───pango
```
    
hope this helps.

**Comment by Bios-Marcel** [comment]
Is this issue still relevant? E.g. is it solved or not?

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
