### ISSUE TITLE
TextBuffer.SelectRange() not available

### ISSUE THREAD

**Issue by rasteric** [gotk3/gotk3#354]
How do I select text in a TextView? The following snippet for selecting all does not work:

```
func SelectAll(t *gtk.TextView) {
	if t == nil {
		return
	}
	buff, err := t.GetBuffer()
	if err != nil {
		return
	}
	var start = buff.GetIterAtOffset(0)
	var end = buff.GetIterAtOffset(0)
	end.ForwardToEnd()
	buff.SelectRange(start, end)
}
```

I'm new to GTK3 so maybe I'm missing something obvious. If not, please add the wrapper!

**Comment by Bios-Marcel** [comment]
Yes, that function simply wasn't implemented yet. I have added it with commit 770c4e769764890fa0d8a91d6690f9745a757d25.
Check the code, it's rather simple, if you encounter a missing wrapper again, I encourage you to try and add it yourself, we will gladly accept your Pull Requests :)
