### ISSUE TITLE
"activate" signal on gtk.Entry uses *glib.Object as handler arg type, not *gtk.Entry

### ISSUE THREAD

**Issue by patknight** [gotk3/gotk3#361]
When I connect the "activate" signal to a gtk.Entry, the handler is passed a *glib.Object. I expected a *gtk.Entry. When I connect signals to buttons or other widget types, the type of the first argument to the signal handler is usually a pointer to the type of widget I connected. E.g. if I connect a gtk.Button, the signal handler gets a *gtk.Button pointer to the button instance. If I connect gtk.IconView, the signal handler gets a *gtk.IconView.

I connected a signal handler to the "activate" signal of a gtk.Entry. When I hit enter in the entry, my application panics with
`panic: reflect.Value.Convert: value of type *glib.Object cannot be converted to type *gtk.Entry`

I added code to my handler to make an Entry out of the Object as a workaround:
```go
func (d *multipickDialog) newTag(obj *glib.Object) {
	e := &gtk.Editable{Object: obj}
	w := &gtk.Entry{Widget: gtk.Widget{InitiallyUnowned: glib.InitiallyUnowned{Object: obj}}, Editable: *e}
	name, err := w.GetText()
```
and the application works, indicating that the object pointer passed in does refer to the correct Entry widget.

I've poked around the gotk3 sources but can't see any magic that happens for Buttons etc. that doesn't happen for Entry, so this is beyond me. I've tried debugging and stepping through Connect and through the callback, but am no clearer.

Any suggestions? If someone knows how to fix this, I'm happy to implement and test.

go version go1.12.2 linux/amd64
gotk3 - head revision as of today

**Comment by patknight** [comment]
I've been doing some more debugging, looking at the g_type value of the object passed in to `g_signal_connect_closure` and the g_type passed back to `glib.goMarshal` when the signal is emitted. For both gtk.Entry and gtk.Button, the appropriate value is passed in to the underlying GTK3 code. When it comes back to goMarshal, the button is still has a button g_type value, but the the entry has a GObject g_type.

Unless someone has a bright idea what's going on, I'm going to code up a test application in C ( :-( ) to see if that has the same issue. If so, the bug is in glib, not gotk3.

**Comment by patknight** [comment]
I've coded the C application. Its GtkEntry "activate" handler is correctly given a *GtkEntry argument, not a *GtkObject. After rebuilding the Gtk and Glib libraries (C versions, not the gotk3 wrappers) from source, I was able to debug using gdb.

I've found out what's going on! This description applies to the C application, until I say we're back to discussing go.

Right down the entire callstack from the emission of the 'activate' signal until the last marshaler (`g_cclosure_marshal_VOID__VOID` in gsignal.c in the glib library), the entry object is encapsulated in a pointer inside a GtkObject. That last marshaler calls `g_value_peek_pointer` (a library internal function, so gotk3 can't use it) to get the GtkEntry* out of the GtkObject.

OK - back to gotk3. Since gotk3 supplies its own marshaler to handle the type conversions from C to go, it never gets the benefit of the call to `g_value_peek_pointer` to extract the GtkEntry*. This isn't a bug in gotk3 - from my reading of the GTK documentation and sources, this is one of the intended uses of marshalers.

It'll take further digging (this weekend I hope) to see if it's safe for `glib.goMarshal` to always peek into a GtkObject and extract a pointer. For the code path I've looked at for the activate signal on GtkEntry, the C gtk library tells the signal system to use the peeking marshaler when no marshaler is supplied. 

There are two reasons we can't take advantage of this goMarshal:
1) we don't know the signal name
2) we shouldn't duplicate the internal knowledge from C gtk about how to marshal specific signals if we did know the signal name.

I need to think about this.

**Comment by patknight** [comment]
I've submitted a fix as pull request #366

**Comment by patknight** [comment]
Hi - the fix for this has been merged to master. Should the issue still be open?

**Comment by Bios-Marcel** [comment]
Nope, thanks.
