### ISSUE TITLE
How to get path from cellrenderertoggle signal handling ?

### ISSUE THREAD

**Issue by fatumx5** [gotk3/gotk3#362]

**Comment by Bios-Marcel** [comment]
I am suggesting that you give some more information about the thing you are asking about. I suspect you are talking about the `toggle` signal in https://developer.gnome.org/gtk3/stable/GtkCellRendererToggle.html?

The documentation states that the path is passed as a string with the function parameters.

It'd be nice if you could include an example showing what you have already tried and which problems you encountered.

**Comment by fatumx5** [comment]
I did not understand at first that I could pass a pointer to the callback function, sorry. 

If somebody have similar question, that looks like this, for example:
func OnToggledCallbac(toggle *gtk.CellRendererToggle, path string) {
	//some actions you need
} 

checkRenderer.Connect("toggled", OnToggledCallbac)
