### ISSUE TITLE
change win Decoration kill opacity

### ISSUE THREAD

**Issue by nodrygo** [gotk3/gotk3#363]
Hello    
first of all thanks for this very good Gtk/Go binding   

In order to learn  both Go and  gotk3 I have wrote a [naive clock demo](https://github.com/nodrygo/GoClock)   

with popup menu I can switch on/off decoration but doing that I lost window opacity
may be I do something wrong ?
if you have some idea,  thanks for your help

**Comment by Bios-Marcel** [comment]
Whenever you report such behavioral problems, it'd be nice if you could include a minimal example that shows the behavior that you deem to be incorrect. It should do nothing less and nothing more.

**Comment by nodrygo** [comment]
ha ok sorry for the inconvenience    
a test code did not seem trivial at first and I thought the demo link code was small enough    
I will try to do better next time ;-)    
thank you for ignoring this request which, in fact,  is not very important  and may be a problem coming Gtk 

Whichever it is, GoTK3 is a great job, thanks for that
cordially

**Comment by Bios-Marcel** [comment]
I personally prefer having a small snippet of code that exactly reproduces the problem and does nothing less and nothing more. Sometimes it doesn't even reproduce the problem, indicating that the problem lies somewhere else in your codebase. So I think writing a minimal example is always the best way to go about this, for you and the people that want to help you.

**Comment by nodrygo** [comment]
Hello
the smallest I can think of (a key press changes the state)
but not sure you have to spend time on that because it's probably a GTK bug
(tested a lot of case without success,  platform Linux Mint 19) 

anyway gotk3 is a great job, thanks for that

[test.go.zip](https://github.com/gotk3/gotk3/files/3115781/test.go.zip)

**Comment by Bios-Marcel** [comment]
I have to bicker one last time.  If you have a single file with example source code, then you can just post it like this:

\`\`\`go
func main() {
...
}
\`\`\`

then nobody has to download a zip file ;)

Anyway it's fine for now, I'll test it later, thanks.

**Comment by nodrygo** [comment]
OK I'll do  ;-)
thank's


Le jeu. 25 avr. 2019 à 12:02, Marcel Schramm <notifications@github.com> a
écrit :

**Comment by Bios-Marcel** [comment]
So, for me this acts completely different. The opacity stays as specified, however, the toggling of the decoration doesn't work at all. After the decoration has been disabled once, it doesn't turn on again.

**Comment by nodrygo** [comment]
after lot of search seem there is different Gkt behaviour according the
platforms
so please do not invest time in such a thing, it is not worth it
thanks again
I have enjoyed to play with gotk3
in some future  I will test on Windows


Le jeu. 25 avr. 2019 à 19:30, Marcel Schramm <notifications@github.com> a
écrit :

**Comment by Bios-Marcel** [comment]
Hm, okay. If you think this is not worth investigating any further, just close the issue.

**Comment by nodrygo** [comment]
ok
in fact I have same or even more problems with same clock
<https://github.com/nodrygo/GoClock> test I have done with Racket and Julia
+ Gtk
but this was just to compare the different environment ;-)
as a language I prefer Julia than Go
as a deployment Racket is the most easy of different platform
for Gtk Binding and for compilation bin size Go is the best :-)

Le jeu. 25 avr. 2019 à 19:57, Marcel Schramm <notifications@github.com> a
écrit :
