### ISSUE TITLE
Can't build on Linux with GTK 3.18

### ISSUE THREAD

**Issue by yukiraven** [gotk3/gotk3#364]
I have Gtk 3.18.9 installed on my box, and when I go to install Gotk3, I get these errors:

```
src/github.com/gotk3/gotk3/gdk/gdk_since_3_16.go:153:16: could not determine kind of name for C.gdk_gl_context_get_use_es
src/github.com/gotk3/gotk3/gdk/gdk_since_3_16.go:180:16: could not determine kind of name for C.gdk_gl_context_is_legacy
src/github.com/gotk3/gotk3/gdk/gdk_since_3_16.go:158:2: could not determine kind of name for C.gdk_gl_context_set_use_es
```

Things were working fine until the GL stuff was added.  But I also need the GL stuff, so I don't exactly want to revert back to an older revision.

I installed it using `go get -u -v -tags gtk_3_18 github.com/gotk3/gotk3/gtk` like I did before.

My Go installation is 1.12.4, but I also tested it with 1.12 and 1.11.4 with the same results.

**Comment by Bios-Marcel** [comment]
Maybe we have done some mistake with the gtk version constraints. I'll take a look at this.

What version of gtk do you have installed?

**Comment by yukiraven** [comment]
It's Gtk v3.18.9

Thanks!

**Comment by Bios-Marcel** [comment]
Should be working now. Just reopen the issue if it doesn't :)

**Comment by yukiraven** [comment]
Almost!  GDK now builds, but it looks like GTK itself now has a similar issue.

```
[alexa@emiko ~]$ go get -u -v -tags gtk_3_18 github.com/gotk3/gotk3/gtk
github.com/gotk3/gotk3 (download)
github.com/gotk3/gotk3/gdk
github.com/gotk3/gotk3/gtk
# github.com/gotk3/gotk3/gtk
mysrc/go/src/github.com/gotk3/gotk3/gtk/glarea.go:92:16: could not determine kind of name for C.gtk_gl_area_get_use_es
mysrc/go/src/github.com/gotk3/gotk3/gtk/glarea.go:97:2: could not determine kind of name for C.gtk_gl_area_set_use_es
```

Thanks for your help with this, I appreciate it!

**Comment by Bios-Marcel** [comment]
Oof, I am dumb. Forgive me. Its midnight,  I'll fix this tomorrow, unless you wanna do it yourself. You'd just have to move the functions into files with gtk3.20+ buildconstraints.

**Comment by Bios-Marcel** [comment]
K, now it works. For real this time ^^

**Comment by peterpalau** [comment]
Is this issue fixed? Because I'm having the same problem when i try to build this library in Ubuntu 16.04

```
gdk_since_3_20.go:15:16 could not determine kind of name for C.gdk_gl_context_is_legacy
```

**Comment by 414n** [comment]
I got the same issue using GTK3-3.18.9 on Slackware64 14.2 while using the https://github.com/sqweek/dialog library that downloads gotk3 v0.4.0.
The solution is to explicitly state during the `go build` phase the specific GTK3 version in use via a build tag, e.g:
`go build -tags gtk_3_18`
This should avoid taking into account the `gdk_since_3_20.go` file altogether.
