### ISSUE TITLE
Windows 10 compiler error

### ISSUE THREAD

**Issue by drakbar** [gotk3/gotk3#365]
@Bios-Marcel 
I have run into a weird quirk with trying to create a custom app. When I try something very simple such as (on Windows 10):
```go
package main

// #cgo pkg-config: gtk+-3.0
import "C"

func main() {
}
```
The compiler throws a complaint like so `invalid flag in pkg-config --libs: -Wl,-luuid`.
This is odd considering `gtk.go` starts out like this:

```go
package gtk

// #cgo pkg-config: gdk-3.0 gio-2.0 glib-2.0 gobject-2.0 gtk+-3.0
```
 I don't seem to run into this issue on linux however. Do you know how gotk3 manages to get around this?

I am now starting to get this from the `HEAD`. 
```
go version
go version go1.11.2 windows/amd64
```

**Comment by Bios-Marcel** [comment]
Check the wiki, there is a workaround for this.

**Comment by drakbar** [comment]
Thanks @Bios-Marcel. 

I know that I have done that step in the past, I am not sure how that .pc file got changed. Gonna close this issue.

**Comment by Bios-Marcel** [comment]
maybe its time to get that shit fixed, its a suprise noone fixed this yet ^^
