### ISSUE TITLE
Writing GUI Tests

### ISSUE THREAD

**Issue by Bresenham** [gotk3/gotk3#367]
Hey everyone,

I would like to test my GUI application. Therefore I would like to create my own `gdk.Event` structs (as if a `key-press-event` would happen for example) - how do I do that? I didn't find any structs for events in your code.

Thanks in Advance.

**Comment by Bios-Marcel** [comment]
Hey, while we have structures for events, those are meant to be read only and don't expose the underlying properties. You could however use something like https://github.com/go-vgo/robotgo in order to actually simulate a user. Sorry for the late answer.
