### ISSUE TITLE
Can't get RadioButton work ok, it always hangs my program.

### ISSUE THREAD

**Issue by errz99** [gotk3/gotk3#37]
This code works ok with conformal/gtk but hangs with gotk3/gtk
In both cases compilation occurs fine.
Tested in OS X and Archlinux

    package main

    import (
	    "github.com/gotk3/gotk3/glib"
	    "github.com/gotk3/gotk3/gtk"
	    //"github.com/conformal/gotk3/glib"
	    //"github.com/conformal/gotk3/gtk"	
    )

    func main() {
	
	    gtk.Init(nil)
	    win := window()
	    win.ShowAll()
	    gtk.Main()

    }
    
    func window() *gtk.Window {		
	    win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	    win.SetBorderWidth(8)
	    win.SetSizeRequest(240, 80)
	    win.SetPosition(gtk.WIN_POS_CENTER)
	    win.SetTitle("Radio Buttons")
	    win.Connect("destroy", func() {
		    gtk.MainQuit()
	    })
    
	    var buttonL *glib.SList	
	    button1, _ := gtk.RadioButtonNewWithLabel(buttonL, "First Button")
	    button2, _ := gtk.RadioButtonNewWithLabelFromWidget(button1, "Second Button")
	
	    vbox, _ := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	    vbox.Add(button1)
	    vbox.Add(button2)
	
	    win.Add(vbox)
	    return win	
	
    }

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40c1301]

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.RadioButtonNewWithLabel(0x0, 0x442c750, 0xc, 0x0, 0x0, 0x0)
	/Users/bdaemon/code/go/src/github.com/gotk3/gotk3/gtk/gtk.go:6576 +0x31
main.window(0x0)
	/Users/bdaemon/code/go/src/_gtk_radiobutton_bis/main.go:32 +0x137
main.main()
	/Users/bdaemon/code/go/src/_gtk_radiobutton_bis/main.go:14 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

**Comment by sshikaree** [comment]
After `var buttonL *glib.SList` pointer is nil. Add `buttonL = new(glib.Slist)` . 
Or for empty struct you can use
```go
buttonL := &glib.Slist{}
```

**Comment by errz99** [comment]
hehe, it was me...

    buttonL := &glib.SList{}

Works fine. Problem solved.

Thanks sshikaree
