### ISSUE TITLE
some additional required

### ISSUE THREAD

**Issue by dudochkin-victor** [gotk3/gotk3#375]
GDK_TYPE_PIXBUF is required urgently. but there are no easy way. so i just initialized it in a runtime(unsafe i know)
gtk_tree_view_column_set_alignment () & gtk_tree_view_column_get_alignment () its easy to add.

**Comment by dudochkin-victor** [comment]
// SetAlignment is a wrapper around gtk_tree_view_column_set_alignment ()
func (v *CellRenderer) SetAlignment(xalign float64, yalign float64) {
	C.gtk_cell_renderer_set_alignment(v.native(), C.gfloat(xalign), C.gfloat(yalign))
}

// SetAlignment is a wrapper around gtk_tree_view_column_set_alignment ()
func (v *TreeViewColumn) SetAlignment(xalign float64) {
	C.gtk_tree_view_column_set_alignment(v.native(), C.gfloat(xalign))
}

**Comment by Bios-Marcel** [comment]
Hey there, sorry for the late answer. If you want this code to be added upstream, you should create a pull request instead of an issue.

**Comment by founderio** [comment]
Regarding GDK_TYPE_PIXBUF:
As far as I have seen, this is not present in gtk 3.
You can use `gdk.PixbufGetType()` to get the type
