### ISSUE TITLE
Rendering a ProgressBar in a TreeView

### ISSUE THREAD

**Issue by Diceshake** [gotk3/gotk3#380]
I was expecting to create a CellRendererProgress to assign to a TreeViewColumn to create a progress bar, but there doesn't seem to be a CellRendererProgress binding.

https://developer.gnome.org/gtk3/stable/GtkCellRendererProgress.html

Is there another way to render a ProgressBar?

**Comment by Bios-Marcel** [comment]
The best way would be to just create the binding. It's probably relatively easy and I doubt you are the first one who needs this.

**Comment by Diceshake** [comment]
I'll give it a shot, thanks!

**Comment by Bios-Marcel** [comment]
Just take a look at how the other GtkCellRenderer... bindings were been implemented.

**Comment by Diceshake** [comment]
Added the bindings and it worked like a charm.
Here's the repo I forked and added onto if interested in merging.

https://github.com/Diceshake/gotk3

**Comment by Bios-Marcel** [comment]
Sure, feel free to make a pull request.

**Comment by Bios-Marcel** [comment]
Implemented with #381
