### ISSUE TITLE
Embed resource

### ISSUE THREAD

**Issue by johnlarfour** [gotk3/gotk3#382]
How embed the glade file and relative icon in the binary?
Because if I build and run outside the directory where glade file and icon is, I get the error
`Gtk-ERROR **: failed to add UI: The resource at 'ui/example.glade' does not exist`

**Comment by Bios-Marcel** [comment]
Sorry, but you gotta give us some more information here. What is your directory structure? What is your working directory and what is the command that you ran? If you use relative paths, the file you are referencing needs to be at the given path relative to your working directory.

**Comment by johnlarfour** [comment]
@Bios-Marcel I download this example https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/glade and add an icon to the window with glade designer.
So the directory structure is:
```
├── glade.go
└── ui
    ├── icon.png
    └── ui.glade
```
The command that I run:
```
cd glade
go build glade.go
```
If i run the program inside the glade directory is load the ui and the icon but if i move the binary for example in /usr/bin will give me the error.
It's possible to embed the glade file with the icon in the binary?

**Comment by Bios-Marcel** [comment]
There are some open source third party packaging tools, just check the net. I can't recommend any, since I haven't done this myself.

**Comment by hfmrow** [comment]
Hi, 'm using this to embedding all my data: [github.com/jteeuwen/go-bindata](url)

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
