### ISSUE TITLE
gtk.Main() loop locked at 60 Hz

### ISSUE THREAD

**Issue by gregjohnson2017** [gotk3/gotk3#383]
I am writing an application that uses OpenGL for graphics, and have recently tried making a switch from SDL to GTK for window management, so I can later take advantage of the widgets that GTK offers (like menu bars and certain dialogs). However, it would seem that GTK's internal signal-handling main loop is limited to a refresh rate of 60 Hz. After looking through a bunch of GTK docs, I can't seem to find a way to change/remove this apparent refresh cap built in to the gtk.Main() loop. Does anyone know if there is a way around this, or if this is an inherent limitation of GTK?

**Comment by Bios-Marcel** [comment]
You might want to try your luck asking in the GTK irc.

**Comment by founderio** [comment]
Any findings here?
An idea that came to mind:

Instead of using `gtk.Main()`, manually run `gtk.MainIteration()` in a loop and see if that gets around the limit?

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
