### ISSUE TITLE
CellRendererToggle not working?

### ISSUE THREAD

**Issue by Diceshake** [gotk3/gotk3#385]
I'm not able to render a toggle button in a cell - below is a sample of code I would expect to work. The text renders fine, but the toggle column appears empty. Perhaps I'm doing something wrong?

I am also building with gtk_3_20

```
package main

import (
	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	gtk.Init(nil)
	win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)

	treeStore, _ := gtk.TreeStoreNew(glib.TYPE_STRING, glib.TYPE_BOOLEAN) 
	treeView, _ := gtk.TreeViewNewWithModel(treeStore)

	rendererText, _ := gtk.CellRendererTextNew()
	rendererToggle, _ := gtk.CellRendererToggleNew()

	column1, _ := gtk.TreeViewColumnNewWithAttribute("column 1", rendererText, "text", 0)
	toggleColumn, _ := gtk.TreeViewColumnNewWithAttribute("toggle", rendererToggle, "active", 1)

	var iter *gtk.TreeIter = nil
	iter = treeStore.Append(iter)

	treeStore.SetValue(iter, 0, "hello")
	treeStore.SetValue(iter, 1, true)

	iter = treeStore.Append(iter)
	treeStore.SetValue(iter, 0, "world")
	treeStore.SetValue(iter, 1, false)

	treeView.AppendColumn(column1)
	treeView.AppendColumn(toggleColumn)

	win.Add(&treeView.Widget)
	win.ShowAll()
	gtk.Main()
}
```

**Comment by Bios-Marcel** [comment]
It works fine for me, I don't know what you are expecting and what it looks like for you. Can you share a screenshot?

)
![bug](https://user-images.githubusercontent.com/19377618/61249334-4c8eda80-a755-11e9-8a75-4936f6fb5031.png)

**Comment by Diceshake** [comment]
![checkbox](https://user-images.githubusercontent.com/30868662/61249493-fbfa8b80-a71a-11e9-82ed-2be481109373.png)

Interesting, this is what I see. I did connect the "toggled" signal to the column and it was emitting it when I clicked in the column. I guess my machine is having trouble displaying it?

**Comment by Bios-Marcel** [comment]
Well, I was using exactly the code that you've sent me. Maybe you have a faulty GTK theme?

**Comment by Diceshake** [comment]
I have the default theme, so I don't think it's that.

I tried a different computer and everything worked fine, so I think I'll close this and comment back if I ever figure out what went wrong, thanks!
