### ISSUE TITLE
X Window System Error

### ISSUE THREAD

**Issue by Diceshake** [gotk3/gotk3#386]
I've been getting some weird crashes in my program and I think I tracked it down to PopupAtPointer() - I took the gotk3 treestore example and added a button press handler to the treeView and turned on gdk debugging with synchronous X calls to recreate my issue.

```package main

import (
	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
	"log"
)

const (
	COLUMN_VERSION = iota
	COLUMN_FEATURE
)

func createColumn(title string, id int) *gtk.TreeViewColumn {
	cellRenderer, _ := gtk.CellRendererTextNew()
	column, _ := gtk.TreeViewColumnNewWithAttribute(title, cellRenderer, "text", id)
	return column
}

func setupTreeView() (*gtk.TreeView, *gtk.ListStore) {
	treeView, _ := gtk.TreeViewNew()
	treeView.AppendColumn(createColumn("Version", COLUMN_VERSION))
	treeView.AppendColumn(createColumn("Feature", COLUMN_FEATURE))
	listStore, _ := gtk.ListStoreNew(glib.TYPE_STRING, glib.TYPE_STRING)
	treeView.SetModel(listStore)
	return treeView, listStore
}

func addRow(listStore *gtk.ListStore, version, feature string) {
	iter := listStore.Append()
	listStore.Set(iter,
		[]int{COLUMN_VERSION, COLUMN_FEATURE},
		[]interface{}{version, feature})
}

func setupWindow(title string) *gtk.Window {
	win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	win.SetDefaultSize(600, 300)
	return win
}

func main() {
	commandline := []string{"application", "--gdk-debug=all", "--sync"}
	gtk.Init(&commandline)

	win := setupWindow("Go Feature Timeline")

	treeView, listStore := setupTreeView()
	win.Add(treeView)

	addRow(listStore, "r57", "Gofix command added for rewriting code for new APIs")
	addRow(listStore, "r60", "URL parsing moved to new \"url\" package")
	addRow(listStore, "go1.0", "Rune type introduced as alias for int32")

	_, err := treeView.Connect("button_press_event", rightMouseClick)
	if err != nil {
		log.Println("error connection")
	}

	win.ShowAll()
	gtk.Main()
}

func rightMouseClick(_ *gtk.TreeView, event *gdk.Event) {
	eventButton := gdk.EventButtonNewFromEvent(event)
	if eventButton.Type() == gdk.EVENT_BUTTON_PRESS && eventButton.Button() == 3 {

		log.Println("click")
		menu, err := gtk.MenuNew()
		if err != nil {
			log.Println(err)
		}
		opt1, err := gtk.MenuItemNewWithLabel("option1")
		if err != nil {
			log.Println(err)
		}
		opt2, err := gtk.MenuItemNewWithLabel("option2")
		if err != nil {
			log.Println(err)
		}
		menu.Append(opt1)
		menu.Append(opt2)
		menu.ShowAll()
		menu.PopupAtPointer(event)
	}
}
```

I run this with gtk_3_20  and right clicking the treeview causes a crash.

>(application:30605): Gdk-ERROR **: The program 'application' received an X Window System error.
>This probably reflects a bug in the program.
>The error was 'BadMatch (invalid parameter attributes)'.
>  (Details: serial 728 error_code 8 request_code 73 (core protocol) minor_code 0)
>  (Note to programmers: normally, X errors are reported asynchronously;
>   that is, you will receive the error a while after causing it.
>   To debug your program, run it with the GDK_SYNCHRONIZE environment
>   variable to change this behavior. You can then get a meaningful
>   backtrace from your debugger if you break on the gdk_x_error() function.)
>SIGTRAP: trace trap
>PC=0x7fa7d1a729eb m=0 sigcode=128

It says "This probably reflects a bug in the program" which makes me think I'm doing something wrong. Maybe someone could point it out? 

Thank you

**Comment by Bios-Marcel** [comment]
Hey,

The problem lies there:

```go
commandline := []string{"application", "--gdk-debug=all", "--sync"}
```

it doesn't like one of your parameters. For me it works after removing the `--gdk-debug=all` parameter.

**Comment by andre-hub** [comment]
so i just tried this on a debian 10 with the included standard versions of the libs. there was no error, the events were all logged.
