### ISSUE TITLE
How to use glib.MenuModel?

### ISSUE THREAD

**Issue by rasteric** [gotk3/gotk3#387]
I'm making a menu for an application window and can't figure out how to use `glib.MenuModel` to add sections, either there is a missing binding or I'm not understanding GTK3, or both.

I create a menu with `glib.MenuNew()`. Then I need to add sections, but `menu.AppendSection` takes a string and a `MenuModel`, not a menu. I see no way of converting from `*glib.Menu` to `*glib.MenuModel`, and I see no way of creating a `MenuModel` directly. According to the docs it is an abstract class, but where is its implementation? 

Here is some example code from my application. The lines with `AppendSection` do not work, because section is a `*glib.Menu` instead of a `*glib.MenuModel`:

```
func NewMenu(model *Model, cmdNames string) *Menu {
	menu := Menu{}
	menu.m = glib.MenuNew()
	section := glib.MenuNew()
	sectionName := ""
	names := strings.Split(cmdNames, " ")
	for _, name := range names {
		if name == "" {
			continue
		}
		if name == "-" {
			// create a section
			menu.m.AppendSection(sectionName, section)
			section = glib.MenuNew()
			continue
		} else {
			cmd := FindCommand(model, name)
			if cmd.IsNull() {
				if !HasLoc(name) {
					log.Warnw(`key for menu is neither command nor valid translation`, "key", name)
					continue
				}
				sectionName = Tr(name)
			}
			// now we know it's a valid command
			section.Append(Tr(cmd.Title()), `win.`+cmd.CommandAction().GetName())
		}
	}
	menu.m.AppendSection(sectionName, section)
	return &menu
}

```

**Comment by Bios-Marcel** [comment]
So, `menu` and `model` are wrapper classes you made yourself?

Anyway, it looks like a mistake has been made implementing the Menu wrapper. It seems that a Menu is actually an extension of the MenuModel. See here under "Object Hierarchy": https://developer.gnome.org/gio/stable/GMenu.html#GMenu-struct

**Comment by Bios-Marcel** [comment]
So, just taking the pointer of the underlying MenuModel should work fine:

```go
menu := glib.MenuNew()
sectionA := glib.MenuNew()
sectionB := glib.MenuNew()
menu.AppendSection("A", &sectionA.MenuModel)
menu.AppendSection("A", &sectionB.MenuModel)
```

Anyway, maybe it might be better to make an interface for `MenuModel`, then this would be a bit easier, but it's not really necessary.

**Comment by rasteric** [comment]
Yes, sorry, it's not a minimal example. My app has its own wrappers for various things like db access, translation and undo/redo.

I hope you can fix this, because MenuModel seems to be used a lot.

**Comment by Bios-Marcel** [comment]
Well, like said, for now there is a solution. Just do that for now.

**Comment by Bios-Marcel** [comment]
Could you do me the favor and write a minimal working example with the workaround I provided? Would take some work of my shoulders, as I am currently also working on other stuff.

**Comment by rasteric** [comment]
I don't understand the workaround. This doesn't seem to work:

> ```go
> menu := glib.MenuNew()
> sectionA := glib.MenuNew()
> sectionB := glib.MenuNew()
> menu.AppendSection("A", &sectionA.MenuModel)
> menu.AppendSection("B", &sectionB.MenuModel)
> ```
> 
> Anyway, maybe it might be better to make an interface for `MenuModel`, then this would be a bit easier, but it's not really necessary.

**Comment by Bios-Marcel** [comment]
`Menu` contains a `MenuModel`, so just passing a reference to the underlying `MenuModel` should satisfy `section *MenuModel`. Or does this give a runtime error? I just checked whether it compiles. So, unless my VS Code lied to me, this should compile. Like I said, I am currently doing other things, which is also why I asked for a minimal example.
