### ISSUE TITLE
Missing gtk_text_buffer_get_selection_bounds (), gtk_text_buffer_insert_markup ()

### ISSUE THREAD

**Issue by hfmrow** [gotk3/gotk3#389]
Hi,
Missing gtk_text_buffer_get_selection_bounds () and
gtk_text_buffer_insert_markup ()
Could you ensure that these functions exist please ?
they seem not to be currently available.

i've tried to use Tags for pango markup but without selection iter (start, end) it's useless.

Thanks you for your work.

**Comment by hfmrow** [comment]
Forget it, i'll publish a request for update with this functions and some others.

**Comment by Bios-Marcel** [comment]
Yeah, you are right, those currently don't exist. Sorry for not replying earlier :)

Do you mean a you'll submit a pull-request when you said this?:
> i'll publish a request for update with this functions and some others

If so, we appreciate it :)

**Comment by hfmrow** [comment]
Hi, done.
Can't publish but i have put a file with adds.
[https://github.com/gotk3/gotk3/pull/391](https://github.com/gotk3/gotk3/pull/391)

**Comment by Bios-Marcel** [comment]
I don't know what you mean by publish
