### ISSUE TITLE
Building apps on Ubuntu 14.04

### ISSUE THREAD

**Issue by sshikaree** [gotk3/gotk3#39]
To build application on Ubuntu 14.04 you should use `gtk_3_10` tag:
`$ go build -tags gtk_3_10 example.go`.

Maybe add this info to README?

**Comment by andre-hub** [comment]
i have add this information:

see: https://github.com/gotk3/gotk3/commit/c27ddeb1bf2079fbaedc1d1be0f976882ff5c141

**Comment by sshikaree** [comment]
Good)
