### ISSUE TITLE
Is there an interest in implementing gstreamer?

### ISSUE THREAD

**Issue by claucece** [gotk3/gotk3#390]
Hey!

Very amazing library!

Some people, like @MovingtoMars started to implement gstreamer in a fork of this library (https://github.com/MovingtoMars/gotk3/tree/master/gst).. will there be an interest of continue the work and having it here?

**Comment by Bios-Marcel** [comment]
In general any PR is welcome, so if @MovingToMars finishes this, we'd be glad if he'd add a PR for it. If he doesn't do it himself, we could theoretically also do it manually.

**Comment by Bios-Marcel** [comment]
Uh, I am sorry, I missunderstood this as `he just started doing this`. I just looked at the code you linked and the last edit was 5 years ago. So, there is still a lot of things to implement and most of the repository members aren't very active right now. Most additions are coming in via PRs at the moment. I usually just do tiny stuff, as I currently dropped the applications that I was writing in gotk3, so my interest in personally doing this is kinda low. However, if you really need gstreamer, you could also attempt implementing this yourself.

**Comment by andre-hub** [comment]
hi @claucece,
hi @Bios-Marcel 

i removed the gsteamer files from normal branch. we have not the power for all stuff.
But i created a subproject based on this lib under my namespace:
https://github.com/andre-hub/go-gstreamer

**Comment by claucece** [comment]
Oh, I see @andre-hub ... and if we need to expand or implement something else from gstreamer, we do it there? https://github.com/andre-hub/go-gstreamer I have a team which will be very interested in doing so and helping ;)

Thanks so much for your replies @Bios-Marcel !
