### ISSUE TITLE
windows amd64 cairo error (maybe) 

### ISSUE THREAD

**Issue by Raklit** [gotk3/gotk3#395]
Hello my arch is linux-amd64.
If I write this command in my terminal:

> env GOOS=windows GOARCH=amd64  go get github.com/gotk3/gotk3/cairo

Then I get answer:

> github.com/gotk3/gotk3/cairo
 ../../../go/src/github.com/gotk3/gotk3/cairo/errors.go:3:18: undefined: Status

**Comment by Bios-Marcel** [comment]
I don't think you can just crosscompile like that. Have you tried what the wiki says? https://github.com/gotk3/gotk3/wiki/Cross-Compiling

I am not sure how up-to-date this is, as I have never made use of it myself.

**Comment by Raklit** [comment]
When I try to follow the instructions step by step, I get a lot of errors (some problems with installing mingw headers).
But this article solved my problem:
> onedev.net "Кросс-компиляция GUI программы на Go + GTK3 (mingw64 + golang + gotk3)"

I do not want to insert a link to this page, but just leave the article title.
