### ISSUE TITLE
How to search for specific bindings?

### ISSUE THREAD

**Issue by lechovskyv** [gotk3/gotk3#403]
### Background
I was searching for bindings using the find functionality in my browser and searching through these pages by typing the function I wanted a binding for:

- https://godoc.org/github.com/gotk3/gotk3/cairo
- https://godoc.org/github.com/gotk3/gotk3/glib
- https://godoc.org/github.com/gotk3/gotk3/gdk
- https://godoc.org/github.com/gotk3/gotk3/gtk

But I didn't find any binding for g_signal_connect function, so I guess I'm doing something wrong.

**Comment by Bios-Marcel** [comment]
Just try searching in your filesystem, using ripgrep / grep / your IDE or whatever tool you want to use.

**Comment by lechovskyv** [comment]
Thanks. I didn't find the binding though. I found a mention of g_signal_connect only in gtk/gtk.go.h, where I didn't find the binding. Grep's output also contained glib/connect.go, but there was only a binding to g_signal_connect_closure.

**Comment by Bios-Marcel** [comment]
I think it's just called `Connect` and all widgets have it.

**Comment by lechovskyv** [comment]
@Bios-Marcel Thanks, this helped. When I search for a binding next time, I'll try to understand what a function does and then search for it.
