### ISSUE TITLE
Please merge the pull requests!

### ISSUE THREAD

**Issue by rasteric** [gotk3/gotk3#424]
There are currently 21 pull requests that pass checks, provided by various contributors, and I need the functionality of some of them (TextBuffer additions) in my project. **_Please_ be so kind and review them, merge them into the repo, or close them for a reason.**

Incomplete list:
https://github.com/gotk3/gotk3/pull/431
https://github.com/gotk3/gotk3/pull/430
https://github.com/gotk3/gotk3/pull/429
https://github.com/gotk3/gotk3/pull/428
https://github.com/gotk3/gotk3/pull/427
https://github.com/gotk3/gotk3/pull/426
https://github.com/gotk3/gotk3/pull/425
https://github.com/gotk3/gotk3/pull/423
https://github.com/gotk3/gotk3/pull/422
https://github.com/gotk3/gotk3/pull/421
https://github.com/gotk3/gotk3/pull/418
https://github.com/gotk3/gotk3/pull/416
https://github.com/gotk3/gotk3/pull/413
https://github.com/gotk3/gotk3/pull/412
https://github.com/gotk3/gotk3/pull/411
https://github.com/gotk3/gotk3/pull/410
https://github.com/gotk3/gotk3/pull/409
https://github.com/gotk3/gotk3/pull/408
https://github.com/gotk3/gotk3/pull/407
https://github.com/gotk3/gotk3/pull/406
https://github.com/gotk3/gotk3/pull/400

**Comment by andre-hub** [comment]
Hello @rasteric,
i have reviewed many pull requests and merged them. But three changes has no little git conflicts and therefore these remain open for the time being

**Comment by rasteric** [comment]
Thank you so much!
