### ISSUE TITLE
how to destroy Timeout

### ISSUE THREAD

**Issue by liao725636367** [gotk3/gotk3#435]
i had use glib.TimeoutAdd to create timeout and get the result typeof glib.SourceHandle but i dont't know how to stop it

**Comment by hfmrow** [comment]
Hi,
Actually, you cannot do that rightly as indicated in glib reference manual:
1. g_source_remove ()
2. g_source_unref ()
3. g_source_destroy ()

these binding does not exist at this time (I will work on it).

so, while **r**eading **t**he **f**.....g **m**anual, I figure out:

[g-timeout-add](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add):
> Sets a function to be called at regular intervals, with the default priority, G_PRIORITY_DEFAULT. The function is called repeatedly **until it returns FALSE, at which point the timeout is automatically destroyed and the function will not be called again**. The first call to the function will be at the end of the first interval .

return false and you do it ...

declare global var:
`var timeoutContinue = true`

make your timeout:
```
glib.TimeoutAdd(uint(1000), func() bool {
	fmt.Println("timed out")
	
	return timeoutContinue
})
```
Button's callaback func:
```
// Example, in callback to "clicked" signal for a button.
func toStopTimeout(){
	timeoutContinue=false
}
```
Bye.

**Comment by liao725636367** [comment]
thinks for help

**Comment by hfmrow** [comment]
Done
https://github.com/gotk3/gotk3/pull/436

An example on how to use:

```
package main

import (
	"fmt"
	"log"

	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

var timeoutContinue = true
var tos glib.SourceHandle

// Create and initialize the window
func setupWindow(title string) *gtk.Window {
	win, err := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 600, 300
	win.SetDefaultSize(width, height)

	box, _ := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	btn, _ := gtk.ButtonNew()
	btn.Connect("clicked", ButtonClicked)
	btn.SetLabel("Stop timeout")

	box.Add(btn)
	win.Add(box)

	return win
}

func main() {
	gtk.Init(nil)

	win := setupWindow("Go Example Testreport")

	win.ShowAll()

	// Init timeout:
	tos, _ = glib.TimeoutAdd(uint(1000), func() bool {
		fmt.Println("timed out")

		return timeoutContinue
	})

	gtk.Main()
}

func ButtonClicked() {
	var methode int

	// Three methods to stop timeout:
	// 1- Destroying
	// 2- Removing
	// 3- Returning false by called function

	// Choose one of them:
	methode = 3

	switch methode {
	case 1: // 1- Destroying
		mcd := glib.MainContextDefault()
		src := mcd.FindSourceById(tos)
		src.Destroy()
		fmt.Printf("Timeout stopped & IsDestroyed: %v\n", src.IsDestroyed())

	case 2: // 2- Removing
		glib.SourceRemove(tos)
		fmt.Printf("Timeout stopped but still referenced\n")

	case 3: // 3- Returning false by called function
		timeoutContinue = !timeoutContinue
		fmt.Printf("Timeout stopped but still in memory and referenced\n")
	}
}
```

**Comment by liao725636367** [comment]
pretty well,thinks

**Comment by founderio** [comment]
@hfmrow want to add that example to `gotk3/gotk3-examples`?

@liao725636367 The PR for the missing bindings is merged. Is your issue resolved now?

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
