### ISSUE TITLE
 I have some trouble with gtk3

### ISSUE THREAD

**Issue by liao725636367** [gotk3/gotk3#446]
i had use  gotk3 for development. it  works very well, but now there has some problem that bothers me. I can't share the compiled program to my friends and run it on his machine (he isn't  programmer and  don't know How to configure gtk3  development environment), can you help me how to solve this problem?

**Comment by hfmrow** [comment]
Hi,
I don't think anyone can help you without more details about end-user issues ...

**Comment by liao725636367** [comment]
i just want gtk-static library with golang

**Comment by hfmrow** [comment]
[AppImage](https://github.com/AppImage/AppImageKit) ?

**Comment by Bios-Marcel** [comment]
@hfmrow That has nothing to do with static compiling afaik :D

**Comment by hfmrow** [comment]
An appimage may include all necessary gtk libraries to run compiled program ...

**Comment by Bios-Marcel** [comment]
Well, it only works fow linux systems running the app image deamon though. That's like not too many desktops on this planet :smile:

**Comment by hfmrow** [comment]
Your right, not enough desktop on linux, sadly ...
- Appimaged is an [optional daemon](https://discourse.appimage.org/t/new-appimaged-optional-daemon-that-registers-appimages-with-the-system/87) _not needed to work_.
- A good example of gtk3 integration is the most known Gimp [appimage version](https://github.com/aferrero2707/gimp-appimage/releases/tag/continuous). To explore appimage content, it can be [mounted](https://docs.appimage.org/user-guide/run-appimages.html) or simply change extension to zip and opening it.
- It does not work on Windows OS but [MacOs have his switcher](https://docs.appimage.org/user-guide/mac.html).

**Comment by wrycode** [comment]
@hfmrow is right, appimages don't need a daemon, so they should work for this purpose.
Other options: 
https://snapcraft.io/
https://flatpak.org/

If you know which distro your friend is using you can compile for it using a Linux container. The resulting binary will work on their system as long as they have GTK3 installed.

**Comment by andre-hub** [comment]
Maybe the above mentioned solutions were good and could help, otherwise I have the following:
`
go build -ldflags "-linkmode external -extldflags -static" ...`

Whereby this project uses the cgo interface and therefore a go standard functionality and the golang developers have already thought of something.
