### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by unrotten** [gotk3/gotk3#447]
go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid

**Comment by hfmrow** [comment]
Hi,
Maybe **gtk** instead of gdk should work better.

**Comment by wrycode** [comment]
@yunyanU This is a bug in the MinGW pkg-config, you can fix it manually like [this](https://github.com/gotk3/gotk3/issues/296#issuecomment-424969284).

Even better you could figure out where to submit a patch upstream! That would clean things up for us.

**Comment by andre-hub** [comment]
see last commit (https://github.com/gotk3/gotk3/issues/296#issuecomment-424969284)
