### ISSUE TITLE
gtk.TreeStore: Unable to store gdk.Pixbuf objects

### ISSUE THREAD

**Issue by axel-freesp** [gotk3/gotk3#45]
The attempt to store (and view) gdk.Pixbuf objects in a gtk.TreeStore leads to warning messages from the GTK library: ```Gtk-WARNING **: /build/buildd/gtk+3.0-3.14.13/./gtk/gtktreestore.c:856: Unable to convert from gpointer to GObject```, and the icons are not drawn. Note: using a gtk.ListStore does not have this issue.

I will provide a (almost trivial) fix.

**Comment by andre-hub** [comment]
sorry for you merge request, I'm just gone linear through RP and someone was faster.
