### ISSUE TITLE
GtkSourceView mapping missing

### ISSUE THREAD

**Issue by sunshine69** [gotk3/gotk3#457]
Hi,

I am trying to search around but not seeing the gtksourceview mapping is implemented. I might miss places, not sure if it is not yet done, or any plan to make it happen?

See the sibling project https://godoc.org/github.com/pekim/gobbi/lib/gtksource whihc has it, but as it warns me it is not as matured like gotk3 , I hope gotk3 has it...

**Comment by hfmrow** [comment]
Hi,
you look for syntax highlighting or other stuff provided by GtkSourceView ?

p.s: GtkSourceView is not yet implemented in gotk3 ...

**Comment by sunshine69** [comment]
HI thanks, I am looking for syntax highlighting at first and might be the print utilities there as well.

**Comment by sunshine69** [comment]
I tried to take gobbi a bit and found that it is so different from gotk3, it would be lots of effort to port from gotk3 to gobbi. From pygtk3 perspective gotk3 is so easy to work with, thus I hope gtksourceview is available.

**Comment by hfmrow** [comment]
I can help you for syntax highlighting, i've made [this PR](https://github.com/gotk3/gotk3-examples/pull/19) about highlight support for textview via pango, it use chroma too.

hope this help.

**Comment by sunshine69** [comment]
That would be a awesome approach. Thanks - will try it very soon.

**Comment by sunshine69** [comment]
Thanks a lot, I implement mine based on your suggestions and it works perfectly.

**Comment by hfmrow** [comment]
perfect !
If i make a new version with more faster processing i will inform you.
