### ISSUE TITLE
Is full compatible?

### ISSUE THREAD

**Issue by matheusssilva** [gotk3/gotk3#464]
I want to start a new project in the gtk interface which will look very much like a new  gnome config interface.

![E8E66574-77D2-4334-9852-23AECE667420](https://user-images.githubusercontent.com/7414956/68998400-64f03c80-0890-11ea-9b15-2070cd9a6263.jpeg)

Is this binding compatible with all gtk features?  Is it compatible with the latest stable release of Gtk (3.24)?

**Comment by founderio** [comment]
This binding does work with gtk 3.24 just fine. It just may not be 100% complete, as in "some bindings may be missing".

Several people are working on adding missing bindings, so if you are missing any feel free to report an issue asking for them, or add them yourselves.

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
