### ISSUE TITLE
go 1.13 build errors : possible misuse of unsafe.Pointer and unkeyed fields

### ISSUE THREAD

**Issue by MaitreDede** [gotk3/gotk3#467]
Hi,
I am trying to build gotk3 with golang 1.13, and it does not build.

I have added a `go.mod` file.
When I `go vet ./...` I have many messages `possible misuse of unsafe.Pointer`.
I also have many `composite literal uses unkeyed fields`.

The `unkeyed fields` errors are easy to fix, but the `unsafe.Pointers are more obvious...

Has anyone got an idea how to fix these pointer errors ?

**Comment by founderio** [comment]
The errors you mention are not really build errors, just linting issues.

The composite literal things are mostly for brevity, most places these come from are already long enough as-is. It would be easy to fix them, but would make several one-liners too long to keep in one line.

The unsafe pointers are, afaik, not really avoidable in many places. There is a common issue with cgo used in multiple packages: `GObject` imported via package `glib` is not the same type as `GObject` imported by package `gtk`, thus the need to do this conversion (convoluted example):
```go
// in package glib
type Object struct {
    *C.GObject
}

func (v *Object) Native() uintptr {
    return uintptr(unsafe.Pointer(c.GObject))
}

// in package gtk
var gobject *glib.Object // From somewhere else

var c *glib.Object // Used to hand over to C-code

c = C.toGObject(unsafe.Pointer(gobject.Native())
```

If there are ways around this, I'd be curious as well!

**Comment by andre-hub** [comment]
we close the issue, since there was no response.
It can be opened at any time if the issue exists.
