### ISSUE TITLE
 could not determine kind of name for C.GtkPlug and C.GtkSocket

### ISSUE THREAD

**Issue by anthonyraymond** [gotk3/gotk3#471]
Hi,

I got an error when i try to build my application using gotk3

gtk version:
```
# pacman -Qi mingw-w64-x86_64-gtk3
Name            : mingw-w64-x86_64-gtk3
Version         : 3.24.13-1
```

Gotk3 version: master as of 9d4abcb1602160e43cba88eb9fa81beb4318ee53
```
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:105:26: could not determine kind of name for C.GtkPlug
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:37:28: could not determine kind of name for C.GtkSocket
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:73:34: could not determine kind of name for C.Window
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:160:2: could not determine kind of name for C.gtk_plug_construct
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:168:2: could not determine kind of name for C.gtk_plug_construct_for_display
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:182:7: could not determine kind of name for C.gtk_plug_get_embedded
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:175:7: could not determine kind of name for C.gtk_plug_get_id
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:189:7: could not determine kind of name for C.gtk_plug_get_socket_window
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:18:14: could not determine kind of name for C.gtk_plug_get_type
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:138:7: could not determine kind of name for C.gtk_plug_new
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:149:7: could not determine kind of name for C.gtk_plug_new_for_display
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:73:2: could not determine kind of name for C.gtk_socket_add_id
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:81:7: could not determine kind of name for C.gtk_socket_get_id
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:88:7: could not determine kind of name for C.gtk_socket_get_plug_window
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:17:14: could not determine kind of name for C.gtk_socket_get_type
vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:58:7: could not determine kind of name for C.gtk_socket_new
cgo: 
gcc errors for preamble:
In file included from vendor\github.com\gotk3\gotk3\gtk\socket_plug.go:7:
./socket_plug.go.h:2:8: error: unknown type name 'GtkSocket'
    2 | static GtkSocket *
      |        ^~~~~~~~~
./socket_plug.go.h:8:8: error: unknown type name 'GtkPlug'
    8 | static GtkPlug *
      |        ^~~~~~~
```

I think that it means my gtk does not have a `C.GtkSocket` nor `C.GtkPlug` but i'm using the last available gtk version (3_24).
Do you know how to fix it?

Thanks you.

**Comment by hfmrow** [comment]
Hi,
I think Windows does not handle X11 window (linux), I'm not familiar with gtk3 under Windows environment. https://stackoverflow.com/questions/24612433/how-to-use-gtksocket-in-windows-os

https://developer.gnome.org/gtk3/stable/GtkSocket.html
> The GtkPlug and GtkSocket widgets are only available when GTK+ is compiled for the X11 platform and GDK_WINDOWING_X11 is defined. They can only be used on a GdkX11Display.

The source files included are:
```
// #include <gtk/gtkx.h>
// #include <gtk/gtksocket.h>
// #include <gtk/gtkplug.h>
```
Maybe these sources are missing in gtk3' Windows version provided by "mingw-w64-x86_64-gtk3" ...

**Comment by lzk97224** [comment]
I had the same problem .
I edit socket_plug.go and add "// +build linux" ，
but appear a new problem :
![image](https://user-images.githubusercontent.com/10347002/70302549-5619fb80-1838-11ea-921d-0b8fb545a153.png)
@hfmrow

**Comment by hfmrow** [comment]
Hi, @lzk97224

I can suggest you a way, but as i said before, I'm not familiar with windows' gtk3 implementation.

Simply remove 2 files:
...\socket_plug.go.h
...\socket_plug.go

By this way, this issue may be temporary solved, all others parts of gotk3 is not dependent of these files.
I don't recommend to doing that but if you are in an emergency case, I do not see any other way.

**This is NOT a viable solution for Windows users, i hope some others guys with more knowledge can help you in a better way.**

**Comment by graynk** [comment]
> Maybe @graynk could suggest some ideas about that ?

The implementation of GtkSocket and GtkPlug is indeed X11 specific, it's not really mingw's fault. I can take a look at it a bit later in the day, to see what I can do to avoid just removing the files

**Comment by graynk** [comment]
> I edit socket_plug.go and add "// +build linux" ，
> but appear a new problem :
> ![image](https://user-images.githubusercontent.com/10347002/70302549-5619fb80-1838-11ea-921d-0b8fb545a153.png)

Okay, this is very strange, because that's definitely the way to go (and I'll make a PR adding this once we figure out what else is wrong). Because I did a clean install on my Win10 right now, using the documentation from the repo (MSYS2+deps, then go get) added comment like in the picture below, and was able to compile gotk3 and launch applications from gotk3-examples repo. What exactly are you trying to build, can you try building some simple Hello World application from examples repo to confirm that you're able to reproduce it?

![pic](https://user-images.githubusercontent.com/3626328/70315588-b9f1f380-183b-11ea-9b44-705f07670f7e.png)

**Comment by hfmrow** [comment]
I found list of header files contained in mingw-w64-x86_64-gtk3 (included), and all needed headers are present ... effectively, it's not mingw's fault.
```
// #include <gtk/gtkx.h>
// #include <gtk/gtksocket.h>
// #include <gtk/gtkplug.h>
```
https://packages.msys2.org/package/mingw-w64-x86_64-gtk3

**Comment by graynk** [comment]
In any case, it won't work on native Windows (unless you plan on using something like Cygwin/X, but that's beside the point), so you just have to ignore it when compiling. Again, I was able to build without any problems, adding `// +build linux` as stated above, so I would suggest using that solution, as soon as we figure out what's wrong with @lzk97224's build

![pic](https://user-images.githubusercontent.com/3626328/70319886-389f5e80-1845-11ea-8508-7d66d1bd2369.png)

**Comment by lzk97224** [comment]
@hfmrow @graynk 
Thank you for your patience.  I checked my environment again . there are two "zlib1.dll" in my PATH.It's working normally now.

Thank you very much.
