### ISSUE TITLE
Are StatusIcon still supported?

### ISSUE THREAD

**Issue by Gelembjuk** [gotk3/gotk3#475]
Hello,

I want to use systray in my gotk3 application.
I tried to build this example to see how to use it 

https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/statusicon/main.go

But i have the error 

```
./main.go:73:14: undefined: gtk.StatusIconNewFromIconName
./main.go:79:45: undefined: gtk.StatusIcon
./main.go:80:8: menu.PopupAtStatusIcon undefined (type *gtk.Menu has no field or method PopupAtStatusIcon)
```

Is that functionality still supported? 

I have libgtk-3-0 - 3.22.30

**Comment by Bios-Marcel** [comment]
Gtk itself has deprecated those. Deprecated stuff isn't compiled by default. Sadly you can't optionally include ceetain things. All you could do is specifically degining the last gtk version that supported Statusicons.

The demo that you ran was probably made before this was changed.

**Comment by founderio** [comment]
See #253 for a suggested change to solve this problem, open for discussion
