### ISSUE TITLE
DBus Support Proposal

### ISSUE THREAD

**Issue by ioncloud64** [gotk3/gotk3#477]
Suggesting DBus support in gotk3

I understand notifications work well with gotk3 now with the added icon support I did in the previous commit. But after working with Elementary OS and a few other Linux Distributions, it may be wise to implement or include another repostitory such as [esiqveland's notify](https://github.com/esiqveland/notify/) repository for Go.

If this is out of the scope this project I understand. If not, I do not mind adding support for this in gotk3.

**Comment by founderio** [comment]
Not sure if dbus support fits this repo. The project you mention uses a go-native implementation of the dbus protocol: https://github.com/godbus/dbus
I've used that in the past to successfully connect to a mediaplayer using MPRIS. So this really is a separate thing, as contrary to godbus, gotk actually uses cgo to call into the native binaries.

The fact remains that godbus does complements the use cases of gotk, so it may be sensible to link to it and have some examples ready for common use cases.

**Comment by andre-hub** [comment]
dbus and gtk should be regarded as two libs, otherwise this code base is too large
