### ISSUE TITLE
Self-contained binary

### ISSUE THREAD

**Issue by we4sz** [gotk3/gotk3#478]
Hi!

I'm quite new to golang and I have one question. Is there any way to build an application that uses gotk3 so it will be self-contained with static linked references to the C code?

I want to build it for one specific target platform

//John

**Comment by wrycode** [comment]
>I want to build it for one specific target platform
Which platform?

Cross-compiling is already detailed in the wiki. If you really need one executable file and no dependencies you _might_  be able to do it for Linux, but we haven't tried it yet. See https://blog.madewithdrew.com/post/statically-linking-c-to-go/ etc.

**Comment by we4sz** [comment]
Hi!  @wrycode  

We're using this to build an application for an linux embedded system. And I think we can get down the init time some if we build it with static linking so we dont have to have to go c runtime and those stuff?

**Comment by andre-hub** [comment]
You probably have a borderline case that probably cannot be completely implemented with this. The current implementation here is not that modular either. I mean for embedded systems, some changes have to be made, which are not possible with the current number of people.
