### ISSUE TITLE
How to build dynamic window with controls list?

### ISSUE THREAD

**Issue by Gelembjuk** [gotk3/gotk3#492]
I try to build the window using this package when contents of a window should be changed on runtime.

I have the list of "file downloads". I want to display this list in the window. But i can not find how to do this correctly.

Is there some best practice or recomedation on how to do a window containing list of repeated blocks with same structure but different data?
In my case each file is Name,Size, SavePath, Progress bar and Cancel button. On design time i do not know how many records (files) will i have.

The list must be updated every second. And on each update number of rows can be different .

What i did, i created the box on the window and displayed that window. And i have another child box which will be created in this one

Then in a loop (in other goroutine ) :
1. if child box was already created, i remove it from parent box with
parentBox.Remove(childBox)

2. Create child box again and add labels, progresbar, button in it
childBox = gtk.BoxNew()

3. Add back to parent 
parentBox.Add(childBox)

And this works. But only some random iterations and then window becomes empty (no any content) and not responsive. But that goroutine till works and try to repeat all this process.
Other issue is that refresh of widgets blinks 

What can cause this way doesn't work?
maybe there is better, more correct way to do such things?

**Comment by founderio** [comment]
Are you trying to update the UI directly from a goroutine? All modification of GTK objects should run in a block like this:
```go
glib.IdleAdd(func() {
    // Modify GTK stuff here
})
```

Anything NOT touching GTK should of course be in a goroutine and just sync back with IdleAdd (I recommend a wait group if you have to wait for the UI update to complete. Using channels to wait may give you some deadlocks like you describe. Example:

```go
var wg sync.WaitGroup
wg.Add(1)
glib.IdleAdd(func() {
    defer wg.Done()
    // Modify GTK here
})
wg.Wait()
```

If you already do that, then check for deadlocks with channels or similar.

Regarding flickering, a few suggestions:
* Try to group as many updates into the same IdleAdd call
* First build full elements, then swap them with what is on screen (less work in the background between Remove() and Add())
* Re-Use elements where possible. You could have a struct holding a reference to all your elements, i.e. label, progressbar, button and keep them around until the next update. Remove excess, create missing, repurpose existing elements.

Aside from these ideas you probably should look into the GtkListBox for this kind of window structure. Above suggestions still apply, but it may give you some other benefits like sorting & the likes. This is a nice explanation: https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html#listbox
