### ISSUE TITLE
How can I hide title bar without SetDecoration function?

### ISSUE THREAD

**Issue by markity** [gotk3/gotk3#494]

**Comment by nodrygo** [comment]
may be you could try 
```
	nb, _ := gtk.HeaderBarNew()
	win.SetTitlebar(nb)
```

but no way to quit so add quit action (gtk.MainQuit()) somewhere before 
doc here [https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html]

**Comment by founderio** [comment]
Exhaustive headerbar example: https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/titlemenu
