### ISSUE TITLE
PangoTabArray (tabs in TextView)

### ISSUE THREAD

**Issue by piotrpsz** [gotk3/gotk3#497]
Is it possible to create PangoTabArray in the current gotk3 implementation? I can't find it, but maybe I can't see something. Generally, I want to set tabs in TextView. Can it be done at all? And if so, is there an example somewhere?

**Comment by founderio** [comment]
Does not seem to be implemented yet. There are some TODO comments mentioning it, but I can't find it either.
Feel free to help by implementing a wrapper for it. For some pointers on how to get started see https://github.com/gotk3/gotk3/issues/503#issuecomment-582125949
