### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by juniorz** [gotk3/gotk3#5]
The travis build is currently disabled. We have been able to run `gotk3` on travis with a config file like this:

```
language: go

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev

sudo: required
dist: trusty
```

Note we use `trusty` to get more recent versions of GTK+ 3.

For testing, we have used something like this to setup the correct build tag:

```
GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
go test -tags "gtk_${GTK_VERSION}" github.com/gotk3/gotk3/...
```

You can try something along these lines, and enable the travis build.

**Comment by andre-hub** [comment]
thank you for helping by this problem.
i updated the file and create the travis ci agent task.
i have forget create this ...

**Comment by juniorz** [comment]
It seems to be fixed now: https://travis-ci.org/gotk3/gotk3/builds/86256866
