### ISSUE TITLE
Pixbuf support for loading from bytestring (new since gdk-pixbuf/2.32)

### ISSUE THREAD

**Issue by vorot93** [gotk3/gotk3#50]
[gdk_pixbuf_new_from_bytes](https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-bytes)

This is critical for single binaries that store data in memory e.g. using [https://github.com/jteeuwen/go-bindata](go-bindata)

Perhaps even replace all GIO-based Pixbuf interaction (`C.gdk_pixbuf_new_from_file`) with [ioutil.ReadFile](https://golang.org/pkg/io/ioutil/#ReadFile) + gdk.PixbufNewFromBytes ?

**Comment by axel-freesp** [comment]
Do you mean the API at https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Image-Data-in-Memory.html? Or rather https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Inline-data.html?

I can do some first steps in porting...

**Comment by axel-freesp** [comment]
FYE: https://github.com/gotk3/gotk3/commit/5c02e875bfa5e15df2d2bc0e2161934ff2e38b4d contains inmem pixbuf handling. While playing around with transparency/alpha, I realize that some image conversion is needed to handle it correctly. The image.Decoder does some things too much...

Not sure where to discuss this.

**Comment by andre-hub** [comment]
at the moment is the best way, we don't add unstable functions.

the actual plan is to add the gtk and gdk stable functions.
