### ISSUE TITLE
Feature Request: GtkTreeModelSort

### ISSUE THREAD

**Issue by mfulz** [gotk3/gotk3#503]
Is it possible to get a TreeModelFilter sortable without [TreeModelSort](https://developer.gnome.org/gtk3/stable/GtkTreeModelSort.html) in gotk3?

If not, what would I need to help you getting TreeModelSort implemented?
Are there some quick guides available to get into doing it, or should I just read through the actual sources?

Thanks in advance :)

**Comment by founderio** [comment]
Not sure if that is possible without TreeModelSort.

For adding new wrappers, the best tutorial is reading code I'm afraid.
If you want to add support for it yourself, a few pointers to get you started:
* Use `glib.Take()` when wrapping a new object
* Interfaces may be tricky (e.g. `GtkTreeModel`, `GtkTreeSortable` and `GtkTreeDragSource` as this one implements)  
Usually this means there will be a `type ITreeModel interface` with a `toGtkTreeModel()` method returning a native pointer. Check `Window` and `ApplicationWindow` wrappers for examples. This allows generic use in other methods.  
As this class implements `GtkTreeModel` for which there is a dedicated wrapper, you will need to embed a wrapper of that in a similar fashion to how `ApplicationWindow` embeds `ActionMap` and `ActionGroup`.
* Keep deprecated stuff and things introduced in GTK 3.10+ in separate files, see existing examples for the build tags to use. (There is an open discussion regarding deprecated functions here:  #253)

Please take all of this with a grain of salt, this is just based on my experience adding wrappers to this project - not the original author. If you see improvement potential feel free to point that out. Especially the use of `glib.Take()` does not look consistent throughout the repository.

Don't hesitate to try implementing a wrapper and ask for advice in a pull request (I'd suggest marking it as 'WIP' until done though, this project's maintainer is only stopping by occasionally.)

**Comment by mfulz** [comment]
Thanks for your advice, I'll try that ;)

**Comment by MJacred** [comment]
@mfulz / @andre-hub: this can be closed thanks to PR #504 
or do you want to keep this open for milestone V0.4.0 ?

**Comment by mfulz** [comment]
For me it's totally fine to close this.

Thanks for merging and the input @all
