### ISSUE TITLE
[code cleanup] Return an error instead of bool as second return value?

### ISSUE THREAD

**Issue by andre-hub** [gotk3/gotk3#513]
see source #510:

At parts like this I'm not sure if we should follow GTK or not. Other code parts return an error instead of bool as second return value.

see binding for gtk_combo_box_get_active_iter in combo_box.go

@founderio : want to pitch in?

**EDIT:** depending on decision, also adjust binding for gtk_tree_model_sort_convert_child_iter_to_iter

_Originally posted by @MJacred in https://github.com/gotk3/gotk3/diffs_

**Comment by founderio** [comment]
This is a hard decision. There are instances in go where a second return value is a bool:
* Read from channels
* Lookup value from maps
* Type-Casting from an interface

The mentioned functions do somewhat fit into these categories, I think.

Taking a step back: Is it an error if there is no active iter? Is it an error if an iter is not valid in a child model?

Cases could be made for both answers, so I'd vote for "stick to what GTK returns" so people familiar with the GTK API don't get confused.

**Comment by andre-hub** [comment]
It should be decided on a case by case basis. One of the places marked in the PR, which were the reason for this issue, looks like this:
```

func (v *TreeModelFilter) ConvertChildIterToIter(childIter *TreeIter) (*TreeIter, bool) { 
	var iter C.GtkTreeIter 
	ok := gobool(C.gtk_tree_model_filter_convert_child_iter_to_iter(v.native(), &iter, childIter.native())
	t := &TreeIter{iter} 
	return t, ok 
}

```
We can change the second value to error then it matches go, but the boolean comes from the gtk function. We leave it like this for now. And if many people are annoyed by it, we will change it.
