### ISSUE TITLE
[bug fixes] fix some open topics from PR510

### ISSUE THREAD

**Issue by andre-hub** [gotk3/gotk3#514]
you call "native" which returns a *C.GtkTreeSortable and then you convert again...

gtk/gtk.go 
line: 9569

_Originally posted by @MJacred in https://github.com/gotk3/gotk3/diffs_
https://github.com/gotk3/gotk3/pull/510/files/c610b8e515c6b094311f2f7fa2151c9cdf8037cd

**Comment by andre-hub** [comment]
same topic here:
 https://github.com/gotk3/gotk3/pull/510#discussion_r377196361

**Comment by founderio** [comment]
To make it clear, the shortest route to the correct pointer is replacing
```go
sort := C.toGtkTreeSortable(unsafe.Pointer(v.native()))
```
with
```go
sort := v.native()
```
as it already is the correct type.

The `unsafe.Pointer` route is only required for cross-package pointers, as these cannot be in the correct package due to limitations of cgo.

**Comment by founderio** [comment]
@MJacred (CC @mfulz) Regarding the suggested change:

> you can implement userData as type uintptr -> then you won't need a return value

A benefit of using `userData ...interface{}` is to be able to omit the parameter, essentially making the function have an optional argument.

Both implementations currently in use have their flaws.
* Using uintptr, you always have to supply a value, and have to use unsafe pointer logic
* Using ...interface{} and only using the first parameter may confuse people

Suggested correction for both: Use all supplied values. I'll make a PR including this and above change, feel free to comment.

**Comment by andre-hub** [comment]
@founderio  i think now, before we make breaking changes for this topic. we creating a version for some cases with the current api.

i move this issue with the #521  to v0.5

**Comment by founderio** [comment]
@andre-hub Agreed, that was the reason for separate PRs. #520 is not breaking :)

**Comment by andre-hub** [comment]
we create two different version, but the PR #521 with userData ...interface{} is a good solutiion actual.
