### ISSUE TITLE
[BUG] available since 3.16, but deprecated again since 3.22

### ISSUE THREAD

**Issue by MJacred** [gotk3/gotk3#516]
**Describe the bug**
This issue is somewhere between a bug and a design issue (the builds in the future might break, when deprecated functions are no longer available)  
funcs `gtk_popover_set_transitions_enabled` and `gtk_popover_get_transitions_enabled` are available since 3.16, but deprecated again since 3.22  
see https://developer.gnome.org/gtk3/stable/GtkPopover.html#gtk-popover-set-transitions-enabled

**To Reproduce**
* move `gtk_popover_set_transitions_enabled` and `gtk_popover_get_transitions_enabled` to file `gtk_deprecated_since_3_22.go`
* build app with tags gtk_3_6, gtk_3_8, gtk_3_10, gtk_3_12 or gtk_3_14
* build fails with something like `gtk/gtk_deprecated_since_3_22.go:78:16: could not determine kind of name for C.gtk_popover_get_transitions_enabled`

**Expected behavior**
funcs are available for versions of GTK where they support it

**Error messages**
 `gtk/gtk_deprecated_since_3_22.go:78:16: could not determine kind of name for C.gtk_popover_get_transitions_enabled`

**Environment:**
gtk3 version: gtk_3_6, gtk_3_8, gtk_3_10, gtk_3_12 or gtk_3_14
go version: independent
os: independent
 
**Additional context**
There might be other cases.  
Temporary solution: put code into non-deprecated file like `gtk_since_3_16.go` (see #515)

**Comment by founderio** [comment]
This will have to be solved by a file build like this:
```go
// +build gtk_3_16,gtk_3_18,gtk_3_20
```
Just leave out 3_14 and lower.

**Comment by MJacred** [comment]
yeah... sth. like this...  
or there is a smarter solution?

**Comment by andre-hub** [comment]
From my understanding all wishes have been implemented. We close the ticket.
It can be opened at any time if the issue exists.
