### ISSUE TITLE
How to deploy GoTK application to windows users?

### ISSUE THREAD

**Issue by Gelembjuk** [gotk3/gotk3#525]
Currently i have found a way to deploy. I just included all dll files from \msys64\mingw64\bin in my installation package. I am not sure if this is best way. But it works.

However, i got another problem - icons. Now error is bout icon can not be laded. How to add that icon or icons or theme to my application? maybe it can be compiled in single exe ?

```
(download.exe:596): Gtk-WARNING **: 16:50:57.008: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(download.exe:596): Gtk-WARNING **: 16:50:57.008: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk+-3.24.12/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk+-3.24.12/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Exception code=0x80000003 flags=0x0 at 0x000007FEFD5E0932
Exception 0x80000003 0x0 0x0 0x7fefd5e0932
PC=0x7fefd5e0932
```

Original post
I have coded the app with using gotk. It works on my dev machine.

But when i copy the exe file to another windows machine, it shows errors about missed dll 

How to build install package to deploy GTK app? 
In general, i know how to make install packages. But how to know which DLL files to include in he package? Maybe there is some wiki for this or best practice?

**Comment by andre-hub** [comment]
I am afraid that this project will not be able to successfully handle your request. Gotk3 is only a solution for a special problem. Namely the provision of an interface for the general framework gtk for the programming language go.

In my opinion, icons from the system should be located in the respective system paths, own icons, in the paths provided for them. everything in a compiled in single exe is unusual.

Sorry, can't help you.
