### ISSUE TITLE
Why gdk.PixbufGetType is delete?

### ISSUE THREAD

**Issue by mondy** [gotk3/gotk3#527]
gdk.PixbufGetType function is not found in version 0.4.0.
I found a commit where this function is deleted.

a9e38592cccaa251abc5e7338e45cf0619042dac

Why was it deleted?
Is there an alternative function?
I hope that this problem is resolved quickly.

**Environment:**
gtk3 version: v0.4.0
go version: 1.14
os: Ubuntu 18.04

**Comment by MJacred** [comment]
Hm... seems that one got lost in my clipboard. Wanted to move it somewhere else

thanks for your report!  
will add it back in a jiffy

**Comment by mondy** [comment]
Thank you for the quick response.
