### ISSUE TITLE
[Project question] Extending the types

### ISSUE THREAD

**Issue by mispp** [gotk3/gotk3#530]
Extend examples with following:

In C++ / Qt programming i've extended the given classes with additional functionality. For example: using a QTab and extending it to custom QCustomTab with some new members. This object would be easily used in UI later.
How to do the same in gotk3 when no constructors are used and e.g. gtk.NotebookNew() needs to be invoked to return a type?

**Comment by andre-hub** [comment]
The extension with own methods, which do not come from the gtk framework, has already been done.

Therefore this will probably be on a voluntary and needed basis.

I hope I could help you.
