### ISSUE TITLE
[Project question] How do you implemented custom signals

### ISSUE THREAD

**Issue by goreorto** [gotk3/gotk3#532]
This how far I got.
```golang
package main

import (
	"fmt"
	"log"

	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

func setupWindow(title string) *gtk.Window {
	win, err := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	win.SetDefaultSize(600, 300)
	return win
}

var sg, _ = glib.SignalNew("custom-signal")

func main() {
	gtk.Init(nil)

	win := setupWindow("Go Feature Timeline")

	lb, err := gtk.ListBoxNew()
	if err != nil {
		log.Fatal(err)
	}

	lb.Connect("custom-signal", handler)

	lb.Emit("table-activated", "signaldata")

	win.Add(lb)
	win.ShowAll()
	gtk.Main()
}

func handler(lb *gtk.ListBox, data string) {
	fmt.Println("called", data)
}
```

This fails with `too many closure args: have 2, max allowed 1`
It works by removing `data string` parameter from  `func handler` but seems like that's not the expected behavior.

I'm no GTK expert, I've been trying to correlate how it's done in C but it seems like Go has a differrent approach to it or maybe it's not supported yet.

Appreciate any guidance

**Comment by MJacred** [comment]
`Object.Connect()` takes your signal name, the func and a slice of user data.
Currently, gotk3 only supports a length of 1 for the user data slice. This counts for ANY kind of calls to `Object.Connect()` -> ie. this limit applies to normal gtk signals as well
The same limitation takes effect for any kinds of sorting/filtering/etc. funcs you pass to gotk3 widgets

Until this is fixed, I'd advice you to put your values into one `struct` and pass it as user data. or use closures (anonymous functions)

**Comment by goreorto** [comment]
>  takes your signal name, the func and a slice of user data.

the slice you're referring is the variadic argument, correct?
I'm not using userdata in the provided example. 

Asumming that `Emit` also has the same slice size limitations, only one parameters is being sent so that should work, right?

**Comment by goreorto** [comment]
I see what you said now.

The `handler` doesn't support the parameter the parameters added in the `Emit` called. Instead, I need to use the userdata parameter
That makes things kinda funky but I'll have to deal with them.

**Comment by ahsand97** [comment]
I still don't understand how are you supposed to connect to a signal with a string being passed when emitted, @old-goreorto  can you please show it? 

> The `handler` doesn't support the parameter the parameters added in the `Emit` called. Instead, I need to use the userdata parameter

I don't know how to do that, I was passing a test string just like you did in the example and I got the same error

**Comment by ahsand97** [comment]
Ok I see that connect now has changed in the version 6.0 and I don't see the userData parameter no more:
[connect.go](https://github.com/gotk3/gotk3/blob/v0.6.0/glib/connect.go)

previous:
```go
func (v *Object) Connect(detailedSignal string, f interface{}, userData ...interface{}) (SignalHandle, error) {}
```
now:
```go
func (v *Object) Connect(detailedSignal string, f interface{}) SignalHandle {}
```
am I missing something? I don't see a way you can connect to a custom signal and recieve the parameters when emitted like @old-goreorto showed:
```go
lb.Emit("table-activated", "signaldata")
```
