### ISSUE TITLE
[Feature] GetWidget() on IWidget interface

### ISSUE THREAD

**Issue by jroosing** [gotk3/gotk3#533]
**Is your feature request related to a problem? Please describe.**
No decent generic way to create a method that accepts IWidget and then set some attributes on the actual widget. 

**Describe the solution you'd like**
Example from https://github.com/d2r2/gotk3/blob/master/gtk/base.go (GetWidget on IWidget interface). Having this would allow for a generic enough way to set common properties on widgets.

**Describe alternatives you've considered**
- 

**Additional context**
Creating an app that will have a lot of common properties (margins and others) now it feels tedious to either add 4 lines per widget. 

Am also willing to create a PR if desired.

**Comment by MJacred** [comment]
done. did the same for IWindow; wanted that one for quite some time

will be available here as soon as the PR is merged

**Comment by jroosing** [comment]
Thanks @MJacred much appreciated!

**Comment by MJacred** [comment]
I renamed the funcs, as `Get*` sounds misleading, in my opinion.
