### ISSUE TITLE
Unable to get GridInsertRow to work (CLOSED)

### ISSUE THREAD

**Issue by billc3012** [gotk3/gotk3#548]
I may be missing something; here is my code and screenshots.
GO version is 1.14 running on Solus 4.1

```
package main 
 
import ("github.com/gotk3/gotk3/gtk") 
import "fmt" 
 
func main(){ 
    gtk.Init(nil) 
    major:=gtk.GetMajorVersion(); minor:=gtk.GetMinorVersion() 
    fmt.Println(fmt.Sprintf("GTK version %d.%d",major,minor)) 
    win,_ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL) 
 
    win.SetDefaultSize(500,400) 
    win.SetTitle("Grid Test") 
    win.Connect("destroy", func() { gtk.MainQuit() }) 
 
    grid,_ := gtk.GridNew() 
 
    grid.SetOrientation(gtk.ORIENTATION_VERTICAL) 
 
    lbl,_:=gtk.LabelNew("Label 0") 
    grid.Attach(lbl,1,1,1,1) 
 
    lbl1,_:=gtk.LabelNew("Label 1") 
    grid.Attach(lbl1,1,2,1,1) 
 
    btn,_:=gtk.ButtonNewWithLabel("Click") 
    btn.Connect("clicked", func() {hdrClicked(grid,lbl)}) 
    grid.Attach(btn,1,3,1,1) 
 
    win.Add(grid) 
 
    win.ShowAll() 
    gtk.Main() 
    } 
 
func hdrClicked(grid *gtk.Grid, lblRef *gtk.Label){ 
    fmt.Println("Click") 
    lbl,_:=gtk.LabelNew("Added Label") 
    //grid.InsertNextTo(lblRef,gtk.POS_BOTTOM) 
    grid.InsertRow(2) 
    grid.Attach(lbl,1,2,1,1) 
    grid.QueueDraw() 
    }
```
![test1A](https://user-images.githubusercontent.com/24464236/77866243-01364100-727e-11ea-9881-f3d473a100da.png)
![test1B](https://user-images.githubusercontent.com/24464236/77866248-04c9c800-727e-11ea-9315-91030c32d9bb.png)

**Comment by MJacred** [comment]
Hi,

well, first of all: you should start inserting the first item for `left` and `top` with index 0, not 1.  
second: the reason the new label does not show is that you didn't tell it to be visible (it's a completely new widget which is created after your call of `ShowAll()`).  
Please call `lbl.Show()` in `hdrClicked()`. GTK itself demands that you tell it explicitly if it should be visible or not. like you had to do this for your window. -> I also sometimes forget to call this...

happy programming!

**Comment by billc3012** [comment]
Thanks  a lot.  I was looking for the equivalent of Show() but missed it

I will study your reply ASAP

**Comment by MJacred** [comment]
You're welcome.

There is also `SetVisible()`, does almost the same: https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-visible

**Comment by MJacred** [comment]
P.S.: If your question is answered, please close this issue (so the issue list stays clean)!

**Comment by billc3012** [comment]
Will do as soon as I have had time to check it out.  Many thanks to all.

I am impressed by the quality of the response.

Currently I am working flat out on other things, but I will get back to it
ASAP.  Its 6AM here and I have been up for an hour.

Many thanks for your help.

**Comment by MJacred** [comment]
All is well! Just wanted to leave a reminder in some issues that are probably done, so that they don't get forgotten!

**Comment by billc3012** [comment]
Changed  "grid.QueueDraw" to "lbl.Show()".  Worked perfectly.  Thanks again
