### ISSUE TITLE
[Feature] GDK Threads (for asynchronous updates)

### ISSUE THREAD

**Issue by LukBukkit** [gotk3/gotk3#550]
**Is your feature request related to a problem? Please describe.**
Hello,
I'm working on an application which asynchronously fetches data from the internet and changes the content dynamically based on the result (see the add and remove exmaple of ours). The data from the web is returned in another goroutine. I'm removing and adding elements on the fly, but the application crashes sometimes when these updates happen. I supspect these crashes occur, because this isn't the main application thread.
```go
radar.ListenEnterLeave(func(data []*flights.FlightData) {
        // Removing old elements
	planeList.GetChildren().Foreach(func(item interface{}) {
		container := item.(*gtk.Widget)
		container.Destroy()
	})

        // Adding new elements
	for _, flight := range data {
		planeList.Add(modernPlaneRow(flight, cfg))
	}
})
```

Here's an example of an error which appears when the program crashes:
```
(___2run.exe:16368): Pango-CRITICAL **: 19:54:48.007: pango_layout_set_attributes: assertion 'layout != NULL' failed

(___2run.exe:16368): Pango-CRITICAL **: 19:54:48.008: pango_layout_set_alignment: assertion 'layout != NULL' failed

(___2run.exe:16368): Pango-CRITICAL **: 19:54:48.008: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed

(___2run.exe:16368): Pango-CRITICAL **: 19:54:48.009: pango_layout_set_wrap: assertion 'PANGO_IS_LAYOUT (layout)' failed

(___2run.exe:16368): Pango-CRITICAL **: 19:54:48.009: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed
**
Gtk:ERROR:../gtk+-3.24.16/gtk/gtklabel.c:3396:gtk_label_update_layout_width: assertion failed: (priv->layout)
Bail out! Gtk:ERROR:../gtk+-3.24.16/gtk/gtklabel.c:3396:gtk_label_update_layout_width: assertion failed: (priv->layout)

Process finished with exit code -2147483645
```

**Describe the solution you'd like**
I did a bit of research and found the method [`gdk-threads-add-idle`](https://developer.gnome.org/gdk3/stable/gdk3-Threads.html#gdk-threads-add-idle) from the [GDK Thread functions](https://developer.gnome.org/gdk3/stable/gdk3-Threads.html) (see the first link). The method allows to schedule UI update for the main thread. It would be nice if this method could be implemented.

**Describe alternatives you've considered**
As far as I know, the only possible solution is, to implement the C Binding for this method myself. Sadly I don't know of any method in this library that would allow me to perform synchronous updates to the UI.

**Additional context**
[Asynchronous GUI Update in GTK](https://www.yhi.moe/en/2019/01/23/async-gui-update-in-gtk.html)
[Add Remove Example](https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/addremove/addremove.go)

**Comment by dkotik** [comment]
@LukBukkit can you please post your final solution? I am using glib.IdleAdd, but it still does not work.

**Comment by LukBukkit** [comment]
My final solution was using the glib.IdleAdd function and it worked. You can take a look at the example for [goroutines](https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/goroutines/goroutines.go#L70), which uses this function and maybe will help you.
