### ISSUE TITLE
[Project question] How can I built for 32bit architecture from 64bit linux

### ISSUE THREAD

**Issue by RezaSR** [gotk3/gotk3#551]
Hi,
I'm on fedora 31 and has successfully built my app for 64 bit architecture.
I installed the following packages for 32bit cross building:
`gtk3-devel.i686 cairo-devel.i686 glib-devel.i686 libstdc++-*.i686 glibc-*.i686 libgcc.i686`
But when trying to build for 32bit architecture with the following command:
`GOARCH=386 CGO_ENABLED=1 go build`
It fails and throws the following error:
```
# github.com/gotk3/gotk3/glib
In file included from /usr/lib64/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /home/USERNAME/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/glib/application.go:3:
/usr/include/glib-2.0/glib/gtypes.h: In function '_GLIB_CHECKED_ADD_U64':
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:466:3: note: in expansion of macro 'G_STATIC_ASSERT'
  466 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
```
Apparently, glib is including `/usr/lib64/glib-2.0/include/glibconfig.h` but I think it should include `/usr/lib/glib/include/glibconfig.h`

Do you have any idea?
Please help me...

**Comment by erfan-azhdari** [comment]
I solved this problem by building my app on a 32bit `chroot` environment. It's not the best way but it works.

You can make a chroot environment with `febootstrap` (or `debootstrap` on debian systems)
You can also build your app in a 32bit container.

**Comment by andre-hub** [comment]
I am afraid that this project will not be able to successfully handle your request.
We currently have too few developers to solve such special cases. 
Sorry, can't help you.

The solution with chroot or a container is at least one solution.
