### ISSUE TITLE
how to create alwaysontop window?

### ISSUE THREAD

**Issue by d1y** [gotk3/gotk3#557]
I have been looking for a solution to top the window, just like by [electron setAlwaysOnTop](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag-level), Of course, I hope to be compatible with macos and linux-gnome, these are the two development desktops that I usually use.

Thank you

**Comment by pekim** [comment]
https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-keep-above is probably what you want.

**Comment by d1y** [comment]
> https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-keep-above is probably what you want.

Could you please tell me how to operate it? I do n’t know how to operate this interface parameter

**Comment by pekim** [comment]
If were to apply this to simple example in https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/simple/simple.go, you might add this after creating the window (perhaps around line #37).
```go
	win.SetKeepAbove(true)
```

**Comment by d1y** [comment]
> If we were to apply this to the simple example in https://github.com/gotk3/gotk3-examples/blob/master/gtk-examples/simple/simple.go, you might add this after creating the window (perhaps around line #37).
> 
> ```go
> 	win.SetKeepAbove(true)
> ```

Very well, thank you
