### ISSUE TITLE
could not determine kind of name for C.gdk_pixbuf_new_from_bytes

### ISSUE THREAD

**Issue by dodona2** [gotk3/gotk3#56]
what can I do?

# github.com/gotk3/gotk3/gdk
could not determine kind of name for C.gdk_pixbuf_new_from_bytes

**Comment by axel-freesp** [comment]
Seems you have an inconsistent setup (which was only possible when you checkout between Dec. 16 and 17). Possible fixes:

update gotk3/gdk
or update your gdk installation beyond 2.32

-Axel

**Comment by juniorz** [comment]
I think the build tag is wrong. See my comment on https://github.com/gotk3/gotk3/commit/5c02e875

**Comment by juniorz** [comment]
The build used to be broken only on go 1.3, but since the introduction of this function it is broken for everything.

https://github.com/gotk3/gotk3/compare/8ecc7a7e8759...7929189768ba

**Comment by juniorz** [comment]
See: https://travis-ci.org/gotk3/gotk3/builds/97268585

**Comment by andre-hub** [comment]
i fix this problem: remove the unstable method and readd in the futher (after the official gdk release)
