### ISSUE TITLE
[Project question] Resolving FileChooserDialog.GetFilenames() to file paths

### ISSUE THREAD

**Issue by ericnsmith** [gotk3/gotk3#563]
The GetFilenames() method returns a glib.SList which, with its ForEach method, I can iterate over the results but I don't understand how to resolve the unsafe.Pointer to a glib.SList to a string value for the file path. Not sure what I'm missing. Any help would be appreciated.

This is an excerpt of what I've got so far:

`	fileChooserDlg, _ := gtk.FileChooserDialogNewWith2Buttons(
		"Choose files",
		mainWindow.win,
		gtk.FILE_CHOOSER_ACTION_OPEN,
		"Cancel",
		gtk.RESPONSE_CANCEL,
		"OK",
		gtk.RESPONSE_ACCEPT)
	defer fileChooserDlg.Destroy()

	fileChooserDlg.SetSelectMultiple(true)

	var response = fileChooserDlg.Run()

	if response == gtk.RESPONSE_ACCEPT {
		selectedFiles, _ := fileChooserDlg.GetFilenames()
		defer selectedFiles.Free()

		selectedFiles.Foreach(func (ptr unsafe.Pointer) {
			filePath := (*string)(ptr)

			// this gives me a string of a pointer
			// to something that's not a string
			fmt.Println(filePath)

			// this results in runtime error: growslice: cap out of range
			//fmt.Println(*filePath)

			//... do something useful with the filepath here
		})
	}`

**Comment by MJacred** [comment]
Hm... I believe you need to do a type assertion, not a direct cast
```go
ptr.(*string)
```

if that does not help, please provide a compilable example in this issue. And your context info: operating system, gtk version, golang version, etc.

**Comment by ericnsmith** [comment]
The go compiler didn't like that type assertion: 'non-interface type (unsafe.Pointer) on left' and I don't know how to access the unsafe pointer to an slist as an interface.

Operating system: Arch Linux 5.6.5
Gtk version: 3.24.18
Golang version: 1.14.2

Borrowed from the simplegrep example project and modified for multiple file selection and to simply display selected file paths:
```go
package main

import (
	"github.com/gotk3/gotk3/gtk"
	"log"
	"unsafe"
)

func main() {
	gtk.Init(nil)

	win, err := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	win.SetTitle("Gtk FileChooser Demo")
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})

	mainBox, err := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 6)
	if err != nil {
		log.Fatal("Unable to create mainBox:", err)
	}

	textView, err := gtk.TextViewNew()
	if err != nil {
		log.Fatal("Unable to create textView:", err)
	}

	browseBtn, err := gtk.ButtonNew()
	if err != nil {
		log.Fatal("Unable to create browseBtn:", err)
	}
	browseBtn.SetLabel("Browse")

	mainBox.PackStart(textView, true, true, 0)
	mainBox.PackStart(browseBtn, false, false, 0)
	win.Add(mainBox)

	browseBtn.Connect("clicked", func() {
		fileChooserDlg, err := gtk.FileChooserNativeDialogNew("Open", win, gtk.FILE_CHOOSER_ACTION_OPEN, "_Open", "_Cancel")
		if err != nil {
			log.Fatal("Unable to create fileChooserDlg:", err)
		}
		defer fileChooserDlg.Destroy()

		response := fileChooserDlg.NativeDialog.Run()
		if gtk.ResponseType(response) == gtk.RESPONSE_ACCEPT {
			filenames, err := fileChooserDlg.GetFilenames()
			if err != nil {
				log.Fatal("Unable to retrieve filenames", err)
			}

			buffer, _ := textView.GetBuffer()
			currText, _ := buffer.GetText(buffer.GetStartIter(), buffer.GetEndIter(), false)

			filenames.Foreach(func(ptr unsafe.Pointer) {
				// this doesn't work (ptr isn't an interface to be asserted)
				if path, ok := ptr.(*string); ok {
					buffer.SetText(currText + "\n" + *path)
				}
			})

			// this works but not what I need
			//path := fileChooserDlg.GetFilename()
			//buffer.SetText(currText + "\n" + path)
		} else {
			cancelDlg := gtk.MessageDialogNew(win, gtk.DIALOG_MODAL, gtk.MESSAGE_INFO, gtk.BUTTONS_OK, "%s", "No files were selected")
			cancelDlg.Run()
			cancelDlg.Destroy()
		}
	})

	win.SetDefaultSize(800, 600)
	win.ShowAll()
	gtk.Main()
}
```

**Comment by MJacred** [comment]
yeah... there is some more elaborate wrapping required. I made a PR to improve `GetFilenames()
`

**Comment by ericnsmith** [comment]
Looks great. Matches how I use the equivalents in python (PyGtk), mono (gtk-sharp) and .Net Core (gtkSharp). Thanks.
