### ISSUE TITLE
Is it possible to create a custom renderer for a TreeViewColumn?

### ISSUE THREAD

**Issue by jocstar** [gotk3/gotk3#566]
I am new to both gtk and go, never having worked with either until very recently, and have a need to implement a dynamic graph like column in a gtktree.
I haven't been able to find any gotk3 examples of doing this. I have seen examples in C and Python, but have been unable to work out how you might be able to implement something similar here.

**Comment by MJacred** [comment]
If it's possible in the original GTK, then it should be possible here as well.
1. Please try to deduce what bindings are needed (meaning: look at the classes and methods used in the examples).
2. Afterwards, try to check which might be missing (meaning: look in the repo around and check if the classes and funcs are there.  
Please mind that the methods for one class may be stretched over several files -> look out for files named `*_since_3_*.go`; example: gtk_since_3_10.go).
3. Referencing the examples you found here in this thread would be helpful as well.

**Comment by andre-hub** [comment]
There has been no feedback on whether the problem continues. I am therefore closing this issue until further notice. If there is still a need, please open this issue again and add a current problem description.
