### ISSUE TITLE
Layout problems when using GLArea on MacOS

### ISSUE THREAD

**Issue by maxfish** [gotk3/gotk3#567]
**Describe the bug**
Whenever a GLArea is included in a glade file, the whole UI scales/stretches when the main window's size changes.
Here is a video of the glarea example: https://youtu.be/ZykpyNFZFe8
Here is a video of another test where it's possible to see that the issue affects the other UI components as well: https://youtu.be/8nC4bIPJtZg

**To Reproduce**
Just run the **glarea** example from gotk3-examples. I had to make a few small changes to the base example code to make it work, here is the commit with the changes: https://github.com/maxfish/gotk3-examples/commit/4374c85ddabba69daf7f036653e6ba7857098e54

**Expected behavior**
The UI shouldn't stretch, the layout should adjust to the new window size and the components should keep their initial proportion/size.

**Error messages**
If applicable, add copy the log message to help explain your problem.

**Environment:**
OS: MacOS 10.15.3 (19D76) "Catalina"
OpenGL version: 4.1 ATI-3.5.5
Golang v.1.14
From my modules file:
* github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
* github.com/go-gl/mathgl v0.0.0-20190713194549-592312d8590a
* github.com/gotk3/gotk3 v0.4.0
 
**Additional context**
I've tried with different layouts (and glade files), different examples and in every case, as soon as I replace the GLArea component with something else (e.g. DrawingArea), the bug disappears.
Not sure if this is the expected behavior or if it can be related to this issue, but the window's dimensions reported at the startup are express in "scaled" pixels, instead the GLArea's ones are reported (by hooking on the resize event) in "real" pixels. I've tried playing a little with the scaling options of the display, the best result I can get is when real and scaled pixels match. Even in that case the issue is present.

**Comment by maxfish** [comment]
One thing to note is that changing the size of the window at startup, via the SetDefaultSize() function, brings you in a correct UI state no matter the size.
The problem appears only when changing the window size at runtime.

**Comment by MJacred** [comment]
HI,  
thanks for submitting this issue. Currently, I don't have time to take an in-depth look at this. So could you try some things, please?

* try the same without glade
* try replicating the example from the original GTK demo for GLArea in gotk3: https://gitlab.gnome.org/GNOME/gtk/blob/master/demos/gtk-demo/glarea.c
* only glanced over this, but maybe it's related: https://gitlab.gnome.org/GNOME/gtk/issues/105

**Comment by maxfish** [comment]
Hi @MJacred, thanks for the quick reply.

* I've tried without Glade, this is the app.go modified https://gist.github.com/maxfish/dcdc3fbe8fe8b18bf8b14f45fb4ba3fa. Same result.
* I've followed the glarea.c example : one window, one box, one glarea
* Not sure if https://gitlab.gnome.org/GNOME/gtk/issues/105 could be related, but for sure it gives me the impression that OpenGL support might be somehow unreliable also on MacOS

**Comment by MJacred** [comment]
Recently, I read a bit about OpenGL on macOS. It's deprecated for a while now. Might be removed any day. https://github.com/google/angle is a popular choice to make OpenGL work on macOS. Did not look at it myself, though. Maybe there's something you can do

**Comment by MJacred** [comment]
@andre-hub: This seems to be a case of `can't fix` (because this is an issue with Gtk+ on macOS, see also [here](http://gtk.10911.n7.nabble.com/GtkGLArea-td90628.html))
