### ISSUE TITLE
Could not install it

### ISSUE THREAD

**Issue by Isitha** [gotk3/gotk3#57]
When I tried this go get https://github.com/gotk3/gotk3 and go build example.go
I tried to build it because it managed to get the code, and it was added as go build example.go returned an error with a statement referring to the location it is installed in
I got this error-->
# github.com/gotk3/gotk3/glib
../work/src/github.com/gotk3/gotk3/glib/glib.go:259: cannot use idleSrc (type *_Ctype_GSource) as type *_Ctype_struct__GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/glib.go:282: cannot use timeoutSrc (type *_Ctype_GSource) as type *_Ctype_struct__GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/glib.go:293: cannot use src (type *_Ctype_struct__GSource) as type *_Ctype_GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/glib.go:319: cannot use src (type *_Ctype_struct__GSource) as type *_Ctype_GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/glib.go:326: cannot use src (type *_Ctype_struct__GSource) as type *_Ctype_GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/glib.go:330: cannot use src (type *_Ctype_struct__GSource) as type *_Ctype_GSource in function argument
../work/src/github.com/gotk3/gotk3/glib/list.go:40: cannot use v.native() (type *_Ctype_struct__GList) as type *_Ctype_GList in function argument
../work/src/github.com/gotk3/gotk3/glib/list.go:41: cannot use glist (type *_Ctype_GList) as type *_Ctype_struct__GList in function argument
../work/src/github.com/gotk3/gotk3/glib/list.go:46: cannot use v.native() (type *_Ctype_struct__GList) as type *_Ctype_GList in function argument
../work/src/github.com/gotk3/gotk3/glib/list.go:47: cannot use glist (type *_Ctype_GList) as type *_Ctype_struct__GList in function argument
../work/src/github.com/gotk3/gotk3/glib/list.go:47: too many errors

**Comment by andre-hub** [comment]
i need more information
can you write your os, go version version?

when you have ubuntu/debian type in console:
go version
pkg-config --modversion gtk+-3.0
pkg-config --modversion glib-2.0

and send us the return values

**Comment by Isitha** [comment]
So this happened on arch, I actually ended up corrupting the os files, by
messing around with gtk+-3.0, to see if it was the problem.
So I installed xubutu and used the tag 3.10 just like the instructions said
and a new error came up.

New Error--> could not determine kind of name for
C.gdk_pixbuf_new_from_bytes

Details-->
OS->XUBUTU-14.04
GO-version->1.5.2
GTK+-3.0 version->3.10.8
GLIB-2.0->2.40.2

I also used the tag to use 3.10 when I tried to build it.

**Comment by andre-hub** [comment]
i fix this problem.
the problem was a unstable method, readd in the futher (after the official gdk release)

**Comment by sqweek** [comment]
I had these same errors, with the following versions in play:

```
go version go1.2.1 linux/amd64
3.10.8  #pkg-config --modversion gtk+-3.0
2.40.2  #pkg-config --modversion glib-2.0
```

After upgrading go, gotk3/glib installed fine.

```
go version go1.10.4 linux/amd64
```
