### ISSUE TITLE
gdk.GDK_CONTROL_MASK and gdk.GDK_SHIFT_MASK have different types?

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#571]
I doubt this is a bug, most likely I am doing something wrong here, but it it looks like gdk.GDK_CONTROL_MASK and gdk.GDK_SHIFT_MASK have different types? Is that intentional? 

const gdk.GDK_SHIFT_MASK        ModifierType = C.GDK_SHIFT_MASK
const gdk.GDK_CONTROL_MASK C                   = C.GDK_CONTROL_MASK

I am trying to detect if the user is holding down the Control or Shift key using the following code (trying to follow the directions in https://developer.gnome.org/gtk3/stable/checklist-modifiers.html):

```
		modifiers:=gtk.AcceleratorGetDefaultModMask()
		keyEvent := gdk.EventKeyNewFromEvent(event)

                if keyEvent.State() & uint(modifiers) == gdk.GDK_CONTROL_MASK {
			fmt.Println("CONTROL")
		} else if keyEvent.State() & uint(modifiers) == gdk.GDK_SHIFT_MASK {
			fmt.Println("SHIFT")
		}
```
The second if-statement gives me a red squiggly(?) line in GoLand saying "Mismatched types uint and ModifierType", but the first if-statement seems to at least compile. Although it does not seem to do what I want it to do anyway, so I am probably doing something wrong here.

**Environment:**
gtk3 version: '1:3.24.18-1'
go version: '1.14.2'
os: 'Manjaro Cinnamon'
other stuff: '...'

**Comment by MJacred** [comment]
you need to cast your `modifiers` like this `gdk.ModifierType(modifiers)`.  
The modifier types have all the same underlying type `ModifierType`

**Comment by Hultan** [comment]
Like this? It compiles but still does not seem to work though, it still does not print **CONTROL** or **SHIFT** when I press the keys. 

```
		if gdk.ModifierType(keyEvent.State()) & modifiers == gdk.GDK_CONTROL_MASK {
			fmt.Println("CONTROL")
		} else if gdk.ModifierType(keyEvent.State()) & modifiers == gdk.GDK_SHIFT_MASK {
			fmt.Println("SHIFT")
		}
```

**Comment by MJacred** [comment]
yes, or what I wrote in my latest change to my previous comment:

> If that does not work, maybe the only thing you need to change is: cast gdk.GDK_CONTROL_MASK and gdk.GDK_SHIFT_MASK to uint. I don't know by heart how go handles type declaration in combination with bitwise operations

**Comment by MJacred** [comment]
It's also possible that you do need parentheses for the operators around `&`. This depends on the language. Some languages need that

**Comment by Hultan** [comment]
I rewrote it like this, and it is still not working. I guess I'll have to try to create a testing project and figure out how to do this in a small project, with nothing else interfering.

```
		modifiers:=gtk.AcceleratorGetDefaultModMask()
		keyEvent := gdk.EventKeyNewFromEvent(event)
		state := gdk.ModifierType(keyEvent.State())

		if state & modifiers == gdk.GDK_CONTROL_MASK {
			fmt.Println("CONTROL")
		} else if state & modifiers == gdk.GDK_SHIFT_MASK {
			fmt.Println("SHIFT")
		}
```

**Comment by MJacred** [comment]
Ah, now I see it. See here https://yourbasic.org/golang/bitmask-flag-set-clear/. Your understanding of the bitwise operation is wrong (I also mix that up sometimes).

**Comment by Hultan** [comment]
Ah, yeah, it is the first time I use bitwise operators in Go so I will try using the way described in the link instead...thanks, I'll let you know if I get it to work...

**Comment by Hultan** [comment]
But,

func Has(b, flag Bits) bool    { return **b&flag** != 0 }

this is how I used them, right? Am I being really dumb here :-)

**Comment by Hultan** [comment]
No wait, it is working, I have to press another key in combination with the shift or control key. I have tried just by pressing the shift or control key, but when I press shift+1 it prints SHIFT. I WAS BEING DUMB! :-)

Thanks @MJacred!
