### ISSUE TITLE
go get github.com/gotk3/gotk3/gtk faild

### ISSUE THREAD

**Issue by maxuanji** [gotk3/gotk3#574]
# github.com/gotk3/gotk3/glib
d:\goapp\src\github.com\gotk3\gotk3\glib\application.go:3:11: fatal error: gio/g
io.h: No such file or directory
 // #include <gio/gio.h>
           ^~~~~~~~~~~
compilation terminated.

**Comment by maxuanji** [comment]
This problem has been resolved

**Comment by day0market** [comment]
@maxuanji how did you resolve it?

**Comment by halcy0n90** [comment]
same question

**Comment by vivekvardha** [comment]
@maxuanji how did you resolve it?

**Comment by hfmrow** [comment]
Hi @vivekvardha 
'gio.h' means a file that contain headers (link) to "C" implemented functions, objects...
This make available the use of glib functionalities.

> d:\goapp\src\github.com\gotk3\gotk3\glib\application.go:3:11: fatal error: gio/g
io.h: No such file or directory
// #include <gio/gio.h>
^~~~~~~~~~~
compilation terminated.

Explicitly indicate that this file is not present, I'm on linux, by installing dev packages for gtk3, glib, cairo as explained in [installation instructions of gotk3](https://github.com/gotk3/gotk3/wiki#installation), all is done.
But i think you're on Win and you have to install [appropriate libraries](https://github.com/gotk3/gotk3/wiki/Installing-on-Windows) properly to got same results.

Hope that help.

**Comment by vivekvardha** [comment]
Hello @hfmrow,

Thank you for the response.

I already followed the link that you have shared. 
For windows, after performing the steps, I went on installing the required packages mentioned.

And finally in mingw64 prompt, I tried executing "go get github.com/gotk3/gotk3/gtk". Output of this was was the above error.

As per one of the comments in this  [#762](https://github.com/gotk3/gotk3/issues/762#issue-848080504), I also tried downgrading glib2 package. However, I failed in doing so with the following error.

```
$ pacman -U https://download.gnome.org/sources/glib/2.66/glib-2.66.0.tar.xz
warning: database file for 'archlinuxfr' does not exist (use '-Sy' to download)
loading packages...
error: '/var/cache/pacman/pkg/glib-2.66.0.tar.xz': package missing required signature
```

This made me reach over here. 
It would be helpful, if you could provide further inputs to resolve this.

**Comment by hfmrow** [comment]
I don't have enough knowledge about Linux integration in Windows OS.
https://download.gnome.org/sources/glib/2.66/glib-2.66.0.tar.xz, seems to be working to DL, after, i d'ont know how file signatures are handled by Win. maybe you may unpack the tar.xz to original target directory directly and retry.
Honestly i don't know how to proceed with Win. This message look like nothing was DL `package missing`, so, i don't know more.
