### ISSUE TITLE
Fails to build with Go 1.6beta1

### ISSUE THREAD

**Issue by Soreil** [gotk3/gotk3#58]
Probably due to the new Cgo rules, works just fine on Go 1.5.2 on Windows and Linux but fails on both with the beta.

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.Init(0xe6d000)
	/home/sjon/go/src/github.com/gotk3/gotk3/gtk/gtk.go:830 +0x220
main.main()
	/home/sjon/go/src/2048/main.go:63 +0x32
exit status 2

**Comment by yamnikov-oleg** [comment]
I'll check this out.
