### ISSUE TITLE
[Project question] Is it possible to receive a ListStore from TreeView.GetModel() ?

### ISSUE THREAD

**Issue by AdamantGarth** [gotk3/gotk3#580]
A `TreeView.GetModel()` method returns a `gtk.TreeModel` structure, which is embedded in a `gtk.ListStore`, but I don't know how to or if it's even possible to "promote" embedded structure to embedding in Go.

So, is there any way to get a `gtk.ListStore` from `gtk.TreeView` if gtk.TreeView was created like this:
```
listStore, err := gtk.ListStoreNew(glib.TYPE_STRING)
...

treeView, err := gtk.TreeViewNewWithModel(listStore)
...
```

**Comment by MJacred** [comment]
mentioned PR should fix this for you. You can do a type assertion on the returned gtk.ITreeModel.

**Comment by AdamantGarth** [comment]
That was quick, thanks!
