### ISSUE TITLE
[BUG] Value.GetString() returns an error on valid empty string

### ISSUE THREAD

**Issue by yktoo** [gotk3/gotk3#583]
**Describe the bug**
Value.GetString() interprets a `NULL` from `C.g_value_get_string` as an "unexpected nil pointer from cgo" whereas it is seemingly returned on a valid, empty string, contrary to the function's description:

```go
// GetString is a wrapper around g_value_get_string().  GetString()
// returns a non-nil error if g_value_get_string() returned a NULL
// pointer to distinguish between returning a NULL pointer and returning
// an empty string.
```

**To Reproduce**
I'm working with a ListStore instance putting strings into it. Empty strings do cause a `nil` to be returned when using the following code:

```go
v, err := model.GetValue(iter, id)
if err != nil {
	// Handle error
}

s, err := v.GetString()
// err is non-nil here where the value was in fact an empty string
```

**Expected behavior**
Not quite sure, but maybe `NULL` does denote a valid empty string when returned by `g_value_get_string()`?

Its [description](https://developer.gnome.org/gobject/stable/gobject-Standard-Parameter-and-Value-Types.html#g-value-get-string) does not mention neither of the two possible causes explicitly.

**Environment:**
gtk3 version: 3.24
go version: 1.14.2
os: Ubuntu 19.10
GLib version: 2.62
 
**Additional context**
The code in question is [here](https://github.com/yktoo/ymuse/blob/master/internal/player/main-window.go#L1218)

Interestingly enough. the only usage of `GetString()` I discovered in gotk3 is in [gtk_export.go](https://github.com/gotk3/gotk3/blob/master/gtk/gtk_export.go#L29), and it also ignores the returned error.

**Comment by MJacred** [comment]
Hm... I doubt that its a gotk3 bug. gotk3 generally returns this error, if the pointer returned from the C func is nil.

As you stated, the gtk docs say nothing that the returned value may be NULL. While extensive, their docs are not flawless. Sometimes their docs are outdated/incomplete. It's also possible that cgo did something at this point. The comment in gotk3 may be wrong (or outdated, if cgo's behaviour changed), as well.

Personally, I don't see any improvements that can be made to `GetString()`...

I wrote a unittest checking this case (see #586). At least `GetString()` is not at fault. The return value is the expected empty string.

If you are interested, you can write some unittests for `TreeModel.GetValue()`

**Comment by yktoo** [comment]
Yep, you're seemingly right. I have created a few tests that check both `ListStore` and `glib.Value`. It is indeed the case an empty string is properly handled, whereas a *missing* value results in an error from `GetString()`. Will file a PR shortly.
