### ISSUE TITLE
Problem with toWindow method in window.gtk causes segfault

### ISSUE THREAD

**Issue by dgmackay** [gotk3/gotk3#593]
**Describe the bug**
If you pass a nil value as the parent window to gtk.FileChooserNativeDialogNew, it segfaults.  That happens when FileChooserNativeDialogNew in gtk_since_3_20.go attempts to invoke the toWindow method on a nil value.

**Expected behavior**
gtk should provide a transient parent window instead of segfaulting, and open the dialog.

Adding the following:
`var pw *C.GtkWindow = nil
if parent != nil {
   pw = parent.toWindow()
}`

and then using pw in place of parent when calling C.gtk_file_chooser_native_new will successfully open the file chooser dialog.

**Comment by MJacred** [comment]
This should work, because `gtk.toWindow()` returns `nil`, if `parent` is `nil`...

Please provide the stacktrace

**Comment by dgmackay** [comment]
On Thu, 2020-06-04 at 02:34 -0700, MJacred wrote:
> This should work, because gtk.toWindow() returns nil, if parent is
> nil...

Yes, I've seen the code.  The problem is that if it's nil then you're
trying to invoke a method on a nil pointer, which segfaults.

> Please provide the stacktrace

I've already used the indicated patch to fix that routine, so mine
works now.  If you run this snippet against the stock version, you
should get the segfault.

     fcn, err := gtk.FileChooserNativeDialogNew("Choose File", nil,
     	  gtk.FILE_CHOOSER_ACTION_OPEN, "OK", "Cancel")
     if err != nil {
     	panic("Couldn't acquire file chooser dialog")
     }

**Comment by MJacred** [comment]
Seems like it. I provided a fix for almost all places using toWindow(). Except for adding/removing window to/from Application. These are windows which should not be nil in the first place...
