### ISSUE TITLE
MessageDialog with an icon

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#602]
I am not sure if this is a bug, or (most likely) I am using it wrong, but I am trying to make a small MessageBox package for convenience and for my private code (so not super serious). The message boxes works fine so far, but I fail to add an icon to the MessageDialogs (see last few rows). The icon does not show, is this not how you are supposed to do it?

**dialog.SetIconName("dialog-warning") // <- DOES NOT SEEM TO WORK**

```
package messagebox

import (
	"github.com/gotk3/gotk3/gtk"
)

type MessageBox struct {
	Header  string
	Message string
	Parent  gtk.IWindow
	Buttons []Button
}

type Button struct {
	Text         string
	ResponseType gtk.ResponseType
}

func NewMessageBox(header, message string, parent gtk.IWindow) *MessageBox {
	box := new(MessageBox)
	box.Header = header
	box.Message = message
	box.Parent = parent
	return box
}

...removed question and information dialogs...

func (m *MessageBox) Warning() gtk.ResponseType {
	dialog := gtk.MessageDialogNewWithMarkup(m.Parent, gtk.DIALOG_MODAL, gtk.MESSAGE_WARNING, gtk.BUTTONS_NONE, m.Header)
	defer dialog.Destroy()
	dialog.FormatSecondaryMarkup(m.Message)
	dialog.SetIconName("dialog-warning") // <- DOES NOT SEEM TO WORK
	for _, button := range m.Buttons {
		dialog.AddButton(button.Text, button.ResponseType)
	}
	return dialog.Run()
}
```
Calling code:

```
	buttons := []messagebox.Button{{ "Absolutely!", gtk.RESPONSE_OK}, {"Hell no!", gtk.RESPONSE_CANCEL}}
	box := messagebox.NewMessageBoxWithButtons("Update statistics?", "Do you want to update statistics?", m.window, buttons)

	if box.Warning() == gtk.RESPONSE_OK {
		m.picker.UpdateStatistics()
	}
```
Edit : I guess i should have started by using to **project question** template (instead of the **bug** template) to get the **question** label?

**Comment by MJacred** [comment]
yes, you should have used **project question**

---

answer:  There is a unittest for setting/getting icon name. Therefore, the gotk3 lib should be fine.

there are several possible reasons why it does not work:
* you don't have the file,
* or you have the icon, but not in the correct icon path: icons per themes are in `/usr/share/icons` on linux

what is your build environment? please give more info.

by the way: if you try to set icons on a non-linux machine, it's probably the case that your OS does not have the icon (with that name at least)

**Comment by Hultan** [comment]
I use Manjaro (Cinnamon) and Goland.

I though it was the icon name it needed, and not the path. Anyway I tried:

    dialog.SetIconName("/usr/share/icons/Adwaita/16x16/legacy/dialog-warning.png")

And it still does not work, no error message, no icon:
![image](https://user-images.githubusercontent.com/24316220/84647953-7d970280-af04-11ea-95a9-0b33560d90d6.png)

The icon exist on the path above, and the icon named **dialog-warning** exists on my machine (using gtk3-icon-browser):
![image](https://user-images.githubusercontent.com/24316220/84647773-2d1fa500-af04-11ea-8238-bceaff0a0886.png)

**Comment by MJacred** [comment]
well, first of all: no, you don't need to specify the full path. only the icon name. gtk has its own search paths on each platform (which you could overwrite, if the bindings were there)

You gave `gtk.MESSAGE_WARNING` as a parameter. Actually, that's enough for your dialog to show the warning icon in the window body... If you only want the icon in the body, not window title bar, then try removing `dialog.SetIconName("dialog-warning")`.

`SetIconName` is specified in GtkWindow, so the icon will be displayed in the window title bar, I think. The question is: Is that what you want? And: Does your computer setup support icons in windows? Not all platforms use window icons (source: https://developer.gnome.org/gtk3/unstable/GtkWindow.html#gtk-window-set-icon-name).  
It would be nice to check your search path for icons, but there is no binding for `gtk_icon_theme_get_search_path`. Would only help if your setup supports window icons.

If you want, try loading the icon as Pixbuf and then setting it via `SetIcon()`.

**Comment by Hultan** [comment]
Ok, then I can only assume that Manjaro Cinnamon does not support icons in windows, because I tried:

```
	icon,_ := gdk.PixbufNewFromFile("/usr/share/icons/Adwaita/16x16/legacy/dialog-warning.png")
	dialog.SetIcon(icon)
```
and there is still no icon. It is not that important to me, I just thought it was some simple mistake I had made, that would be easy to fix...

Closing the issue now, thanks for your help @MJacred !
