### ISSUE TITLE
[BUG] "Could not determine kind of name for ...." when installing

### ISSUE THREAD

**Issue by reitnorF** [gotk3/gotk3#605]
**Describe the bug**
Error when installing the package via "go get"

**To Reproduce**
go get github.com/gotk3/gotk3/gtk

**Expected behavior**
Package installation success

**Error messages**
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:30:44: could not determine kind of name for C.GNotificationPriority
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:24:54: could not determine kind of name for C.G_NOTIFICATION_PRIORITY_HIGH
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:23:54: could not determine kind of name for C.G_NOTIFICATION_PRIORITY_LOW
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:22:54: could not determine kind of name for C.G_NOTIFICATION_PRIORITY_NORMAL
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:25:54: could not determine kind of name for C.G_NOTIFICATION_PRIORITY_URGENT
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:39:7: could not determine kind of name for C.g_application_get_resource_base_path
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:49:2: could not determine kind of name for C.g_application_set_resource_base_path
/root/go/src/github.com/gotk3/gotk3/glib/glib_since_2_42.go:30:2: could not determine kind of name for C.g_notification_set_priority

**Environment:**
gtk3 version: 3.10.8-0ubuntu1
go version: go1.14.4 linux/amd64
os:Ubuntu 14.04 LTS

**Comment by MJacred** [comment]
what is your glib version?  
which gotk3 version do you use?

**Comment by MJacred** [comment]
Ubuntu 14.04 LTS has glib version 2.40 -> did you use build tag `glib_2_40`? I think that's why it crashes

**Comment by reitnorF** [comment]
I just do this, nothing else : `go get github.com/gotk3/gotk3/gtk`
How to use that build tag?

**Comment by MJacred** [comment]
when you do `go install` and `go build`, you need to use the `-tags` parameter with the input you need, e.g. `-tags gtk_3_16 glib_2_40`

look at the source files (e.g. https://github.com/gotk3/gotk3/blob/master/glib/glib_since_2_42.go). If they mention tags at the top and you want to use their functionalities, you need to add that tag version (or a higher one).

**Comment by MJacred** [comment]
Please close the issue if everything is resolved, or provide more details on your build pipeline...
