### ISSUE TITLE
Random Crashes on mac os

### ISSUE THREAD

**Issue by RajaSrinivasan** [gotk3/gotk3#611]
I am a new user. I am experiencing random crashes on startup on my Mac OS/X. The app itself is quite simple and can be found here:

https://sourceforge.net/p/gohanoi/code/ci/master/tree/

Upon cloning:
**make
bin/gtk_gohanoi 8 graphic**

will reproduce the problem.

It is a "Towers of Hanoi" with graphics.

It runs well sometimes but randomly crashes with the following trace:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fff5130c018]

runtime stack:
runtime.throw(0x4422110, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 1 [syscall]:
runtime.cgocall(0x4307de0, 0xc000161ea8, 0xc000000180)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000161e78 sp=0xc000161e40 pc=0x4005d0b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:15288 +0x41 fp=0xc000161ea8 sp=0xc000161e78 pc=0x4142991
github.com/gotk3/gotk3/gtk.Main(...)

...
...

Any ideas on how to troubleshoot will be helpful.

thanks, srini

**Comment by linuxerwang** [comment]
Like almost all UI systems, drawing has to be in a single thread, called UI thread. GTK is no difference, it uses gtk main thread.

So you have to do UI updates in gtk main thread, in callback functions like "click" or "changed" event handlers. Otherwise, if you created your own goroutines and you try to update the UI in them, you have to do it through gtk.IdleAdd(). You UI update will be done in the same thread when gtk event loop is idle.

**Comment by RajaSrinivasan** [comment]
Not having much luck with this. On my other mac which is quite beefy and a later version it worked with no crashes. On this MacOS Sierra, (10.13.6) on an Early 2011 version, even with the AddIdle approach, the crashes are random.

Hopefully this section of the dump may throw some light.

goroutine 19 [runnable]:
github.com/gotk3/gotk3/glib._Cfunc_g_idle_source_new(0x6a09880)
	_cgo_gotypes.go:1570 +0x4a
github.com/gotk3/gotk3/glib.IdleAdd(0x43703c0, 0x4421c60, 0xc00003ab98, 0x1, 0x1, 0x3, 0x3, 0x22)
	/Users/rajasrinivasan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/glib/glib.go:290 +0xdf
git.code.sf.net/p/gohanoi/code/gohanoi/hanoi.(*gtkVisualHanoi).Notify(0x4995b60, 0x2, 0xc000188270, 0xc0001882a0, 0x1)
	/Volumes/Data/Prj/gohanoi/hanoi/gtk_visual.go:209 +0x88
git.code.sf.net/p/gohanoi/code/gohanoi/stack.(*Stack).Move(0xc000188270, 0xc0001882a0, 0x0, 0x0)
	/Volumes/Data/Prj/gohanoi/stack/stack.go:126 +0xbb
git.code.sf.net/p/gohanoi/code/gohanoi/hanoi.(*Hanoi).MoveAll(0xc0001a8000, 0x1, 0xc000188270, 0xc0001882a0, 0xc0001882d0, 0x0, 0x0)

 I will soon have a Linux machine and will test it out. Any other suggestions?

**Comment by RajaSrinivasan** [comment]
OH BTW,  this is functional on a RPI 3 as well.

**Comment by RajaSrinivasan** [comment]
Figured out my issues. I ended up using TimeoutAdd and did a bit of restructuring and now all is well. thanks for the pointer towards IdleAdd.
