### ISSUE TITLE
[Feature] Handle mouse second button click

### ISSUE THREAD

**Issue by alivesubstance** [gotk3/gotk3#617]
**Is your feature request related to a problem? Please describe.**
Failed to handle mouse second button click. 

**Describe the solution you'd like**
Properly process mouse click event to have an option to distinguish between mouse buttons.

**Describe alternatives you've considered**
There is no alternative. I've implemented mouse handle by myself. See below.

**Additional context**
There is an EventKey that describe mouse button click event but it has no provide `button` field from original C `GdkEventButton` struct. The next code can check is mouse second button click. It could be include in gotk3 project.

    func isMouse2ButtonClicked(e *gdk.Event) bool {
        event := &gdk.EventKey{Event: e}
        mouseButton := (*C.GdkEventButton)(unsafe.Pointer(event.Event.GdkEvent)).button
        return uint(mouseButton) == 3
    }

**Comment by graynk** [comment]
I'm trying to do the same thing, could you explain how it works for you? I get an `could not determine kind of name for C.GdkEventButton` error

**Comment by alivesubstance** [comment]
Very nice! 
You've got an error `could not determine kind of name for C.GdkEventButton` cause in this case you have to 
include gdk.go.h into you project and
