### ISSUE TITLE
gdk EventType typo

### ISSUE THREAD

**Issue by jrm-1535** [gotk3/gotk3#618]
It seems that EVENT_LEAVE_NOTIFY is mapped to the wrong native value: C.GDK_ENTER_NOTIFY
https://github.com/gotk3/gotk3/blob/f7e85ed33fd290bcfbf4ce56dcdae192647f42c1/gdk/gdk.go#L429

Also, EVENT_ENTER_NOTIFY is not defined.

**Comment by MJacred** [comment]
Could you do a pull request, please?

**Comment by jrm-1535** [comment]
Hum, while preparing for the pull request I realized that I was looking at v0.4.0, but the code in master is now correct.
This was fixed already with commit f71cc72d7edac8bfef5de23fc6f3d8d394f4f28d on May 21 "fix wrong EventType value + add missing one".

Sorry about that. I will close it.
