### ISSUE TITLE
Change repository status (remove fork dependency)

### ISSUE THREAD

**Issue by Soreil** [gotk3/gotk3#62]
The repository is currently seen as a fork of the conformal master. This disables searching of the repo on the github website. It also makes it so that when you make a pull request it defaults to diffing the conformal repo and the gotk3 repo. This takes a super long time to load on slow computers.

**Comment by andre-hub** [comment]
i believe, when i delete the fork dependency, we lost all infos for issues, pullrequest and more.

**Comment by Soreil** [comment]
Ah, that is very unfortunate.

**Comment by andre-hub** [comment]
i found regrettably only this way:

 * made sure my local copy was up to date.
 * created a new project in github.
 * git remote rm origin
 * pushed the code to the new project (per the new project instructions)
 * deleted the old project/fork within github
 * renamed the new project over the old project.
 * updated the origin remote to point to the original url

I will not do so.

**Comment by yamnikov-oleg** [comment]
[This help page](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) says:
> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support.

So maybe it's possible to drop dependency without losing any data.

**Comment by andre-hub** [comment]
is done! i hope this was in yours sense.
