### ISSUE TITLE
[BUG] Built .exe file failed to run due to missing DLL's

### ISSUE THREAD

**Issue by alivesubstance** [gotk3/gotk3#621]
**Describe the bug**
I've built gotk3 glade example on Windows using `MINGW64` by command
`GOOS="windows" GOARCH="amd64" go build -o "app.exe" https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/glade`. After run `app.exe`  I see four system error dialogs which describes that the next libraries were not found:
- libcairo-2.dll
- libcairo-gobject-2.dll
- libfontconfig-1.dll
- libgdk-3-0.dll

All these libraries are from `MINGW64` installation and I've tried to include them into build with options `CGO_ENABLED=1 CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc CGO_CFLAGS="-IC:\tools\msys64\mingw64\bin"` but has no luck. 

**To Reproduce**
1. Get `https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/glade`
2. Build `GOOS="windows" GOARCH="amd64" go build -o "app.exe" https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/glade`
3. Run `app.exe`

**Expected behavior**
Program run and show UI.

**Error messages**
Failed to find libraries from above.

**Environment:**
gtk3 version: 'v0.4.0'
go version: '1.14.3'
os: 'Windows 10'
 
**Additional context**

**Comment by MJacred** [comment]
this looks like your setup is incomplete

just to be sure
* Did you install GTK? https://www.gtk.org/docs/installations/windows/
  * did you check that the installation was successful?
* did you bundle the libraries? https://www.gtk.org/docs/installations/windows/#building-and-distributing-your-application
  * also the GLIB schema files?
* which gotk3 version do you use?

**Comment by alivesubstance** [comment]
Thank you for tou reminder. I've remove all previously installed gtk related things and install again regarding your instructions. After all trying to build glade from gtk3-example I've got:
`go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid`

My gotk3 version is from `v0.4.0` tag. Should I use `master` branch instead?

**Comment by TechAdvancedCyborg** [comment]
same issue here

**Comment by jcbritobr** [comment]
> 
> 
> Thank you for reminder. I've remove all previously installed gtk related things and install again regarding your instructions. After all trying to build glade from gtk3-example I've got:
> `go build github.com/gotk3/gotk3/gdk: invalid flag in pkg-config --libs: -Wl,-luuid`
> 
> My gotk3 version is from `v0.4.0` tag. Should I use `master` branch instead?

I workaround ths here:
https://github.com/gotk3/gotk3/issues/562#issuecomment-633151874

**Comment by jcbritobr** [comment]
If the ',' is really wrong I thing I'll fix this by myself. Is just a pontual fix.

**Comment by jcbritobr** [comment]
Its a gtk package issue.

**Comment by alivesubstance** [comment]
Finally I've found out how to run application. I've built on Windows and run on Windows. If built app tell you about missing libraries copy executable to `mingw64/bin`. It should help. 

The second step is to find out which libraries is mandatory for you app. There is a program that helps to find dependent libraries but no one helped me. I've copied `mingw64` installation with my app into separate folder and manually removed unnecessary libraries till get minimal snapshot. Here is a link to minimal snapshot https://github.com/alivesubstance/zooverseer/tree/1.0.0/bin/win/mingw64. It's my open source project.

**Comment by CHchenf** [comment]
Even if I operate according to this method, the problem still exists. If I transplant to other windows desktop systems, it is reported that DLL is missing

**Comment by CHchenf** [comment]
Copying all the files in mingw64 directory to the new windows can run the go GUI program normally, but this operation is a little too unchanged

**Comment by jcbritobr** [comment]
I think we can close this bug, because it is a miss use of gtk libraries. No need to get it opened.
