### ISSUE TITLE
[Project question] Loading an webp image file

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#632]
If you try to load a *.webp file into a gdk.Pixbuf using the gdk.PixbufNewFromFile() function you get an error:

```Couldn’t recognize the image file format for file “4kberLzSvx0.webp”```

So I started to look at the package **golang.org/x/image/webp** (https://pkg.go.dev/golang.org/x/image/webp?tab=doc) but I don’t know if this package is what I am supposed to use to enable **webp** format support, or how to use it properly.

Does anyone here know how to load an image in **webp** format?

You can see my code at:

https://github.com/Hultan/testWebp

This is my test code so far:

```
package main

import (
	"fmt"
	"github.com/gotk3/gotk3/gdk"
	_ "golang.org/x/image/webp"
)

func main() {
	// Jpeg works fine
	loadImage("031wc2m0IWs.jpg")

	// Webp does not work
	loadImage("4kberLzSvx0.webp")
}

func loadImage(path string) *gdk.Pixbuf {

	image, err := gdk.PixbufNewFromFile(path)
	if err!=nil {
		fmt.Printf("%s", err.Error())
	}
	return image
}
```

**Comment by Hultan** [comment]
I got a suggestion on how to read a **webp** image from the go forum (https://forum.golangbridge.org/t/loading-a-webp-image-file/20050/4). I can now read a **webp** image and get an image.Image out of it. How do I convert an image.Image to an gdk.PixBuf though?

```
func loadImageWebp(path string) image.Image {
	f, err := os.Open(path)
	if err!=nil {
		fmt.Printf("%s", err.Error())
	}
	image, err:=webp.Decode(f)
	if err!=nil {
		fmt.Printf("%s", err.Error())
	}

	return image
}
```

GitHub is updated.

**Comment by ryanerwin** [comment]
I'm just learning how this stuff works, so hopefully someone who knows more can confirm or elaborate.

From what I could see, it looks difficult to get libp images directly working inside of Gdk.Pixbuf. The Gdk.Pixbuf team has been waiting on libp to support pixbuf, the way that the SVG library also supports rendering into pixbuf.

See:

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/103

However, there is an alternative GdkPixbuf loader that can be used, but I'm not sure how widely shipping it is yet, after you figured out how to use this, I assume that you would have to ship those libraries along with your app.

https://github.com/aruiz/webp-pixbuf-loader

For me on Ubuntu 20.04, trying to open an example webp image works fine in Firefox, but when I try to use Eye of Gnome, I get an error that the file can't be opened. If Ubuntu 20.04 shipped with the webp-pixbuf-loader above, I think that I should be able to open webp images, just like I can open svg images...

![image](https://user-images.githubusercontent.com/2156415/89744475-6e34cf80-dad7-11ea-805d-3887a5606a7d.png)

**Comment by Hultan** [comment]
Ah, nice to know the explanation behind the problems I am having. I see a couple of solutions then:

1. Wait for **webp/GdkPixBuf**-support to be built in. Might not happen.
2. Use the loader you mentioned.
3. Wait for **youtube-dl** to support an option to download thumbnails as **jpg**. Might not happen.
4. Do a conversion, as I mentioned above, where I load the **webp** and save it as a **jpg**.

I'll probably go for option 4 since I know how to do that and already have the solution for that. Thanks for the information.
