### ISSUE TITLE
How to add actions to MenuButton items?

### ISSUE THREAD

**Issue by thunderrous** [gotk3/gotk3#639]
Sorry for a simple question but i'm having difficulties navigating the docs.

I have this in one function to create the menu button

```golang
func CreateDropDownMenu(margin []int, grid gtk.Grid) *glib.Menu {
	// Create a new menu button
	mbtn, err := gtk.MenuButtonNew()
	if err != nil {
		log.Fatal("Could not create menu button:", err)
	}

	// Set up the menu model for the button
	menu := glib.MenuNew()
	if menu == nil {
		log.Fatal("Could not create menu (nil)")
	}

	mbtn.SetMenuModel(&menu.MenuModel)

	mbtn.SetMarginStart(margin[0])
	mbtn.SetMarginEnd(margin[1])
	mbtn.SetMarginTop(margin[2])
	mbtn.SetMarginBottom(margin[3])

	// Add menu to the grid
	grid.Add(mbtn)

	return menu
}
```
The grid is:
```golang
headerGrid, err := gtk.GridNew()
if err != nil {
	log.Fatal("Unable to create grid:", err)
}

headerGrid.SetOrientation(gtk.ORIENTATION_HORIZONTAL)
```

In a third function, i have something that adds them on app launch (there's another button that adds new ones but that's working). I'm not hardcoding them because they will change. They're read from a JSON file.
```golang
for _, bd := range library.ImportedLibrary.Boards {
	menu.Append(bd.BoardName, "win.showBoard")

	// Would be best to add actions for buttons here as they're being added
}
```

My question is: how do i add actions to individual items? The example `titlemenu` from the examples repo doesn't work (adding with `win.AddAction(aClose)`) for me because my `win` variable is `*gtk.Window` not `*gtk.ApplicationWindow`. Since it's getting these titles for items from a struct i'd like to fill some widgets with text from the corresponding struct when that item is pressed.

**Comment by MJacred** [comment]
just in case, your `aClose` is roughly defined as follows?

```go
aClose := glib.SimpleActionNew("showBoard", nil)
aClose.Connect("activate", func() {
	doSomething()
})
window.AddAction(aClose)
```

`AddAction()` is defined in `IActionMap interface`. Only gtk.Application and gtk.ApplicationWindow implement that one.
* `win.*` for gtk.ApplicationWindow
* `app.*` for gtk.Application/glib.Application

Adding an action to something else is not possible, to my knowledge. You define them in an application or applicationwindow and then the widgets call them.

The only other thing that comes to my mind is that you create a popover and fill it with normal buttons, which are connected to signals

**Comment by thunderrous** [comment]
Thanks @MJacred

**Comment by hfmrow** [comment]
Hi, 
You need something like this bellow ?

```go
package main

import (
	"fmt"
	"log"

	"github.com/gotk3/gotk3/gtk"
)

var win *gtk.Window
var box *gtk.Box
var btn *gtk.Button

// examle:
func example() {

}

// btnClicked: Callback "clicked" button' signal
func btnClicked() {

}

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")
	example()
	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {
	var err error
	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatal("Unable to create box:", err)
	}

	// MENU button -start-
	MenuButton, err := gtk.MenuButtonNew()
	if err != nil {
		log.Fatal("Unable to create MenuButton:", err)
	}
	MenuButton.SetLabel("The name of it")

	menu, _ := gtk.MenuNew()

	mItem1, _ := gtk.MenuItemNew()
	mItem2, _ := gtk.MenuItemNew()
	mItem1.SetLabel("m1")
	mItem2.SetLabel("m2")
	mItem1.Connect("activate", func() { fmt.Println("m1") })
	mItem2.Connect("activate", func() { fmt.Println("m2") })

	mItem1.ShowAll()
	mItem2.ShowAll()

	menu.Append(mItem1)
	menu.Append(mItem2)

	menu.SetHAlign(gtk.ALIGN_CENTER)
	menu.SetVAlign(gtk.ALIGN_CENTER)

	MenuButton.SetPopup(menu)
	// MENU button -end-

	box.Add(MenuButton)
	win.Add(box)
	win.ShowAll()
	return win
}

```
Regards.

**Comment by thunderrous** [comment]
@hfmrow i've already used application to create it like in examples, but I'll keep this in mind. On the other hand, i'm trying to grab menu items to update their text. Is there a way i can iterate or use indexing on glib.Menu items?
