### ISSUE TITLE
[BUG] title

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#646]
**Describe the bug**
The function `gdk.PixbufNewFromFile` sometimes fails to read JPG files with the error:

    "Couldn’t recognize the image file format for file “fail.jpg”

The failed JPGs can be opened in an image viewer, like `Pix` on Linux, without a problem, and **GitHub** has no problem displaying it. 

The images are downloaded with `youtube-dl`, and 95% of the images I download with `youtube-dl` works just fine. It seems like it is only thumbnails from certain channels that pretty much always fails. This leads me to think that there is some property set in the program that creates the thumbnails, that is set by these channels, that is not supported by the function `gdk.PixbufNewFromFile`. 

In my example on **GitHub** (link below) this is the image failing (a thumbnail from the **David Pakman Show**):

https://github.com/Hultan/jpg-fail/blob/master/fail.jpg (link to video : https://www.youtube.com/watch?v=7g99lKLk898)

Note that this error occurred in Go 1.14 as well, even though I updated last night to Go 1.15.

**To Reproduce**

Code can be found here : https://github.com/Hultan/jpg-fail

**Expected behavior**

No fail

**Error messages**

"Couldn’t recognize the image file format for file “fail.jpg”

**Environment:**
gtk3 version: '3.24.23-1'
go version: '1.15.1-1'
os: 'Manjaro (Cinnamon)'

**Comment by hfmrow** [comment]
Hi,
WebP format is not handled by gtk3 (at this time...)
- XViewer can't open it
- Pix can do it
- XnViewMp do it too

Just convert it to png or jpg.
```
Fichier	
Nom de fichier	fail.jpg	
Répertoire	~/jpg-fail-master	
Taille de fichier	14.48 Kio (14 824)	
Date/Heure de création	09/09/2020 - 18:50:11 CEST	
Date/Heure de modification	09/09/2020 - 08:58:32 CEST	
Date/heure d'accès	09/09/2020 - 18:50:19 CEST	
Note	0	
Libellé de couleur	0	

Image	
Format	WebP	
Largeur	336	
Hauteur	188	
Nb bits	24	
Modèle couleur	RGB	
Taille d'impression	11.85x6.63 cm, 4.67x2.61 pouces	
Compression	Aucune	
Nb images/pages	1	
Origine	Haut gauche	
```

**Comment by Hultan** [comment]
Oh, I thought that I had converted the WebP to a JPG, but apparently just by name I guess?

**Comment by hfmrow** [comment]
if you just change extension, its not a conversion ...
XnViewMp or Gimp could convert in multiple formats

**Comment by Hultan** [comment]
_if you just change extension, its not a conversion ..._

I understand that, what I did was that I wrote a program to convert it myself, but obviously that is not working as expected. I might need to use `convert-webp-to.jpg`instead...I will look into that, since I don't know anything about image formats myself. I don't know why I thought that doing it myself was a good idea :-)

Thanks...

**Comment by hfmrow** [comment]
yes it's a good idea to learn how to do it, some time ago i did some research on webp and golang on github, like i said i found some tips but not enough time to do something that works properly, if you can find a solution, I would be happy to be notified. :)
