### ISSUE TITLE
SetVisibleFunc/PixbufGetType problem

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#662]
When I compile my project against version 0.4.0, I now get an error ```Unresolved reference 'PixbufGetType'```. I feel that this compiled just a few months ago. According to #527 this function was accidentally deleted in version 0.4.0 (in february?), but this is fixed now in master, but no new version is released.

go.mod : ```github.com/gotk3/gotk3 v0.4.0```

So I changed my reference (in the go.mod file) to reference the master branch (I believe I ran ```go get github.com/gotk3/gotk3@master```:

go.mod : ```github.com/gotk3/gotk3 v0.4.1-0.20200919055744-5c37c8051f06```

Now the following code does not compile, the error I get is : 
```
Cannot use 'v.filterFunc' (type func(model *gtk.TreeModelFilter, iter *gtk.TreeIter, userData interface{}) bool) as type (TreeModelFilterVisibleFunc, interface{}) or TreeModelFilterVisibleFunc
```

Here is the code:

```
        ...

	filter, err := listStore.FilterNew(&gtk.TreePath{})
	if err!=nil{
		logger.LogError(err)
                return
	}
	filter.SetVisibleFunc(v.filterFunc)    // <--- Error here
	v.TreeView.SetModel(filter)

        ...

        func (v *VideoList) filterFunc(model *gtk.TreeModelFilter, iter *gtk.TreeIter, userData interface{}) bool {
                return true; // Removed a lot of irrelevant code here
        }
```
How to solve this issue? Can I reference just the 0.4.0 plus the PixBufGetType-commit in my go.mod?

**Comment by hfmrow** [comment]
Hi,

go get github.com/gotk3/gotk3/gtk

may solve your issue ...

**Comment by Hultan** [comment]
@hfmrow : Sorry, it did download and recompiled everything again, but no change.

**Comment by hfmrow** [comment]
original definition:
```go
type TreeModelFilterVisibleFunc func(model *TreeModelFilter, iter *TreeIter, userData ...interface{}) bool
```

userData **...** interface{} : Three dot ...

```go
        func (v *VideoList) filterFunc(model *gtk.TreeModelFilter, iter *gtk.TreeIter, userData ...interface{}) bool {
                return true; // Removed a lot of irrelevant code here
        }
```

**Comment by Hultan** [comment]
There you go! You have better eyes than me obviously :-)

I got a warning about the unused userData parameter, so I removed it, and then I added it back again later (when I was trying to fix this error) without the dots apparently...

Thank you...
