### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#667]
This might not really be a GoTk3 question, but I will try here first.

Let's say I have a function like this, in this case I am not actually using the argument ```entry```:
```
func (p *page2) onKeyPressed(entry *gtk.Entry, event *gdk.Event) {
	keyEvent := gdk.EventKeyNewFromEvent(event)

	if keyEvent.KeyVal() == keyValF1 {
		p.hint.SetText(getLongHint())
	}
}

```

I believe I can't remove the ```entry``` argument, because I am using the ```event``` argument. So what would be the idiomatic way here to get rid of the GoLands warning? Just fake a use of the parameter? And yes, I hate warnings, I want to get rid of them all. But there are situations, like above, where I don't know what to do.

![golang_problem](https://user-images.githubusercontent.com/24316220/95332057-69ec1f00-089a-11eb-8728-3b46715518d1.png)

**Comment by pekim** [comment]
Replace `entry *gtk.Entry` with `_ *gtk.Entry`?

**Comment by Hultan** [comment]
Lol, it was that easy? I did not know that you could do that in a function declaration, I thought it was for variable declarations only...I feel kind of stupid now :-)
