### ISSUE TITLE
Caps Lock warning not displaying, and no Cursor for GtkEntry

### ISSUE THREAD

**Issue by deranjer** [gotk3/gotk3#668]
Not sure if a bug, or not implemented in this package, or what.

This is my first try at gtk3, and using Glade.  I have a GtkEntry box, but when I click on it no cursor appears in the entry box, and no caps lock warning appears when I turn on caps lock.

I am running on Windows using mingw64 and go 1.15, and glade 3.36.0

**Comment by hfmrow** [comment]
Hi,
I tried under linux,
1st activate password mode:
```go
Entry.SetInputPurpose(gtk.INPUT_PURPOSE_PASSWORD) // or gtk.INPUT_PURPOSE_PIN
```
2nd set property (Whether password entries will show a warning when Caps Lock is on.):
```go
Entry.SetProperty("caps-lock-warning", true)
```
3th to ensure Entry is editable ...
```go
Entry.SetProperty("editable", true)
```
The entry can be modified with the cursor still flashing.
And finally, the result is ... does not work :(, and very surprised, the input method set to password or pin does not change the input type (text not hidden).
I don't know how to solve this issue.

Test code:
```go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gtk"
)

var (
	win   *gtk.Window
	box   *gtk.Box
	entry *gtk.Entry
)

// btnClicked: Callback "clicked" button' signal
func btnClicked() {

}

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")

	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {
	var err error
	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatal("Unable to create box:", err)
	}

	entry, err = gtk.EntryNew()
	if err != nil {
		log.Fatal("Unable to create entry:", err)
	}

	entry.SetInputPurpose(gtk.INPUT_PURPOSE_PASSWORD)
	entry.SetProperty("caps-lock-warning", true)
	entry.SetProperty("editable", true)

	box.Add(entry)
	win.Add(box)
	win.ShowAll()
	return win
}
```

**Comment by deranjer** [comment]
Thank you, I assume this will work, but I ended up rewriting the app in Fyne (although caps lock notification doesn't fully work there, but cursor does, good enough for me) so I will close this for the time being.
