### ISSUE TITLE
Can't convert from *gtk.Widget to *gtk.Label

### ISSUE THREAD

**Issue by shsms** [gotk3/gotk3#67]
gtk.Bin.GetChild() returns *gtk.Widget,  but I can't find a way to convert that to a *gtk.Label.  So I wrote this function:
```Go
func (v *Widget) ToLabel() *Label {
        return wrapLabel(wrapObject(unsafe.Pointer(v.native())))
}
```

Is this the right way to solve this?

**Comment by yamnikov-oleg** [comment]
Label struct embeds Widget. So it's possible to convert values this way:
```go
lbl := gtk.Label{widg}
widg = lbl.Widget
```
I don't think it's necessary to write another exported function.

**Comment by yamnikov-oleg** [comment]
*Deleted last comment*
My bad, sorry.

**Comment by yamnikov-oleg** [comment]
I guess there is no proper way of converting gtk.Widget to particular classes currently. 

Best solution *IMO* is to export `wrapSmth(*glib.Object)` functions, renaming them to `SmthWrap(*glib.Object)`. Since every widget's object is available through `Object` field, casting would be possible.

If noone else comes up with something better, I will eventually get my hands on this issue.

**Comment by shsms** [comment]
Thanks Oleg,  I might not have enough understanding of the library yet,  and I can't really guess if it would have been very intuitive for me to discover a LabelWrap function if it was already there without having to gotk3's code.  But I guess that can be resolved with easily accessible documentation.  And this would be less code change than creating new functions like ToLabel(*gtk.Widget)

I will start with renaming just wrapLabel for my immediate use,  and if you give me a go-ahead,  I could do for the others as well and send a pull request.

**Comment by yamnikov-oleg** [comment]
The problem is that I'm new to this team and I don't have full understanding of the code either. So I don't feel myself authorized enough to give you green light about such a massive change: the owner of the repo might decline it.

We could wait for comment from @andre-hub.

**Comment by yamnikov-oleg** [comment]
Hey!
Your problem can be solved this way without modifying package code:
```go
w, _ := wnd.GetChild()
lbl := &gtk.Label{gtk.Widget{glib.InitiallyUnowned{w.Object}}}
```
