### ISSUE TITLE
[BUG] _Ctype_struct__GIcon can't be allocated in Go

### ISSUE THREAD

**Issue by nwg-piotr** [gotk3/gotk3#670]
**Describe the bug**
Yesterday I first tried to use gotk3, by just running [the example](https://github.com/gotk3/gotk3#example-usage) - and everything went well. Today it stopped working for some reason, and I tried to install gotk3 from scratch. It ends up in the error as below.

**To Reproduce**

```text
$ go get github.com/gotk3/gotk3/gtk
# github.com/gotk3/gotk3/gtk
go/src/github.com/gotk3/gotk3/gtk/gtk.go:5414:14: _Ctype_struct__GIcon can't be allocated in Go; it is incomplete (or unallocatable)
```

**Environment:**
gtk3 version: '3.24'
go version: 'go1.15.3 linux/amd64'
os: 'Arch Linux'
 
**Additional context**
Since yesterday: [2020-10-16T23:37:38+0200] [ALPM] upgraded go (2:1.15.2-1 -> 2:1.15.3-1)

Downgrading Go resolves the issue.

**Comment by hfmrow** [comment]
Hi,
fix added to pull request that solve your issue with go1.15.3

**Comment by nwg-piotr** [comment]
Hello,

I noticed. Thank you very much!

**Comment by shackra** [comment]
I'm also experiencing this bug:

```
../../../go/pkg/mod/github.com/gotk3/gotk3@v0.5.0/gtk/gtk.go:5369:14: _Ctype_struct__GIcon can't be allocated in Go; it is incomplete (or unallocatable)
```

Environment:
gtk3 version: '3.24.23'
go version: 'go version go1.15.3 linux/amd64'
os: 'Arch Linux'

**Comment by nwg-piotr** [comment]
I'm on Arch as well. We need to wait on 1.15.2 until the new gotk3 version is released.

**Comment by ugjka** [comment]
You can just pin master branch in your go.mod: go get foo@master

**Comment by nwg-piotr** [comment]
Sorry, I forgot to close. 0.5.1 works well.
