### ISSUE TITLE
Jobs failing on Travis-CI for Intel

### ISSUE THREAD

**Issue by kishorkunal-raj** [gotk3/gotk3#671]
Hi All,
I am running jobs on travis-ci and found that jobs are failing. Failures can be seen for go 1.13 on xenial, go 1.14 on bionic and go 1.9 & go.tip on focal. 
Below are the logs

LOG 1: AMD64 - Xenial - Go1.13
===================================================
Setting environment variables from .travis.yml
$ export GOARCH=amd64
4.71s$ travis_setup_go
go version go1.13 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.13.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version go1.13 linux/amd64
go.env
$ go env
before_install.1
0.00s$ export DISPLAY=:99.0
before_install.2
0.01s$ sudo /usr/bin/Xvfb $DISPLAY &> /dev/null &
before_install.3
0.01s$ export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
before_install.4
0.01s$ export Glib_VERSION=$(pkg-config --modversion glib-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.5
0.01s$ export GDK_Pixbuf_VERSION=$(pkg-config --modversion gdk-pixbuf-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.6
0.01s$ export Cairo_VERSION=$(pkg-config --modversion cairo)
before_install.7
0.01s$ export Pango_VERSION=$(pkg-config --modversion pango)
before_install.8
0.00s$ echo "GTK/GDK version ${GTK_VERSION} Glib/Gio version ${Glib_VERSION} Gdk-Pixbuf version ${GDK_Pixbuf_VERSION} (Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"
52.21s$ go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./...
# github.com/gotk3/gotk3/gtk
gtk/gtk.go:574:41: could not determine kind of name for C.GTK_INPUT_PURPOSE_TERMINAL
The command "go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./..." failed and exited with 2 during .
Your build has been stopped.

LOG 2: AMD64 - Bionic - Go1.14
===================================================
Setting environment variables from .travis.yml
$ export GOARCH=amd64
4.10s$ travis_setup_go
go version go1.14 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.14.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v10.16.0/bin:/home/travis/.kiex/elixirs/elixir-1.7.4/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.6.5/bin:/home/travis/.rvm/gems/ruby-2.6.5@global/bin:/home/travis/.rvm/rubies/ruby-2.6.5/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version go1.14 linux/amd64
go.env
$ go env
before_install.1
0.00s$ export DISPLAY=:99.0
before_install.2
0.00s$ sudo /usr/bin/Xvfb $DISPLAY &> /dev/null &
before_install.3
0.01s$ export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
before_install.4
0.01s$ export Glib_VERSION=$(pkg-config --modversion glib-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.5
0.01s$ export GDK_Pixbuf_VERSION=$(pkg-config --modversion gdk-pixbuf-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.6
0.01s$ export Cairo_VERSION=$(pkg-config --modversion cairo)
before_install.7
0.01s$ export Pango_VERSION=$(pkg-config --modversion pango)
before_install.8
0.00s$ echo "GTK/GDK version ${GTK_VERSION} Glib/Gio version ${Glib_VERSION} Gdk-Pixbuf version ${GDK_Pixbuf_VERSION} (Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"
123.23s$ go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./...
# github.com/gotk3/gotk3/gtk
gtk/gtk.go:574:41: could not determine kind of name for C.GTK_INPUT_PURPOSE_TERMINAL
The command "go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./..." failed and exited with 2 during .
Your build has been stopped.

LOG 3: AMD64 - Focal - Go1.9
===================================================
Setting environment variables from .travis.yml
$ export GOARCH=amd64
4.88s$ travis_setup_go
go version go1.9 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.9.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v10.16.0/bin:/home/travis/.kiex/elixirs/elixir-1.7.4/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.7.1/bin:/home/travis/.rvm/gems/ruby-2.7.1@global/bin:/home/travis/.rvm/rubies/ruby-2.7.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.16.8/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version go1.9 linux/amd64
go.env
$ go env
before_install.1
0.00s$ export DISPLAY=:99.0
before_install.2
0.01s$ sudo /usr/bin/Xvfb $DISPLAY &> /dev/null &
before_install.3
0.01s$ export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
before_install.4
0.01s$ export Glib_VERSION=$(pkg-config --modversion glib-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.5
0.01s$ export GDK_Pixbuf_VERSION=$(pkg-config --modversion gdk-pixbuf-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.6
0.01s$ export Cairo_VERSION=$(pkg-config --modversion cairo)
before_install.7
0.01s$ export Pango_VERSION=$(pkg-config --modversion pango)
before_install.8
0.00s$ echo "GTK/GDK version ${GTK_VERSION} Glib/Gio version ${Glib_VERSION} Gdk-Pixbuf version ${GDK_Pixbuf_VERSION} (Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"
21.89s$ go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./...
# github.com/gotk3/gotk3/glib
glib/gfile.go:118: cannot use c (type *C.char) as type *C.gchar in argument to goString
glib/gicon.go:95: cannot use (*C.char)(cstr) (type *C.char) as type *C.gchar in argument to func literal
The command "go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./..." failed and exited with 2 during .
Your build has been stopped.

LOG 4: AMD64 - Focal - Go.tip
===================================================
Setting environment variables from .travis.yml
$ export GOARCH=amd64
179.05s$ travis_setup_go
go version devel +9848e93cb7 Wed Oct 21 09:34:39 2020 +0000 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v10.16.0/bin:/home/travis/.kiex/elixirs/elixir-1.7.4/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.7.1/bin:/home/travis/.rvm/gems/ruby-2.7.1@global/bin:/home/travis/.rvm/rubies/ruby-2.7.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.16.8/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version devel +9848e93cb7 Wed Oct 21 09:34:39 2020 +0000 linux/amd64
go.env
$ go env
before_install.1
0.00s$ export DISPLAY=:99.0
before_install.2
0.00s$ sudo /usr/bin/Xvfb $DISPLAY &> /dev/null &
before_install.3
0.01s$ export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
before_install.4
0.01s$ export Glib_VERSION=$(pkg-config --modversion glib-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.5
0.01s$ export GDK_Pixbuf_VERSION=$(pkg-config --modversion gdk-pixbuf-2.0 | tr . _| cut -d '_' -f 1-2)
before_install.6
0.01s$ export Cairo_VERSION=$(pkg-config --modversion cairo)
before_install.7
0.01s$ export Pango_VERSION=$(pkg-config --modversion pango)
before_install.8
0.00s$ echo "GTK/GDK version ${GTK_VERSION} Glib/Gio version ${Glib_VERSION} Gdk-Pixbuf version ${GDK_Pixbuf_VERSION} (Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"
376.82s$ go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./...
# github.com/gotk3/gotk3/gtk
gtk/accel.go:264:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
gtk/accel.go:273:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
The command "go get -t -tags "gtk_${GTK_VERSION} glib_${Glib_VERSION} gdk_pixbuf_${GDK_Pixbuf_VERSION}" ./..." failed and exited with 2 during .
Your build has been stopped.

Please help me out to fix it.

**Comment by hfmrow** [comment]
Hi,
log 1 & 2:
C.GTK_INPUT_PURPOSE_TERMINAL is available since [GTK3.6](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkInputPurpose) gotk3 start at (3.12 and later). I don't know why this problem exist with travis.

log 3:
fixed in [PR](https://github.com/gotk3/gotk3/pull/669/commits/814fdc03006e342209ce1f8f83ae58d9c0e85306).

log 4: 
Ctype_struct__GtkAccelKey has no field or method accel_flags.
[GtkAccelKey](https://developer.gnome.org/gtk3/stable/gtk3-Keyboard-Accelerators.html#GtkAccelKey)
accel_flags exist ...

except for log 3 , is there a misconfiguration in travis ?

**Comment by kishorkunal-raj** [comment]
I am not sure about travis configuration at this point of time. Is there any specific configuration required for it?

**Comment by hfmrow** [comment]
Sorry, i haven't enough knowledge about travis to answer.
So if you want to use gtk3 to produce a GUI app, I'm sure it works with your distro (gtk> = 3.12), I've been using it for a long time and it works enough to make apps usable and user-friendly. even if travis say some unexplained behaviors.

**Comment by pekim** [comment]
This may not be generating the build tag names that you need. The `tr` will fail.
```
export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . | cut -d '' -f 1-2)
```

Looking at https://github.com/gotk3/gotk3/blob/master/.travis.yml, it should probably look more like this.
```
export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
```
That will set the var to something of the form `3_22`.

**Comment by hfmrow** [comment]
@pekim 
excellent. clap clap !
this may help our friend @kishorkunal-raj

**Comment by Infinoid** [comment]
> log 1 & 2:
> C.GTK_INPUT_PURPOSE_TERMINAL is available since [GTK3.6](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkInputPurpose) gotk3 start at (3.12 and later). I don't know why this problem exist with travis.

Not quite true.

GtkInputPurpose existed since 3.6.  INPUT_PURPOSE_TERMINAL was added sometime after 3.22.

https://gitlab.gnome.org/GNOME/gtk/-/blame/master/gtk/gtkenums.h#L816

libgtk-3-dev 3.22.30-1ubuntu4 (ubuntu bionic) does not have it.
libgtk-3-dev 3.24.23-2 (debian bullseye) has it.

Thus, I see this build error on ubuntu bionic but not debian bullseye.

**Comment by nojus297** [comment]
Hi, may I revive this?
 `INPUT_PURPOSE_TERMINAL` was introduced in gtk version`3.24.14`, and I have version `3.24.5` (debian buster), which means that it fails to build normally, but throws deprecation warnings if building with `3_22` tag.
Would you consider adding more specific build tags, or is it too tedious to keep up with all those versions?
