### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#674]
**Describe the bug**
gtk.ImageNewFromFile (and gtk.ImageNewFromPixbuf()) gives a fatal error. I have tried several different jpg:s and png:s.

**To Reproduce**
```
package main

import (
	"fmt"
	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	imagePath := "/home/per/temp/Best.png"
	image, err := gtk.ImageNewFromFile(imagePath)
	if err!=nil {
		panic(err)
	}
	fmt.Println(image.GetAllocation())
}
```

**Expected behavior**
No error message

**Error messages**
GOROOT=/usr/lib/go #gosetup
GOPATH=/home/per/go #gosetup
/usr/lib/go/bin/go build -o /home/per/code/test/test -gcflags all=-N -l . #gosetup
/var/lib/snapd/snap/goland/106/plugins/go/lib/dlv/linux/dlv --listen=0.0.0.0:41703 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /home/per/code/test/test --
API server listening at: [::]:41703

(process:90209): Gtk-CRITICAL **: 18:57:50.140: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:90209): Gtk-CRITICAL **: 18:57:50.142: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:90209): Gtk-CRITICAL **: 18:57:50.142: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fdbd1350c1c]

runtime stack:
runtime.throw(0x6cb5b9, 0x2a)
        /usr/lib/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:704 +0x269

goroutine 1 [syscall]:
runtime.cgocall(0x5b6ad0, 0xc00010ddf8, 0x1f99920)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00010ddc8 sp=0xc00010dd90 pc=0x47e03b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_image_new_from_pixbuf(0x1f99920, 0x0)
        _cgo_gotypes.go:14924 +0x4a fp=0xc00010ddf8 sp=0xc00010ddc8 pc=0x55908a
github.com/gotk3/gotk3/gtk.ImageNewFromPixbuf.func1(0xc000010038, 0x0)
        /home/per/go/pkg/mod/github.com/gotk3/gotk3@v0.5.1-0.20201028052159-952547abf55a/gtk/gtk.go:5281 +0x73 fp=0xc00010de40 sp=0xc00010ddf8 pc=0x577133
github.com/gotk3/gotk3/gtk.ImageNewFromPixbuf(0xc000010038, 0x0, 0x0, 0x0)
        /home/per/go/pkg/mod/github.com/gotk3/gotk3@v0.5.1-0.20201028052159-952547abf55a/gtk/gtk.go:5281 +0x45 fp=0xc00010de88 sp=0xc00010de40 pc=0x569d45
main.main()
        /home/per/code/test/main.go:15 +0x135 fp=0xc00010df88 sp=0xc00010de88 pc=0x585d35
runtime.main()
        /usr/lib/go/src/runtime/proc.go:204 +0x1cf fp=0xc00010dfe0 sp=0xc00010df88 pc=0x4b790f
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00010dfe8 sp=0xc00010dfe0 pc=0x4e9fe1

Debugger finished with exit code 0

**Environment:**
gtk3 version: 3.24.23-4
go version: 1.15.3
os: Manjaro (Cinnamon)

**Additional information**
Because of #670, I am currently running on the master branch instead of 0.5.0. Maybe this is my problem? Maybe I should not run on go 1.15.3, and then use the 0.5.0 (or older) release instead?

go.mod:
```
module test

go 1.15

require (
	github.com/gotk3/gotk3 v0.5.1-0.20201028052159-952547abf55a
)
```

**Comment by hfmrow** [comment]
I can't reproduce on Ubuntu focal ... sorry, that work for me.
i got &{{{-1 -1 1 1}}} from GetAllocation without error.
maybe someone on Manjaro could help you.

**Comment by Hultan** [comment]
Thanks, then I know that something is wrong on my machine. I am experimenting with using multiple Go versions now, so that I can use 1.14.x instead of 1.15.x that is on Manjaro right now, but I have not gotten it to work yet. Hopefully that will solve my problem.

**Comment by Hultan** [comment]
Now when I have changed to Go 1.14 and GoTK 0.4.0, I get a shorter error message, this is the ouput. To me, it looks like it is compiling against 1.14, and the mod file specifies to use GoTK 0.4.0, correct? So then I guess it must be a problem that is related to my machine or Manjaro, right?:

```
GOROOT=/home/per/go1.14.11 #gosetup
GOPATH=/home/per/go #gosetup
/home/per/go1.14.11/bin/go build -o /tmp/___test2 -gcflags all=-N -l . #gosetup
/var/lib/snapd/snap/goland/106/plugins/go/lib/dlv/linux/dlv --listen=0.0.0.0:33735 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /tmp/___test2 --
API server listening at: [::]:33735

(process:165363): Gtk-CRITICAL **: 08:11:03.655: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:165363): Gtk-CRITICAL **: 08:11:03.656: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:165363): Gtk-CRITICAL **: 08:11:03.656: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
fatal error: unexpected signal during runtime execution

Debugger finished with exit code 0
```

My go.mod file :

```
module github.com/hultan/test2

go 1.14

require github.com/gotk3/gotk3 v0.4.0

```

**Comment by hfmrow** [comment]
Have you tested in pure C to determine if issue come from gotk3 or not ?
So, i give you a piece of code in Go but using C, gotk3 is not used with it. This way, you will be able to know from where issue come.

Explanations:
```C
  GtkWidget *image=gtk_image_new_from_file (filename);			Load image from file
  GdkPixbuf *pixbuf=gtk_image_get_pixbuf (GTK_IMAGE(image));		Convert loaded image to pixbuf
  GtkWidget *image_pbuf=gtk_image_new_from_pixbuf (pixbuf);		Create image from pixbuf
  GdkPixbuf *pixbuf_img=gtk_image_get_pixbuf (GTK_IMAGE(image));	Convert created image to pixbuf
```
This covers your entire problem. `gtk.ImageNewFromFile (and gtk.ImageNewFromPixbuf()) gives a fatal error.`

```go
package main

/*

#cgo pkg-config: gdk-3.0 gobject-2.0 gtk+-3.0
#include <gtk/gtk.h>

gboolean draw_picture(GtkWidget *da, cairo_t *cr, gpointer data)
{
  gint width=gtk_widget_get_allocated_width(da);
  gint height=gtk_widget_get_allocated_height(da);

  GdkPixbuf *temp=gdk_pixbuf_scale_simple((GdkPixbuf*)data, width, height, GDK_INTERP_BILINEAR);
  gdk_cairo_set_source_pixbuf(cr, temp, 0, 0);
  cairo_paint(cr);

  g_object_unref(temp);
  return FALSE;
}

int launch(const char *filename)
{
  gtk_init(NULL, NULL);

  GtkWidget *window=gtk_window_new(GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title(GTK_WINDOW(window), "gdk_pixbuf_new_from_file");
  gtk_window_set_position(GTK_WINDOW(window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size(GTK_WINDOW(window), 400, 400);

  g_signal_connect(window, "destroy", G_CALLBACK(gtk_main_quit), NULL);

  //Needs a valid picture.
  GtkWidget *image=gtk_image_new_from_file (filename);
  GdkPixbuf *pixbuf=gtk_image_get_pixbuf (GTK_IMAGE(image));
  GtkWidget *image_pbuf=gtk_image_new_from_pixbuf (pixbuf);
  GdkPixbuf *pixbuf_img=gtk_image_get_pixbuf (GTK_IMAGE(image));

  GtkWidget *da1=gtk_drawing_area_new();
  gtk_widget_set_hexpand(da1, TRUE);
  gtk_widget_set_vexpand(da1, TRUE);
  g_signal_connect(da1, "draw", G_CALLBACK(draw_picture), pixbuf_img);

  GtkWidget *grid=gtk_grid_new();
  gtk_grid_attach(GTK_GRID(grid), da1, 0, 0, 1, 1);

  gtk_container_add(GTK_CONTAINER(window), grid);
  gtk_widget_show_all(window);

  gtk_main();

  g_object_unref(image);
  g_object_unref(pixbuf);
  g_object_unref(image_pbuf);
  g_object_unref(pixbuf_img);

  return 0;
}

*/
import "C"
import (
	"fmt"
	"unsafe"
)

func main() {
	cstr := C.CString("Library-48.png")
	defer C.free(unsafe.Pointer(cstr))
	C.launch(cstr)
}
```
Note: change "Library-48.png" with an image placed in the directory where you store this code.

**Comment by Hultan** [comment]
I unfortunately don't know how to compile c code. I tried to copy the code above into a file I called image.c, and then ran ```gcc image.c``` but that gives me errors. So I guess I am doing something wrong, or are missing some libraries or something.

Why is most of the code above commented out?

```
>gcc image.c
image.c:1:1: error: unknown type name ‘package’
    1 | package main
      | ^~~~~~~
image.c:60:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘import’
   60 | import "C"
      | ^~~~~~

```

**Comment by hfmrow** [comment]
It's a Go file, name it using "main.go" 
go build main.go

**Comment by Hultan** [comment]
Ah, now it compiles. I had to remove imports "fmt" though...No errors, and it opens a window. So what does that mean?

A lot of gtk errors though...

```
>./image

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.666: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.666: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.666: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.666: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GLib-GObject-CRITICAL **: 11:34:41.667: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:181258): Gtk-WARNING **: 11:34:41.667: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): Gtk-WARNING **: 11:34:41.667: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): Gtk-WARNING **: 11:34:41.667: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.783: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.783: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.783: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GdkPixbuf-CRITICAL **: 11:34:41.783: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:181258): GLib-GObject-CRITICAL **: 11:34:41.783: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:181258): Gtk-WARNING **: 11:34:41.783: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): Gtk-WARNING **: 11:34:41.783: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): Gtk-WARNING **: 11:34:41.783: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:181258): Gtk-WARNING **: 11:34:47.461: A floating object was finalized. This means that someone
called g_object_unref() on an object that had only a floating
reference; the initial floating reference is not owned by anyone
and must be removed with g_object_ref_sink().

(image:181258): GLib-GObject-CRITICAL **: 11:34:47.462: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:181258): Gtk-WARNING **: 11:34:47.462: A floating object was finalized. This means that someone
called g_object_unref() on an object that had only a floating
reference; the initial floating reference is not owned by anyone
and must be removed with g_object_ref_sink().

(image:181258): GLib-GObject-CRITICAL **: 11:34:47.462: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by hfmrow** [comment]
I've edited message before, maybe you have the 1st version ...
try to copy paste again

**Comment by Hultan** [comment]
I tried the new code, but the same result basically. How do we interpret this result though. Does it mean that the problem is on my machine?

```
./image

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.622: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.622: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.622: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.622: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GLib-GObject-CRITICAL **: 11:42:13.622: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:183201): Gtk-WARNING **: 11:42:13.622: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:13.622: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:13.622: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.739: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.739: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.739: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:13.739: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GLib-GObject-CRITICAL **: 11:42:13.739: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:183201): Gtk-WARNING **: 11:42:13.739: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:13.739: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:13.739: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): GdkPixbuf-CRITICAL **: 11:42:22.711: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:22.711: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:22.711: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:22.711: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GLib-GObject-CRITICAL **: 11:42:22.711: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:183201): Gtk-WARNING **: 11:42:22.711: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:22.711: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:22.711: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): GdkPixbuf-CRITICAL **: 11:42:25.494: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:25.494: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:25.494: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GdkPixbuf-CRITICAL **: 11:42:25.494: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(image:183201): GLib-GObject-CRITICAL **: 11:42:25.494: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(image:183201): Gtk-WARNING **: 11:42:25.494: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:25.494: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): Gtk-WARNING **: 11:42:25.494: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(image:183201): GLib-GObject-CRITICAL **: 11:42:37.020: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by Hultan** [comment]
No I screwed up, now it works, I get an image. Forgot to change the image path after i copied the code again...

**Comment by hfmrow** [comment]
lol
man
have you put YOUR image in the directory that hold your code ?

**Comment by Hultan** [comment]
See above, I forgot to change the image path after I copied the code. It works now...

How to interpret that though, is the problem my machine (ignore my incompetence for a while :-) )?

**Comment by hfmrow** [comment]
It's ok ^^ don't worry
So, look like your os is ok, cgo too, then i really don't know ...
this look like out of my competencies, the difference between you and me is Ubuntu/Manjaro ...
I think I can't help you anymore, hope someone can.
below my actual configuration:
| Name                                                       | Version / Info / Name                          |
| ---------------------------------------------------------- | ---------------------------------------------- |
| GOLANG                                                     | V1.15.4 -> GO111MODULE="off", GOPROXY="direct" |
| DISTRIB                                                    | LinuxMint Xfce                                 |
| VERSION                                                    | 20                                             |
| CODENAME                                                   | ulyana                                         |
| RELEASE                                                    | #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020    |
| UBUNTU_CODENAME                                            | focal                                          |
| KERNEL                                                     | 5.8.0-25-generic                               |
| HDWPLATFORM                                                | x86_64                                         |
| GTK+ 3                                                     | 3.24.20                                        |
| GLIB 2                                                     | 2.64.3                                         |
| CAIRO                                                      | 1.16.0                                         |
| [GtkSourceView](https://github.com/hfmrow/gotk3_gtksource) | 4.6.0                                          |
| [LiteIDE](https://github.com/visualfc/liteide)             | 37.3 qt5.x                                     |
| Qt5                                                        | 5.12.8 in /usr/lib/x86_64-linux-gnu            |

**Comment by Hultan** [comment]
Ok, thanks for your help. It is not a super important project anyway, so I'll just wait and pick it up later, hoping that the problem will magically solve itself somehow :-)

**Comment by Hultan** [comment]
@hfmrow : 

@moson from the Manjaro forum pointed out that I had forgot the gtk.Init(nil)! That was the answer, so sorry for wasting your time with such a newbie mistake :-(

**Comment by hfmrow** [comment]
ahh yes, I should have seen it, indeed, when I tested the code, I integrated it into my test matrix which already contains the windows initialization elements, I did not pay attention to it .. .
