### ISSUE TITLE
compiling webloop's example fails

### ISSUE THREAD

**Issue by maerlyn** [gotk3/gotk3#68]
I'm trying to compile the example of sourcegraph/webloop (https://github.com/sourcegraph/webloop/blob/master/examples/angular-static-seo/server.go), which has gotk3 as a dependency. I'm running into the following errors, that seem to be gotk3-related:

```
$ go build -tags gtk_3_10 server.go 
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-659884296/000009.o: In function `removeClosure':
/tmp/go-build971982688/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:10: multiple definition of `removeClosure'
/tmp/go-link-659884296/000001.o:/tmp/go-build781173935/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:10: first defined here
/tmp/go-link-659884296/000009.o: In function `goMarshal':
/tmp/go-build971982688/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:23: multiple definition of `goMarshal'
/tmp/go-link-659884296/000001.o:/tmp/go-build781173935/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:23: first defined here
collect2: error: ld returned 1 exit status
```

My OS is ubuntu 14.04.

**Comment by andre-hub** [comment]
the error say, you have a multiple definition
i thinks this is the problem with the file https://github.com/sourcegraph/go-webkit2/blob/master/cmd/webkit-eval-js/evaljs.go#L12

the webloop project mixed many libs, clone the project and clean the files and test again.

**Comment by andre-hub** [comment]
i have change the import from "github.com/conformal/gotk3/glib" to gotk3 

'go run server.go'

> Launching two HTTP servers serving equivalent content:
> 
> 	Dynamic AngularJS app:     http://localhost:9090
> 	Statically rendered site:  http://localhost:9091
> 
> T>ry browsing to both and comparing them. View the HTML source of the
> static site to confirm that the page is, indeed, static HTML.
> 
> 2016/01/23 21:35:54 static: Listening on :9091
> 2016/01/23 21:35:54 app: Listening on :9090

on debian 8.2 and go 1.3
