### ISSUE TITLE
[Project question] libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#683]
I was hoping that someone here could point me in the right direction about this issue. I am building an application, using gotk3, on Manjaro using go 1.14, and it works perfectly on Manjaro. 

However, when I move the executable to a Linux Mint machine, it outputs:

```./softtube: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./softtube)```

This did not use to be an issue, the application worked fine on Linux Mint before, so I can only assume that is because Manjaro have moved to a newer GTK version. Because of this problem I have understood that go:s executables are not always completely independent (if you are using certain packages, like ```net``` and maybe others). And I believe that the ```net``` package is using GLIB, and on my Mint-machine I have version 2.27 of GLIB (at least that is what I understand from looking around in Synaptic Package Manager).

I see four solutions to this (listed in the order of what I would prefer):
1. **Make sure that the executable is not dependent on any libraries.** I believe this involves disabling CGO? Can a GoTK3 application even be compiled that way, to be completely independent of which GTK version is installled on the target machine?
2. **Make sure that the compiler compiles against a specific (older) version of GLIB (2.27).** How do I do this? Will this version then work on my Manjaro machine? I am guessing not, but compiling two version should be easy enough.
3. **Setup a Linux Mint developing virtual machine, then compile the application twice**. On Manjaro for 2.32-version and on Linux Mint for 2.27-version.
4. **Upgrade the GLIB version on my Linux Mint-machine to a newer version (2.32).** I don't like this "solution" because that means that I would have to keep updating the Mint-machine, every time my main machine updates, which might happen a lot since Manjaro is a rolling release distribution.

I understand that this question is more of a support question, that only just touches GoTK3, but you have been awesome and very helpful here before, so I am asking the question here. I also understand that my knowledge of GTK/GLIB is very limited so there is a chance that I make no sense at all, I am not even sure if GTK and GLIB are related :-) Let me know if it doesn't belong here, and I will close the issue.

**Comment by hfmrow** [comment]
Hi,
Glibc is GNU C Library, the implementation of Standard C library. Used in cgo every time a linux native functionality is required.
In your case, step 3 look like good idea, on the other way, you can try step 2 : https://stackoverflow.com/questions/55450061/go-build-with-another-glibc
Haven't tested it, it's the first topic that relate this i have found using google.
I don't think this Glibc version issue is a Gotk3 issue

**Comment by Hultan** [comment]
Thanks for your input, I think I will go with step 3 then. It seems easier, for a newbie go programmer as myself, than the solution for step 2 that you linked to.

**Comment by Hultan** [comment]
I just created a VM, an installed LM + Go and compiled, and those executables worked fine! Thanks for your help...

**Comment by hfmrow** [comment]
Perfect.
I thought of another solution to this kind of problem (lib versions).
For go development I have been using 'LiteIde' (built in 'C') for a long time and saw its folder tree which uses a 'lib/' directory, inside I can find all the extra libraries (compiled version '.so') used that work with the deployed version. I wonder if there is not the possibility of doing the same thing with a program in Go.
