### ISSUE TITLE
[BUG] MessageDialog | Fatal IO error

### ISSUE THREAD

**Issue by raifpy** [gotk3/gotk3#686]
**Describe the bug**
When i was try gtk.MessageDialogNew with my win object (*gtk.Window);
Gdk-Message: 22:32:27.937: main: Fatal IO error 0 (Success) on X server :0.

**Expected behavior**
MessageDialogNew getting error when win added any object *

**Error messages**
Gdk-Message: 22:40:12.289: <binName>: Fatal IO error 2 (No such or ordinary) on X server :0.
//
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
main: xcb_io.c:260: poll_for_event: Sav `!xcb_xlib_threads_sequence_lost' not successful.

**Environment:**
gtk3 version: 'gtk3-3.24.23-1.fc33.x86_64'
go version: 'go version go1.15.6 linux/amd64'
os: 'Fedora Linux (i3)'
 
**Additional context**

**Example Code**

```
package main

import (
	"fmt"
	"time"

	"github.com/gotk3/gotk3/gtk"
)

func main() {
	gtk.Init(nil)

	win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	fmt.Println("first dialog start")
	waitDialog(win) // there is no problem here
	fmt.Println("first dialog end")

	label, _ := gtk.LabelNew("Label")
	win.Add(label) // problem here

	go func() {
		time.Sleep(time.Second * 3)
		fmt.Println("second dialog start")
		waitDialog(win) // problem here
		fmt.Println("second dialog end")
	}()

	win.ShowAll()
	gtk.Main()
}
func waitDialog(win *gtk.Window) {
	dialog := gtk.MessageDialogNew(win, gtk.DIALOG_DESTROY_WITH_PARENT, gtk.MESSAGE_INFO, gtk.BUTTONS_OK, "Test")
	dialog.Connect("response", dialog.Destroy)
	dialog.Run() //
}
```

![gtkError](https://user-images.githubusercontent.com/50047969/102264918-5ce94d00-3f27-11eb-876c-2d1bebb2b9d9.gif)

**Comment by pekim** [comment]
In your go routine you're making gtk api calls while not on the main thread. That's dangerous.
You should use https://pkg.go.dev/github.com/gotk3/gotk3/glib#IdleAdd .

Something along these would be safer.
```go
	go func() {
		time.Sleep(time.Second * 3)

		glib.IdleAdd(func() bool {
			fmt.Println("second dialog start")
			waitDialog(win) // problem here
			fmt.Println("second dialog end")

			return false
		})
	}()
```

**Comment by raifpy** [comment]
> In your go routine you're making gtk api calls while not on the main thread. That's dangerous.
> You should use https://pkg.go.dev/github.com/gotk3/gotk3/glib#IdleAdd .
> 
> Something along these would be safer.
> 
> ```go
> 	go func() {
> 		time.Sleep(time.Second * 3)
> 
> 		glib.IdleAdd(func() bool {
> 			fmt.Println("second dialog start")
> 			waitDialog(win) // problem here
> 			fmt.Println("second dialog end")
> 
> 			return false
> 		})
> 	}()
> ```

Thanks, solved..
