### ISSUE TITLE
[Project question] Method to Limit gtk.Entry values 

### ISSUE THREAD

**Issue by kampsy** [gotk3/gotk3#713]
gtk.Entey accepts textual data. Is there a way to limit this to numerical values only.  Eg gtk.Entry.SetNumeric(true)

**Comment by hfmrow** [comment]
You have:
[gtk\_entry\_set\_input\_purpose](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-input-purpose)
or 
[input-purpose](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--input-purpose)
but does not work actually ...
you can handle it manually with signal : [preedit-changed](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry-preedit-changed)

**Comment by kampsy** [comment]
Thanks i found your examples very helpful. I ended up using a gtk.SpinButton. v0.5.2 has the gtk.SpinButton.SetNumeric() method.

**Comment by kampsy** [comment]
> You have:
> [gtk\_entry\_set\_input\_purpose](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-input-purpose)
> or 
> [input-purpose](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--input-purpose) property.
> 
> but unfortunately, it does not work actually ...
> you can handle it manually with signal : [preedit-changed](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry-preedit-changed)
> 
> there is some times, i've made an example it may help you: [on 11 Oct 2020](https://github.com/gotk3/gotk3/issues/668#issuecomment-706636167)
> this one uses "inserted-text" signal from de TextBuffer to intercept and change entered values.

Thanks i found your examples very helpful. I ended up using a gtk.SpinButton. v0.5.2 has the gtk.SpinButton.SetNumeric() method.
