### ISSUE TITLE
get css error

### ISSUE THREAD

**Issue by yuancpfive** [gotk3/gotk3#714]
**Describe the bug**
I'm trying to use css to modify the theme , and the code like this, but get error...
this is the code :
`global.Log.Debug("{main}[loadCss] start....")
    provider, err := gtk.CssProviderNew()
    if err != nil {
    global.Log.Error("{main}[loadCss] gtk.CssProviderNew error ", zap.Error(err))
    return
}

err = provider.LoadFromPath("css/gtk-normal.css")
if err != nil {
global.Log.Error("{main}[loadCss] LoadFromPath error", zap.Error(err))
return
}
screen, err := gdk.ScreenGetDefault()
if err != nil {
global.Log.Error("{main}[loadCss] gdk.ScreenGetDefault error", zap.Error(err))
return
}
gtk.AddProviderForScreen(screen, provider, gtk.STYLE_PROVIDER_PRIORITY_USER)`

**Error messages**
`gdk.ScreenGetDefault error {"error": "cgo returned unexpected nil pointer"}`

**Environment:**
gtk3 version: ''
go version: '1.13.4'
os: 'ubuntu kylin'

**Comment by hfmrow** [comment]
'main.go' file:
``` go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

var win *gtk.Window
var box *gtk.Box
var btn *gtk.Button

// examle:
func example() {
	// noop
}

// btnClicked: Callback "clicked" button' signal
func btnClicked(b *gtk.Button) {
	// noop
}

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")
	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {
	var err error
	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func(w *gtk.Window) {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatal("Unable to create box:", err)
	}
	btn, err = gtk.ButtonNew()
	if err != nil {
		log.Fatal("Unable to create button:", err)
	}

	btn.Connect("clicked", btnClicked)
	btn.SetLabel("Click it")

	box.Add(btn)
	win.Add(box)

	err = CssApply("test.css")
	if err != nil {
		log.Fatal("Unable to CssApply:", err)
	}

	win.ShowAll()
	return win
}

func CssApply(filename string) (err error) {

	var (
		cssProv *gtk.CssProvider
		screen  *gdk.Screen
	)

	if cssProv, err = gtk.CssProviderNew(); err == nil {
		if err = cssProv.LoadFromPath(filename); err == nil {
			if screen, err = gdk.ScreenGetDefault(); err == nil {
				gtk.AddProviderForScreen(screen, cssProv, gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
			}
		}
	}
	return
}

```
'test.css' file:
``` css
window * {
    color: red;
    background-color: yellow;
}
```

**Comment by yuancpfive** [comment]
@hfmrow thanks a lot, it seems that my codes in the wrong place, but not bug

**Comment by hfmrow** [comment]
If you want to learn how to create a css file, you need to understand how Css works, this language is not specific to Gtk3, it is also used for html pages and others ...

My references on this subject:

- [GTK+ CSS Overview: GTK+ 3 Reference Manual](https://developer.gnome.org/gtk3/stable/chap-css-overview.html)
- [GTK+ CSS Properties: GTK+ 3 Reference Manual](https://developer.gnome.org/gtk3/stable/chap-css-properties.html)
- [Using the CSS file format: GTK+ 3 Reference Manual](https://developer.gnome.org/gtk3/stable/gtk-migrating-GtkStyleContext-css.html)

There is a lot of explanations over internet, this list is not restrictive.

There is nothing in gotk3 examples directory because it's not really hard to apply a css file or string to a specific window and his childs.

To help you more, you can use [GTK Inspector](https://wiki.gnome.org/Projects/GTK/Inspector) to modify css in real time and much more (object names for example).

hope this help.

**Comment by yuancpfive** [comment]
@hfmrow Words cannot express how thankful I am.
there are still something wrong disturb me. I theme the style by css , but it is not work.
css file :
`#GtkLayout
{
    background-color: #333;
}

#window
{
    background-color: hotpink;
}

#gtk_btn_login
{
    color: red;
    background-color: coral;
    border: 2px solid yellowgreen;
    font-size: 21pt;
}

.gtk_btn_login
{
    color: blueviolet;
    background-color: yellow;
    border: 2px solid black;
    font-size: 21pt;
}

gtk_btn_login
{
    color: blueviolet;
    background-color: yellow;
    border: 2px solid black;
    font-size: 21pt;
}

#gtk_entry_accout {
    color: yellowgreen;
    font-size: 25pt;
}

/*button, label{*/
/*    color: blue;*/
/*    background: purple;*/
/*    font-size: 21pt;*/
/*}*/`

this is my layout:
`<?xml version="1.0" encoding="UTF-8"?>

<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkApplicationWindow" id="window">
    <property name="can_focus">False</property>



    <child>
      <object class="GtkFixed" id="gtk_fixed_layout">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <child>
          <object class="GtkLayout">
            <property name="width_request">983</property>
            <property name="height_request">151</property>
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <child>
              <object class="GtkButton" id="gtk_btn_net_config">
                <property name="label" translatable="yes">网络配置</property>
                <property name="width_request">119</property>
                <property name="height_request">61</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="focus_on_click">False</property>
                <property name="receives_default">True</property>
              </object>
              <packing>
                <property name="x">810</property>
                <property name="y">71</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="y">436</property>
          </packing>
        </child>
        <child>
          <object class="GtkLayout">
            <property name="width_request">983</property>
            <property name="height_request">100</property>
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="height">200</property>
            <child>
              <object class="GtkLabel">
                <property name="width_request">100</property>
                <property name="height_request">100</property>
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="has_tooltip">True</property>
                <property name="label" translatable="yes">账号：</property>
                <property name="single_line_mode">True</property>
              </object>
              <packing>
                <property name="x">112</property>
              </packing>
            </child>
            <child>
              <object class="GtkEntry" id="gtk_entry_accout">
                <property name="width_request">642</property>
                <property name="height_request">40</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="max_length">50</property>
                <property name="text" translatable="yes">请输入账号</property>
                <property name="truncate_multiline">True</property>
                <property name="input_hints">GTK_INPUT_HINT_SPELLCHECK | GTK_INPUT_HINT_NO_SPELLCHECK | GTK_INPUT_HINT_NONE</property>
              </object>
              <packing>
                <property name="x">191</property>
                <property name="y">31</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="y">96</property>
          </packing>
        </child>
        <child>
          <object class="GtkLayout">
            <property name="width_request">983</property>
            <property name="height_request">100</property>
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="height">200</property>
            <child>
              <object class="GtkLabel">
                <property name="width_request">100</property>
                <property name="height_request">100</property>
                <property name="visible">True</property>
                <property name="can_focus">False</property>
                <property name="label" translatable="yes">密码：</property>
                <property name="single_line_mode">True</property>
              </object>
              <packing>
                <property name="x">112</property>
              </packing>
            </child>
            <child>
              <object class="GtkEntry" id="gtk_entry_password">
                <property name="width_request">642</property>
                <property name="height_request">40</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="max_length">25</property>
                <property name="visibility">False</property>
                <property name="invisible_char">●</property>
              </object>
              <packing>
                <property name="x">191</property>
                <property name="y">31</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="y">203</property>
          </packing>
        </child>
        <child>
          <object class="GtkLayout">
            <property name="width_request">983</property>
            <property name="height_request">56</property>
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <child>
              <object class="GtkButton" id="gtk_btn_login">
                <property name="label" translatable="yes">登录</property>
                <property name="width_request">100</property>
                <property name="height_request">49</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="focus_on_click">False</property>
                <property name="receives_default">True</property>
                <property name="relief">none</property>
                <property name="use_underline">True</property>
              </object>
              <packing>
                <property name="x">452</property>
                <property name="y">6</property>
              </packing>
            </child>
          </object>
          <packing>
            <property name="y">377</property>
          </packing>
        </child>
      </object>
    </child>
  </object>
</interface>
`

no widget work by this css style, I try a lot of methods to work it ,but nothing change

**Comment by yuancpfive** [comment]
@hfmrow Words cannot express how thankful I am.

there are still something wrong disturb me. I theme the widget style by css , but it is not work.

css file:
`#GtkLayout
{
background-color: #333;
}

#window
{
background-color: hotpink;
}

#gtk_btn_login
{
color: red;
background-color: coral;
border: 2px solid yellowgreen;
font-size: 21pt;
}

.gtk_btn_login
{
color: blueviolet;
background-color: yellow;
border: 2px solid black;
font-size: 21pt;
}

gtk_btn_login
{
color: blueviolet;
background-color: yellow;
border: 2px solid black;
font-size: 21pt;
}

#gtk_entry_accout {
color: yellowgreen;
font-size: 25pt;
}

/button, label{/
/* color: blue;/
/ background: purple;/
/ font-size: 21pt;/
/}*/`

**Comment by hfmrow** [comment]
A sharp `#` is used only when the object have a name defined with `gtk.Object.SetName("winName")`

```css
#winName {
    color: blue;
    background-color: red;
}
```

If you want to apply to all windows (descendants of the main window)

```css
window {
    color: blue;
    background-color: red;
}
```

For your `gtk_btn_login` , be sure it is named 'gtk_btn_login' using `.SetName` method and add a `#` at start.

```css
#gtk_btn_login {
    color: blueviolet;
    background-color: yellow;
    border: 2px solid black;
    font-size: 21pt;
} 
```

Real life example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.2 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkWindow" id="Window">
    <property name="name">WindowNamedForCss</property>
    <property name="can_focus">False</property>
    <child type="titlebar">
      <placeholder/>
    </child>
    <child>
      <object class="GtkButton" id="Button">
        <property name="label" translatable="yes">button</property>
        <property name="name">ButtonNamedForCss</property>
        <property name="visible">True</property>
        <property name="can_focus">True</property>
        <property name="receives_default">True</property>
      </object>
    </child>
  </object>
</interface>
```

Css will be:

```css
#WindowNamedForCss {
    background-color: hotpink;
}

#ButtonNamedForCss {
    color: blueviolet;
    background-color: yellow;
    border: 2px solid black;
    font-size: 21pt;
} 
```

**Comment by yuancpfive** [comment]
@hfmrow oh, I thing I find the mistake, I don't write this 
`<property name="name">gtk_btn_login</property>`
in the css, but how do you know should add property? I have read a lot of articles, but no one metion this property, would you please tell me why do you know this ? thanks.

**Comment by hfmrow** [comment]
## Object Hierarchy For [GtkWindow](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindow.object-hierarchy)

```
GObject
╰── GInitiallyUnowned
    ╰── [GtkWidget](https://developer.gnome.org/gtk3/stable/GtkWidget.html "GtkWidget")
        ╰── [GtkContainer](https://developer.gnome.org/gtk3/stable/GtkContainer.html "GtkContainer")
            ╰── [GtkBin](https://developer.gnome.org/gtk3/stable/GtkBin.html "GtkBin")
                ╰── GtkWindow
                    ├── [GtkDialog](https://developer.gnome.org/gtk3/stable/GtkDialog.html "GtkDialog")
                    ├── [GtkApplicationWindow](https://developer.gnome.org/gtk3/stable/GtkApplicationWindow.html "GtkApplicationWindow")
                    ├── [GtkAssistant](https://developer.gnome.org/gtk3/stable/GtkAssistant.html "GtkAssistant")
                    ├── [GtkOffscreenWindow](https://developer.gnome.org/gtk3/stable/GtkOffscreenWindow.html "GtkOffscreenWindow")
                    ├── [GtkPlug](https://developer.gnome.org/gtk3/stable/GtkPlug.html "GtkPlug")
                    ╰── [GtkShortcutsWindow](https://developer.gnome.org/gtk3/stable/GtkShortcutsWindow.html "GtkShortcutsWindow")
```

[GtkWindow](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindow.object-hierarchy) is a descendant of [GtkWidget](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget.properties), so it receives its properties

**Comment by yuancpfive** [comment]
@hfmrow thank you very much!!!

**Comment by yuancpfive** [comment]
@hfmrow I am sorry to bother you again.
would you please tell me how to construct own widgets? they may be a collection of basic widget, or a newly drawn widget.
please give me some suggestion or website.

**Comment by hfmrow** [comment]
There is the hard-coding *(1)* way and soft version *(2)*

1. A good way to start is to understand how gotk3 wrap a glib.Object inside a gtk.Entry (or others) for example. And, learn how to reproduce it. Some references in `C` language: [CustomWidgets](https://wiki.gnome.org/HowDoI/CustomWidgets) may give you an overview on how construct work and the required methods to comply with gtk3 standard, the heritage from parent (methods, properties, signals) and much much more.
2. Another more accessible way is to get an existing one and get its `*.GetContentArea`, `*.Container`, `*.Bin` container. This way it is easy to add a GtkBox and / or GtkGrid and fill it as you wish with some other existing widgets (Button, Pixbuf, Entry ...) you can put everything in a structure that can handle specific methods and other things related to those objects and the goal you want to achieve.

**Comment by yuancpfive** [comment]
@hfmrow 
from your suggestion, it seems that  construct a basic widgets collection is more easyer than construct a newly drawn widget. 

it  will be much easier to use container to wrap basic widgets to form new controller, but if this way does not work, such as make a scale dial widget,  can not construct from basic widget, we only use the hard-coding way,  not only need to use go language, but also need to be constructed in c language,  is my understanding correct?
