### ISSUE TITLE
[Project question] Problem with compiling on Windows

### ISSUE THREAD

**Issue by gitchander** [gotk3/gotk3#725]
I made the official GTK instructions for Windows and I have next problem:

$ go build
# pkg-config --cflags  -- gio-2.0 glib-2.0 gobject-2.0 gio-2.0 glib-2.0 gobject-2.0 gio-2.0
pkg-config: exec: "pkg-config": executable file not found in %PATH%

Please Help!

**Comment by 13rac1** [comment]
You need to install pkg-config, there are multiple options: https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows

**Comment by gitchander** [comment]
Thanks! I try it later.
