### ISSUE TITLE
[BUG] cannot get lib

### ISSUE THREAD

**Issue by Out-Of-Mind** [gotk3/gotk3#749]
**What bug is**
When I try to go get `github.com/gotk3/gotk3/...` I get this error:
`# github.com/gotk3/gotk3/glib`
`go/src/github.com/gotk3/gotk3/glib/glib.go:236:3: expected '}', found 'case'`
`go/src/github.com/gotk3/gotk3/glib/glib.go:269:2: expected declaration, found rv`

**Expected behavior**
Just downloaded gotk3 lib

**Environment:**
gtk3 version: '3'
go version: 'go version go1.15.8 linux/amd64'
os: 'openSUSE 15.2 leap'

**Comment by mellowmoxy** [comment]
I am having this same issue. 

Environment:
gtk3 version: '3'
go version: go1.16 linux/amd64
os: Arch Linux

**Comment by MrWaggel** [comment]
https://github.com/gotk3/gotk3/commit/63e33a17ee03a8358612dc0ed47635d747d852d0#diff-1e0da5718d3bd17989bc25af80f912afe7e5b40cc689bcea0a9ae7efb9145b24 seems to be the problem.

Had the same issue, using a version prior to this commit works.

**Comment by rubiojr** [comment]
https://github.com/gotk3/gotk3/pull/750 fixed this, I think.
