### ISSUE TITLE
[Project question] title

### ISSUE THREAD

**Issue by hfmrow** [gotk3/gotk3#751]
Hi @diamondburned
I have to use  'user_data' in 'connect' callback function, but now, i don't know how to do this since last api modifications.
1st  thinking coming to me is to try like defined in Gtk documentation
```c
user_function (GtkButton *button,
               gpointer   user_data)
```
```go
button.Connect("clicked", func(b *gtk.Button, arg interface{}) {
        fmt.Println(arg.(string))
})
```
but no way. 

I'm sure I'm missing something, can you explain how to make "user_data" available through the "connect" callback function as before. Thank you.

**Comment by diamondburned** [comment]
You can't use `user_data` anymore. The latest change requires `user_data` for the callback ID.

If `arg` is an existing Go variable, then you can write a regular Go closure:

```go
arg := "argument 10"

button.Connect("clicked", func() {
    fmt.Println("button clicked, arg:", arg)
})
```

**Comment by hfmrow** [comment]
Sad news for me, thanks for fast answer.
(lot of code to change ...)
