### ISSUE TITLE
go build problem

### ISSUE THREAD

**Issue by gitchander** [gotk3/gotk3#752]
I have next problem:
$ go build
# github.com/gotk3/gotk3/gtk
../../../../pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/accel.go:264:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../../../../pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/accel.go:273:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)

**Comment by yktoo** [comment]
Duplicate of #726

**Comment by gitchander** [comment]
Thanks for help!
