### ISSUE TITLE
Regression in version v0.5.2

### ISSUE THREAD

**Issue by sunshine69** [gotk3/gotk3#759]
**Describe the bug**
Build error 

**To Reproduce**
With version v0.5.2 my project (https://github.com/sunshine69/gnote) build error with messages

```
go build --tags "json1 fts5 secure_delete" -ldflags='-s -w' -o gnote
 github.com/sunshine69/gnote/forms
forms/gnoteapp.go:36:18: model.GetIter undefined (type gtk.ITreeModel has no field or method GetIter)
forms/gnoteapp.go:37:16: model.GetValue undefined (type gtk.ITreeModel has no field or method GetValue)
forms/note-pad.go:322:22: undefined: gdk.GDK_CONTROL_MASK
forms/note-search.go:167:22: undefined: gdk.GDK_CONTROL_MASK
```

**Expected behavior**
Build passed the same as old version  v0.4.0

**Error messages**

**Environment:**
gtk3 version: '
```
rpm -qa|grep gtk3
gtk3-3.24.27-1.fc33.x86_64
gtk3-devel-3.24.27-1.fc33.x86_64
```
go version: 
```
go version
go version go1.15.10 linux/amd64
```
os: 'Fedora 33 and test with Ubuntu20 same outcome'

 
**Additional context**

**Comment by hfmrow** [comment]
hi,
- ITreeModel is an interface to hold TreeModel.
gtk.ITreeModel.ToTreeModel().GetIter/GetValue work better ....

- try 'gdk.CONTROL_MASK'
instead of 'gdk.GDK_CONTROL_MASK'

**Comment by sunshine69** [comment]
Great! Thanks it works for me.
