### ISSUE TITLE
How do I change the font size of the label

### ISSUE THREAD

**Issue by 2407383500** [gotk3/gotk3#766]
I need to change the label_text fontsize, but I don't know how to implement it......

**Comment by hfmrow** [comment]
Hi,
Recommendation are to use CSS style
```go
css:=`
entry {
	color: blue;
	font-size: 24px;
}
`
```

**Comment by 2407383500** [comment]
> Hi,
> Recommendation are to use CSS style
> 
> ```go
> css:=`
> label {
> 	color: blue;
> 	font-size: 24px;
> }
> `
> ```

Thank you very much. I'll try it right away
