### ISSUE TITLE
How do I close `glib.TimeoutAdd`

### ISSUE THREAD

**Issue by 2407383500** [gotk3/gotk3#767]
Can someone help me please

**Comment by hfmrow** [comment]
Hi,
`The function is called repeatedly until it returns FALSE,`
Ref: [g_timeout_add ()](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add)

**Comment by 2407383500** [comment]
> Hi,
> `The function is called repeatedly until it returns FALSE,`
> Ref: [g_timeout_add ()](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add)

thankyou very much! I know how to fix my program!
