### ISSUE TITLE
[Feature]How do I change GtkComboBox's widget style?

### ISSUE THREAD

**Issue by yuancpfive** [gotk3/gotk3#768]
I make a window with GtkComboBox in gtk_3_18, and it show correcttly, but now I  want to change it style, like change arrow color to red, or change background to red, and it can't work.  

How do I write css file and how to attach to the GtkComboBox ?

My environment is gtk-3.18, ubuntu.

**Comment by hfmrow** [comment]
Hi,
im late, sorry.
```go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

var (
	win *gtk.Window
	cbx *gtk.ComboBox
	box *gtk.Box
)

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")
	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {

	var err error

	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatalf("Unable to create window: %v\n", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func(w *gtk.Window) {
		gtk.MainQuit()
	})

	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatalf("Unable to create box: %v\n", err)
	}

	cbx, err = gtk.ComboBoxNew()
	if err != nil {
		log.Fatalf("Unable to create button: %v\n", err)
	}
	/*****************************************************************/
	cssProv, err := gtk.CssProviderNew()
	if err != nil {
		log.Fatalf("Unable to init css provider: %v\n", err)
	}

	var css = `
combobox arrow {
	color: red;
	background-color: blue;
}
`
	err = cssProv.LoadFromData(css)
	if err != nil {
		log.Fatalf("Unable to read css data: %v\n", err)
	}

	screen, err := gdk.ScreenGetDefault()
	if err != nil {
		log.Fatalf("Unable to get screen: %v\n", err)
	}

	gtk.AddProviderForScreen(screen, cssProv, gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
	/*****************************************************************/

	box.Add(cbx)
	win.Add(box)
	win.ShowAll()
	return win
}

```
hope this could help.
![1](https://user-images.githubusercontent.com/45952208/115715473-74728f80-a378-11eb-9264-327e4a315bf2.png)

**Comment by yuancpfive** [comment]
wow, I am very happy that you can give me the answer, thank you very much .
It seems that the key codes is `gtk.AddProviderForScreen`, it will change all the widgets that meet the conditions?

 is there any others method to change GtkComboBox's widget style?
such as widget.AddProvider? to add CssProvider in a widget.

thanks agains for your answer.

**Comment by hfmrow** [comment]
```go
// This means that all GtkComboBox (children of main windows) will receive this directive
	var css = `
combobox arrow {
	color: red;
	background-color: blue;
}
`
```
if you wish to send to a specific widget, you have to name it using GtkWidget.SetName method and add a '#' just before the name in the css declaration to specify that is a named object.
```go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

var (
	win *gtk.Window
	cbx,
	cbx1 *gtk.ComboBox
	box *gtk.Box
)

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")
	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {

	var err error

	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatalf("Unable to create window: %v\n", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func(w *gtk.Window) {
		gtk.MainQuit()
	})

	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatalf("Unable to create box: %v\n", err)
	}

	cbx, err = gtk.ComboBoxNew()
	if err != nil {
		log.Fatalf("Unable to create button: %v\n", err)
	}
	cbx1, err = gtk.ComboBoxNew()
	if err != nil {
		log.Fatalf("Unable to create button: %v\n", err)
	}
	/*****************************************************************/
	cbx.SetName("onlyMe")

	cssProv, err := gtk.CssProviderNew()
	if err != nil {
		log.Fatalf("Unable to init css provider: %v\n", err)
	}

	var css = `
#onlyMe arrow {
	color: red;
	background-color: blue;
}
`
	err = cssProv.LoadFromData(css)
	if err != nil {
		log.Fatalf("Unable to read css data: %v\n", err)
	}

	screen, err := gdk.ScreenGetDefault()
	if err != nil {
		log.Fatalf("Unable to get screen: %v\n", err)
	}

	gtk.AddProviderForScreen(screen, cssProv, gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
	/*****************************************************************/

	box.Add(cbx)
	box.Add(cbx1)
	win.Add(box)
	win.ShowAll()
	return win
}

```

**Comment by yuancpfive** [comment]
thanks agains for your answer!

**Comment by yuancpfive** [comment]
@hfmrow 
Hi hfmrow, I am sorry to disturb you again, 
do you know how to change ComboBox dropdown item's background-color? I can't find object name in Inspector and do not know how to change it.

**Comment by hfmrow** [comment]
Hi,
Not sure understanding in right way your question, but anyway using the keyword 'background-color' might help.

**Comment by yuancpfive** [comment]
gtk's widget appearance style always confused me,
finally,  I find a way to change ComboBox dropdown item style.
```
GtkTreeMenu{
    color: white;
    background-color:rgba(19, 26, 36,255) ;
    border-color: white;
}
```

thanks you very much,
your answers and suggestions give me more power to solve the gtk problems I meet,
hope you have a nice day

**Comment by rubyFeedback** [comment]
I found this on a random google search. The arrow-example works fine (I use it in ruby-gtk3).

Has anyone been able to style the popup window? I wanted to give it a more distinct border-type so the 
user can visually separate it in an easier manner, but while I am able to modify the arrow via CSS just
fine, I don't know how to access the window that is pop up on a combo-box when the user clicked
on the arrow.

**Comment by rubyFeedback** [comment]
Actually I could modify color and font-weight, but I can't seem to add a border. Perhaps using a modified border is not possible? The following CSS rules work for the popup-window, excluding the border-property.

    .fancy_combobox window.popup {
      color: royalblue;
      font-weight: bold;
      border: 3px dashed lightgreen;
    }
