### ISSUE TITLE
[Project question] Can I use webkit_web_view in gotk3?

### ISSUE THREAD

**Issue by yuancpfive** [gotk3/gotk3#775]
How can I use webkit_web_view in gotk3?
I can't find any example and don't know how to start it, please give me some suggesstions, thanks a lot.

**Comment by SottoMonte** [comment]
i am currently making a mini browser, i am using this code as a basis, https://github.com/sourcegraph/go-webkit2/tree/master/webkit2, if you know a little c just change a few things to make it work again

**Comment by decentral1se** [comment]
Sorry to resurrect but I am also very much wondering so because I ran into https://github.com/gotk3/gotk3/issues/925 and I am not sure what is the issue. Any hints are much appreciated!
