### ISSUE TITLE
Could not determine kind of name for C.free

### ISSUE THREAD

**Issue by Rillwz** [gotk3/gotk3#789]
**Describe the bug**
i've had an issue running on "go get github.com/gotk3/gotk3/gtk" instructions that [available in here](https://github.com/gotk3/gotk3/wiki/Installing-on-Windows) i've been install any kind package's needed.

**Error messages**
it's clearly said,
> C:\Users\*****\go\pkg\mod\github.com\gotk3\gotk3@v0.6.0\glib\quark.go:13:8: could not determine kind of name for C.free

**Environment:**
gtk3 version: 'gtk3'
go version: 'go version go1.16.5 windows/amd64'
os: 'Windows 10, 21H1, 19043.1055'
other stuff: '...'

**Comment by victor-simon** [comment]
![image](https://user-images.githubusercontent.com/60160760/122760273-9b2f4280-d2a3-11eb-85c7-12392f428fc6.png)

Also there is this problem

**Comment by Lk2v** [comment]
I have the same problem

**Comment by Hareis** [comment]
I have the same problem

**Comment by Lk2v** [comment]
Any solution ?

**Comment by tdanecker** [comment]
It should be fixed by #788

**Comment by Lk2v** [comment]
Yes I had already made this modification while looking at the commits but I thought it was not enough to solve it because I had another error (#796)

Thanks and have a nice day

**Comment by Rillwz** [comment]
> Yes I had already made this modification while looking at the commits but I thought it was not enough to solve it because I had another error (#796)
> 
> Thanks and have a nice day

Ayye thanks ...
