### ISSUE TITLE
[BUG] Connect without userdata breaks compatiblity to old code (Gotk3 0.6.0)

### ISSUE THREAD

**Issue by naums** [gotk3/gotk3#790]
**Describe the bug**
Connect in previous versions took a signal-name, an interface (function), and user-data. It seems version 0.6.0 removed the user-data parameter, breaking my old code. Unfortunately it seems, that due to incompatibilities with current gtk-versions and gotk 0.5.0 I can't go back.

You apparently try to rebuild the code to use closures, but seem to have forget the user-parameter. Or am I doing something wrong?

**Error messages**
For example in 0.6.0:
```
ui/AccountView.go:123:26: too many arguments in call to w.Bin.Container.Widget.InitiallyUnowned.Object.Connect
	have (string, func(*gtk.Button, string), string)
	want (string, interface {})
ui/AccountView.go:127:26: too many arguments in call to w.Bin.Container.Widget.InitiallyUnowned.Object.Connect
	have (string, func(*gtk.Button, string), string)
	want (string, interface {})
```
for the code:
```
func _acceptRequest ( w *gtk.Button, id string ) {
    handleInteraction ( w, id, "acceptRequest" )
}

//...
// fx.Id is a uint
                w, _ = gtk.ButtonNewWithLabel ( "Accept Request" )
                w.Connect("clicked", _acceptRequest, fx.Id )
```

(as reference if I try to build it with 0.4.0, same with 0.5.0)
```
../go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/accel.go:261:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/accel.go:270:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
```

**Environment:**
gtk3 version: (from pacman) 1:3.24.29-2
go version: go version go1.16.5 linux/amd64
os: Arch Linux

**Comment by hfmrow** [comment]
Hi, look at: https://github.com/gotk3/gotk3/issues/751

**Comment by naums** [comment]
Ah, see I did not find that. Could you change the title to something more useful?

I'm gonna preface this: I'm irritated about the change, not angry to you personally.

To be frank here: If you gonna deprecate a function, make that explicit. Have at least a version where every use of that function raises deprecation warnings, and then a new function with a different name, e.g. ConnectWithClosure or something.

To the Connect-problem: Now I have to change all my code, where I use user-data, by either hacking gotk and try to patch every new version, so there is a Connect-variant which behaves the same, or by having an anon function executed, which just calls the actual handler. Both are weird. I meant this would work, wouldn't it? It doesn't make my code prettier.

```
func _acceptRequest ( w *gtk.Button, id string ) {
    handleInteraction ( w, id, "acceptRequest" )
}

//...
// fx.Id is a uint
w, _ = gtk.ButtonNewWithLabel ( "Accept Request" )
w.Connect("clicked", func ( w *gtk.Button ) { _acceptRequest ( w, fx.Id ) } )
```

Thing is, that we both have a different view about this library. You want to do new cool stuff, I just want to use it and it should always work, as long as the underlying libraries are present, i.e. as long as I (can) use GTK3. This is where is irritation comes from. I can totally understand wanting to deprecate certain behaviour, trying to get the garbage collector to improve, fine, fair enough. Have deprecation warnings. Not even the godocs have a warning in the top, that the behaviour of Connect has changed.

So, ok. I apparently have to change my code, because if you revert, everyone else has to change their code. Please deprecate functions or behaviour better next time to prevent this kind of irritation.

Again, I'm not angry at you personally, I'm just irritated that I have to change my code, so I loose hours* and can't make any progress on my project in this time.

*or probably minutes

**Comment by hfmrow** [comment]
I understand you but you are not alone, all programmers who use gotk3 and want to use the latest 0.6 version have to make these changes and have to waste time updating their previously written code (I'm like you, I'm not not happy having to do it, but it's a big improvement, not a stupid or unnecessary constraint).
Another point, maintaining two different versions of an API is not really a simple task considering the compatibility issue and other things.
Like you, the people who help build this gotk3 library have jobs, families, personal desires (development), obligations, and (unfortunately) don't have a lot of time to maintain multiple versions of an API.
You can always use version 0.5.3 to avoid modifying all your code, this is a benefit of golang which uses "modules" to specify the library version.
I hope I am understandable an not too hard in what I want to explain to you.
good day.

**Comment by naums** [comment]
Yes. I am not alone, other devs probably also got irritated by this. But anyway. I understand maintaining a library like gotk3 is not easy, takes a lot of time and resources, which are already limited.

Take this from this irritation: deprecate old functions in two steps, first marking it as deprecated, updating all docs accordingly, then remove it. Ideally present how old code needs to be updated to use new functions. Maybe I just missed that, or it wasn't present.

I'm gonna try 0.5.3, 0.5.0 fails building on some missing members. 

Just to reiterate: I'm irritated, I'm not mad at you.

Cheers.
