### ISSUE TITLE
[BUG] problem with using gotk3 on arch.

### ISSUE THREAD

**Issue by GNUSheep** [gotk3/gotk3#819]
I can't use gotk3, becuase of glib2, I tried using glib2 2.68 but that didn't work. Even downgrading glib2 to the 2.64 version didn't help.

OS: Arch Linux

Error:
![20210727_13h12m35s_grim](https://user-images.githubusercontent.com/54682807/127145149-75e48b6b-abdc-4b58-82db-5640a647370c.png)

**Comment by knightpp** [comment]
On my Arch system the same issue. When I run `go build .` it's compiling indefinitely.

**Comment by zpfz** [comment]
The same problem on Windows 11😭😭

**Comment by sqp** [comment]
I'm on manjaro and don't have compilation issues.
The screenshot you provided only show deprecation warnings (things that would break if not updated for a next future major version, glib3).

My versions:
glibc                          2.33-5                      core 
glib2                          2.68.3-1                    core 
gtk3                   1:3.24.30-1                         extra 
gtk4                   1:4.2.1-2                           extra

**Comment by MJacred** [comment]
@GNUSheep: as @sqp explained, these are just warnings, no errors. this library compiles deprecated GTK code as well. deprecated does not mean that it won't work anymore

@andre-hub: I'd say this issue can be closed
