### ISSUE TITLE
How to limit GtkTextView width? (number of chars)

### ISSUE THREAD

**Issue by chespinoza** [gotk3/gotk3#835]
Hi folks, thanks for this project, so far I've been enjoying it a lot, there's only one thing annoying me which is that I can't figure out how to limit the width of a GtkTextView when loading text, I've tried using a GtkScrolledWindow too without any success.
I thought that the property Maximum Content Width would work but it didn't either, probably I'm overlooking something I'm not really sure, I'm using Glade to define the GUI btw.

What I want is that the text I'm loading would be limited by maybe the number of chars/columns but instead it just grows out of control, using a ScrolledWindow helps a bit but it really just hide it.

If anyone knows any pattern to limit the GtkTextView width please let me know, I'd really appreciate any advice or hint.

Cheers!

**Comment by hfmrow** [comment]
Hi,
Have you try '`SetRightMargin`' and formatting like `'SetWrapMode(gtk.WRAP_WORD_CHAR)'` ?

**Comment by chespinoza** [comment]
thank you very much @hfmrow it made my day!!!
```go
	txtV1.SetWrapMode(gtk.WRAP_WORD_CHAR)
	txtV1.SetVExpand(true)
	txtV1.SetHExpand(false)
```
