### ISSUE TITLE
[Project question] How to get parameters emited on custom signals?

### ISSUE THREAD

**Issue by ahsand97** [gotk3/gotk3#842]
Is  there any way to get parameters when you emit custom signals like this?:

```go
_, _ = glib.SignalNew("test-signal")

myGtkApplication.Connect("test-signal", func(app *gtk.Application, data string) {
    fmt.println(data)
})

_, _ = myGtkApplication.Emit("test-signal", "test parameter")

```
When you run this you get
``` panic: closure error: too many closure args: have 2, max 1```

I see that this issue is basically the same  as [this one](https://github.com/gotk3/gotk3/issues/532) and they mentioned that the parameter "userdata" could be used but that parameter was dropped from the function ```Connect``` in the version 6.0

**Comment by diamondburned** [comment]
I think the proper answer to this question is to fix up the `g_signal` bindings
and make them proper.

Is this signal something that might be called/connected on the C side? If not,
why not just use Go methods?

**Comment by ahsand97** [comment]
> Is this signal something that might be called/connected on the C side? If not,
> why not just use Go methods?

The backend package only has an instance of *gtk.application attached to its main struct and I emmit custom signals on that object to trigger its handlers that change things in the frontend (which is in a different package) and sometimes I'd like to emmit those signals with custom parameters, maybe a boolean, an integer or string. if I do not add any parameter everything works but with extra parameters there's panic.
The `Emit` function has a variadic parameter to send data but I don't see any possible way to retrieve that data with the `Connect` function (it hasn't the variadic parameter anymore).

**Comment by diamondburned** [comment]
> The backend package only has an instance of *gtk.application attached to its main struct

This sounds more like an application design issue to me. If the "backend
package" is in Go, then communicating with it should also be in Go, not
overloaded through C and back.

You should look into ways to restructure your packages rather than relying on
this magical pattern of pseudo-methods.

**Comment by ahsand97** [comment]
> You should look into ways to restructure your packages rather than relying on
> this magical pattern of pseudo-methods.

Backend and Frontend are totally independent from each other and both have the same instance of *gtk.Application. GObject can connect and emmit signals (evne those even created by the programmer itself) and that's not relying on this magical pattern but relying in a common functionality that is present in C and other Gtk bindings.

**Comment by ahsand97** [comment]
After trying some architecture alternatives avoiding passing parameters in the custom signals I found that the actual problem are not the functions `Connect` and `Emit` , both work as expected even when a callback has extra parameters.

The problem is with the function `glib.SignalNew`
```go
func SignalNew(s string) (*Signal, error)
```

This wrapper creates a signal but the signal is limited cuz its callback only allows to have a single parameter which is the object who emitted the signal, that's why when I tried to run the example I showed above I was receiving the error

> ` panic: closure error: too many closure args: have 2, max 1`

So, if there's a necessity to create custom signals and there's no need to have extra parameters `glib.SignalNew` works great.

As a workaround `C` or `cgo`  can be used to create the signal and then use normally the functions `Connect` and `Emit` with the new signal.

Demonstration:

**Using C** 
```go
package test

/*
#cgo pkg-config: gdk-3.0
#include <gdk/gdk.h>

// C function that creates a signal called "test-signal" using GObject -> signal_new (https://docs.gtk.org/gobjecy/func.signal_new.html)
void create_signal()
{
	g_signal_new(
		"test-signal",
		G_TYPE_OBJECT,
		G_SIGNAL_RUN_FIRST,
		0,
		NULL,
		NULL,
		g_cclosure_marshal_VOID__POINTER,
		G_TYPE_NONE,
		1,
		G_TYPE_POINTER
	);
	// This signal returns nothing and its callback should have 2 parameters
	// 1. object who emitted the signal, 2. gpointer with the data passed
}
*/
import "C"

import (
	"fmt"

	"github.com/gotk3/gotk3/gtk"
)

func testSignalUsingC(app *gtk.Application) {
	C.create_signal() // Calling the C function to create the signal
	app.Connect("test-signal", func(app *gtk.Application, data string) { // Connecting normally to the signal expecting an extra string
		fmt.Println("Signal activated, extra params:", data)
	})
	_, _ = app.Emit("test-signal", "parameterExtra#1") // Emitting the signal with extra parameters
	_, _ = app.Emit("test-signal", "parameterExtra#2")
}
```

Giving as a result: 
![image](https://user-images.githubusercontent.com/32344641/147365272-ec7ad375-e127-434b-a5c3-7058fc12b187.png)


**Using cgo** 
```go
package test

/*
#cgo pkg-config: gdk-3.0
#include <gdk/gdk.h>
*/
import "C"

import (
	"fmt"
	"unsafe"

	"github.com/gotk3/gotk3/gtk"
}

func testSignalUsingCgo(app *gtk.Application) {
	cstr := C.CString("test-signal")   // Signal name allocated as a C string
	defer C.free(unsafe.Pointer(cstr)) // making sure the memory allocated is released

	// (http://irtfweb.ifa.hawaii.edu/SoftwareDocs/gtk20/gobject/gobject-gtype.html)
	// Slice of GTypes that indicates what the callback of the signal should recieve as extra parameter
	arrayOfTypes := []C.GType{C.G_TYPE_INT} // To reference its array pointer we use &arrayOfTypes[0]

	// C Function used from go to create the signal, in this case GObject -> signal_newv is used instead of
	// GObject -> signal_new because cgo doesn't support variadic parameters
	// (https://docs.gtk.org/gobject/func.signal_newv.html)
	C.g_signal_newv(
		(*C.gchar)(cstr),
		C.G_TYPE_OBJECT,
		C.G_SIGNAL_RUN_FIRST,
		(*C.GClosure)(C.NULL),
		(*[0]byte)(C.NULL),
		C.gpointer(C.NULL),
		(*[0]byte)(C.g_cclosure_marshal_VOID__POINTER),
		C.G_TYPE_NONE,
		C.guint(1),
		(*C.GType)(&arrayOfTypes[0]),
	)
	// This signal returns nothing and its callback should have 2 parameters
	// 1. object who emitted the signal, 2. an int (defined in arrayOfTypes)

	app.Connect("test-signal", func(app *gtk.Application, data int) { // Connecting normally to the signal expecting an extra int
		fmt.Println("Signal activated, extra params:", data)
	})
	_, _ = app.Emit("test-signal", 1234) // Emitting the signal with extra parameters
	_, _ = app.Emit("test-signal", 4321)
}
```

Giving as a result
![image](https://user-images.githubusercontent.com/32344641/147366486-dfc76da4-dd8e-47ce-bde4-6a40c0882871.png)

The extra castings using **cgo** (ex: `(*[0]byte)`) are necessary since macros are not available in cgo and the compiler it's gonna fail because of incompatible types when calling the function

**Comment by diamondburned** [comment]
This seems valid. If you ever want to PR this directly into the library, you can
open one for adding a new function `NewSignal` in `pkg/core/glib`.

**Comment by ahsand97** [comment]
> This seems valid. If you ever want to PR this directly into the library, you can open one for adding a new function `NewSignal` in `pkg/core/glib`.

Oh okay, I already opened another issue with the prototype of the binding, if everything is correct can I create the PR ?

**Comment by diamondburned** [comment]
It seems alright. If there's anything, you can open the PR for reviewing.

**Comment by ahsand97** [comment]
> It seems alright. If there's anything, you can open the PR for reviewing.

Okay after digging some more I found that `glib.SignalNew` is a wrapper around `g_signal_new` defined [here](https://github.com/gotk3/gotk3/blob/1d544513fb748b660717266a1fe0284daeeb8fbc/glib/glib.go.h#L157) , so....should I modify that function and ofcourse `glib.SignalNew` or would u say is best to create a new binding?? meaning to create a new C function using `g_signal_newv` and a new Go function let's say `glib.SignalNewV` ??

**Comment by diamondburned** [comment]
I think a new `glib.SignalNewv` would be better.
