### ISSUE TITLE
[BUG] what the fuck happened? 

### ISSUE THREAD

**Issue by ArkAngeL43** [gotk3/gotk3#843]
**Describe the bug**
IDK you tell me? there is something massively wrong in your code, for some reason every time I went to compile the examples using your module my CPU spiked up to 100% load and went way above the temperature it’s supposed to ( keep in mind with other packages even after it never happens ) I ran it and read some of the other bugs people were having and upon waiting I noticed ALL of my resources started fucking skyrocketing out of the damn screen, then my entire computer shut itself down, then turned itself back on, then off and on again until finally just quitting completely. I got back on thinking it was just a OS issue and somehow someway even windows decided it wouldn’t even install the program after also nearly exploding my entire desktop, then I ran it on my raspberry pi cluster and the same exact thing happend, I think you really need to add some sort of threading and fix this up ALOT let alone the compilation for the code takes for EVER, even I’ve written some pretty heafty personal modules and even AI GUI applications, however they didn’t use up every bit of my resources and take 6 minutes to compile at most they took 30 seconds. golang is a very very fast language however even I know it shouldn’t take this long for the environment or code to compile itself. 

**To Reproduce**
started on parrot OS 64 and 32 BIT
Switched too windows to try again same issue
Switched to a raspberry pi cluster server same issue 
switched to my laptop same issue 

**Environment:**
gtk3 version: newest
go version: latest
os: Debian, Unix, Windows 10, Windows 11 
other stuff:
PC SPECS: 
CPU: Ryzen 7 3700X 
GPU: X2 MSI 1050TI’s
Coo: ZXT KRaken X53 
storage: 3 Samsung 970 evo SSD’d 
 
** other ** 

I know it’s not my hardware since I can read everything that’s happening upon compiling and running the code, i tried fixing it myself with my own resources and debuggers but couldn’t find the issue 

also I want to note if you take in the code from the example modules, toss it into a visual studio IDE with a golang server it will tell you that there is one bug in the script where the “ os “ module is imported but not used, when you get that on your screen and you find a way to fix it 12 other errors appear in the script where it needs os arguments, and when you run the compiled fixed code you get errors like “ argument is needed upon calling GTK.run “ or whatever the module is defined as. 

Please fix this before you break google itself and make the go Lang developers eyes cry

**Comment by ArkAngeL43** [comment]
Newer issue: completely destroyed my Linux system as well, my SSD doesn’t have my original parrot os system on it- I didn’t even know a module can do this 💀

**Comment by ahsand97** [comment]
The module does take a lot to compile the first times, you just have to wait...then the next times it compiles straight forward.

**Comment by ArkAngeL43** [comment]
yeah ive read that hence why i said that IS NOT supposed to happen, as ive said ive written my own personal modules even AI with GO and when it takes that long to compile, and then crashes your entire computer to where it collapses the OS something is wrong in that code, more than just " wait " time

**Comment by ahsand97** [comment]
> IS NOT supposed to happen

This module takes a lot to compile the first time and if you see the resource monitor you'll see that there's of bunch of "gcc" running while it compiles cuz it's basically building all GTK and its go bindings (if you check the source code there's a bunch of .h files that need to be compiled), after it finishes then you can build and run the examples or your own applications faster.

**Comment by ArkAngeL43** [comment]
yes i saw that after my PC literally exploded a whole ass card, C is a very VERY flexible language, i feel if you guys truly were able to build the bindings for it and even modify the manager you can easily control the .h files and compress them i know alot of people spue " oh well 1000 files need to be seperate " but i know if someone whoever is in charge of the header files, c files, and even the bindings needs to change it before the amount of power it takes frys someones sockets or damages someones hardware, and if you arent the orgin developers for GTK you can take GTK's source code and compress the H files yourself ive had to do it hundreds of times because developers now adays just do NOT know how to operate or work around languages.

**Comment by 1player** [comment]
This is certainly the most idiotic thing I've read today. Why is this bug report still open eludes me.

**Comment by ArkAngeL43** [comment]
shoot yourself in the foot

**Comment by ArkAngeL43** [comment]
phyne was a better module anyway, they had GOOD error handeling, and AMAZING compile time not fucking 30 minutes + 40 extra crashes on your system
.
.
.
. cmon dude, could have been a better response, when programmers = shit
