### ISSUE TITLE
[BUG] Lines 264 and 273 of accel.go throw errors

### ISSUE THREAD

**Issue by egg4096** [gotk3/gotk3#846]
### Description:
Lines 264 and 273 of accel.go throw errors

### Error messages:
`accel.go:264:5:`
`val.accel_flags undefined`
`(type _Ctype_struct__GtkAccelKey has no field or method accel_flags)`

`accel.go:273:22: `
`obj.accel_flags undefined`
`(type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)`

### To reproduce:
`go install -v github.com/diamondburned/gtkcord3@latest`

### Environment:
GTK 3 version: '3.24.25-1ubuntu4.1'
Go version: '1.17.2'
OS: 'Ubuntu Linux 21.04 x86_64'

**Comment by hfmrow** [comment]
Hi,
Which version of gotk3 is in use ?
Look at https://github.com/gotk3/gotk3/pull/730
Solved since go v1.16 but if you are with gotk3 version <V0.6.0 you have to update your library

**Comment by egg4096** [comment]
Alright! I was a little confused where to add an issue, and turns out I shouldn't've done it on this repo. Thank you :)
