### ISSUE TITLE
[BUG] BUTTON CSS BACKGROUND

### ISSUE THREAD

**Issue by GhostironmanRVG2** [gotk3/gotk3#857]
**Describe the bug**
All css properties are working but background color not at my button

**Error messages**
Theres no error messages , all propertys are working as they should but the background-color not
![image](https://user-images.githubusercontent.com/48800536/151349414-c3437cf5-964c-4b69-bc36-02cf709e757c.png)
![image](https://user-images.githubusercontent.com/48800536/151349491-7b46416b-5189-4cf7-ab96-788222b7e3f1.png)
![image](https://user-images.githubusercontent.com/48800536/151349640-a081df6d-69db-4056-b19c-7e93cd9c2cbd.png)
![image](https://user-images.githubusercontent.com/48800536/151349791-976aad62-1044-4f91-89e7-40e73eda1b76.png)

**Comment by GhostironmanRVG2** [comment]
Well , with gradient it works but with background-color it stills not went throught :(

**Comment by GhostironmanRVG2** [comment]
Btw ..do you know how do i change the selected day color from an calendar widget? i think it is another limitation for this library since i changed that in gtk 3.0 in c language :P

**Comment by hfmrow** [comment]
```go
var customCss = []byte(`
#top-level {
	background: red;

}`)
```
work right ...

**Comment by hfmrow** [comment]
Right...
gotk3 limitation about css ? i think not.
maybe seat / machine interface could be concerned ? not sure but sometimes questions should be asked.
Below a working code using a single red backgroud-color for a dummy button mixed with a calendar with user defined color for selected day...
```go
package main

import (
	"log"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

var (
	win *gtk.Window
	box *gtk.Box
	btn *gtk.Button
)

// Css declaration
var customCss = []byte(`
#top-level {
	background-color: red;
}
#calendar:selected {
   color: red;
   background-color: yellow;
   padding: 0.4em;
   border-radius: 3px;
 }
`)

// main: launcher
func main() {
	gtk.Init(nil)
	win = setupWindow("Go Example")

	cssWdgScnBytes(customCss) // Css setup

	gtk.Main()
}

// setupWindow: Create and initialize the window
func setupWindow(title string) *gtk.Window {
	var err error

	win, err = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatalf("Unable to create window: %v\n", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func(w *gtk.Window) {
		gtk.MainQuit()
	})

	win.SetPosition(gtk.WIN_POS_CENTER)
	width, height := 640, 480
	win.SetDefaultSize(width, height)

	cal, err := gtk.CalendarNew()
	cal.SetName("calendar")

	box, err = gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)
	if err != nil {
		log.Fatalf("Unable to create box: %v\n", err)
	}

	btn, err = gtk.ButtonNew()
	if err != nil {
		log.Fatalf("Unable to create button: %v\n", err)
	}
	btn.SetLabel("Click it or not")

	btn.SetName("top-level") // naming btn for css usage

	box.Add(btn)
	box.Add(cal)
	win.Add(box)
	win.ShowAll()
	return win
}

// css implementation
func cssWdgScnBytes(data []byte) error {

	cssProv, err := gtk.CssProviderNew()
	if err == nil {
		if err = cssProv.LoadFromData(string(data)); err == nil {
			screen, err := gdk.ScreenGetDefault()
			if err != nil {
				return err
			}
			gtk.AddProviderForScreen(screen, cssProv, gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
		}
	}
	return err
}
```

**Comment by GhostironmanRVG2** [comment]
Maybe a installation error idk because i made exacly what you provided to me and it isnt working at all. I mean , i can change the font of the button but the colors itself no :P . Anyway , thanks for the help mate !!!
