### ISSUE TITLE
[Project question] Grab mouse pointer and confine to window

### ISSUE THREAD

**Issue by mevdschee** [gotk3/gotk3#861]
Hi, Thank you for this awesome project: it allows me to easily create a GUI in my favorite language :-). I want to grab the mouse pointer and send all mouse input to one window (moves and clicks). I want to mimic the the behavior of virtual machine viewers that "grab" the mouse pointer. Pseudo-code:

	"onClickGrabButton": func(tb *gtk.ToggleButton) {
		mouseGrabbed = tb.GetActive()
		display, _ := playerArea.GetDisplay()
		window, _ := playerArea.GetWindow()
		seat, _ := display.GetDefaultSeat()
		cursorNone, _ := gdk.CursorNewFromName(display, "none")
		// not supported:
		//grab, _ := gdk_seat_grab(seat, window, gdk.GDK_SEAT_CAPABILITY_ALL_POINTING, true, cursorNone, nil, nil, nil)
		//gdk_seat_ungrab(grab)
	}

How can I call "gdk_seat_grab" and "gdk_seat_ungrab"? These calls seem to be missing. Is there a way to add this in my own code or via a PR, should I try that? Or would you like me to set-up a bounty for this? Also I'm quite new to GDK 3, so maybe I need "gdk_device_grab" and "gdk_device_set_mode" instead. Any advice on this? I would be very grateful for any pointers in the right direction. Kind regards, Maurits

**Comment by ahsand97** [comment]
You can use C inside go just like this:

```Go
package test

/*
#cgo pkg-config: gdk-3.0
#include <gdk/gdk.h>
*/
import "C"

```
then you can call `C.gdk_seat_grab()` and `C.gdk_seat_ungrab()`, you have to cast the parameters to valid C types when calling a C function.

Or you can create a binding yourself for those functions and make a PR

**Comment by mevdschee** [comment]
@ahsand97 Thank you very much for your reply. I was not aware it was that easy and with your directions I managed to make it work. In the top of the file I write as you suggested:

    /*
    #cgo pkg-config: gdk-3.0
    #include <gdk/gdk.h>
    */
    import "C"

and below I wrote:

    display, _ := playerArea.GetDisplay()
    window, _ := playerArea.GetWindow()
    seat, _ := display.GetDefaultSeat()
    cursorNone, _ := gdk.CursorNewFromName(display, "none")				
    C.gdk_seat_grab((*C.GdkSeat)(unsafe.Pointer(seat.Native())), (*C.GdkWindow)(unsafe.Pointer(window.Native())), 1<<0|1<<1|1<<2, 0, (*C.GdkCursor)(unsafe.Pointer(cursorNone.Native())), nil, nil, nil)

and to release the seat I wrote:

    display, _ := playerArea.GetDisplay()
    seat, _ := display.GetDefaultSeat()
    C.gdk_seat_ungrab((*C.GdkSeat)(unsafe.Pointer(seat.Native())))

It works great, thank you very much!
