### ISSUE TITLE
[Project question] Will there be GTK 4 support?

### ISSUE THREAD

**Issue by rilysh** [gotk3/gotk3#878]
As the title says, I'd like to know any further updates about this project. GTK 4 was released back in 2020 and it would be nice if you folks add GTK 4 support in gotk. Will there be anything soon related with it?

Thanks.

**Comment by apprehensions** [comment]
https://github.com/diamondburned/gotk4

**Comment by rilysh** [comment]
> https://github.com/diamondburned/gotk4

Even though the repo name says what it is, it's always better to explain a little instead throwing a link with no context at all. Kind of disrespectful behaviour.

**Comment by apprehensions** [comment]
>"here's an alternative library instead"
