### ISSUE TITLE
Would it be possible to tag a new minor version?

### ISSUE THREAD

**Issue by olabiniV2** [gotk3/gotk3#893]
It's been quite some time since the last commit in the repository, and there are some useful changes since the last release that would be useful to have tagged. Would it be possible to just tag `v0.6.2`?, so that I can make other projects depend on a numbered version instead of a commit hash?

**Comment by andre-hub** [comment]
yeah, is a good idea.
https://github.com/gotk3/gotk3/releases/tag/v0.6.2

**Comment by olabiniV2** [comment]
Great, thank you!
