### ISSUE TITLE
[BUG] Double free or corruption

### ISSUE THREAD

**Issue by la-ref** [gotk3/gotk3#899]
Hello, I am developing a Go application using Gotk3 and gRPC. To provide a quick overview, my application includes a window that contains a treeview with data from a database and an information box containing the detailed info of the riw. When a row in the treeview is clicked, an information box is displayed at the bottom of the treeview widget, presenting detailed information about the selected row. Within this information box, there is a gtk.Image widget.

To add image date into the gtk.Image widget, I use the SetFromPixBuf function, which receives an image buffer from my gRPC server. However, I am encountering an issue where the application occasionally crashes when rapidly navigating through rows using the arrow keys. The crash occurs specifically when calling C.gtk_image_set_from_pixbuf within the SetFromPixbuf function, but i have no access to this C function, and looks to be crashing after a lot of calls. The expected behavior is to successfully set the image on the gtk.Image widget without any crashes.

**Error messages**
```
double free or corruption (fasttop)
SIGABRT: abort
PC=0x7f81a2433ccc m=9 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 11179 [syscall]:
runtime.cgocall(0xf2c500, 0xc0000d1d18)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000d1cf0 sp=0xc0000d1cb8 pc=0x4906dc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_image_set_from_pixbuf(0x3e29700, 0x7f81540474c0)
	_cgo_gotypes.go:15181 +0x45 fp=0xc0000d1d18 sp=0xc0000d1cf0 pc=0x79ecc5
github.com/gotk3/gotk3/gtk.(*Image).SetFromPixbuf.func1(0xc000316000?, 0x7f81540474c0)
	/home/dev1/go/pkg/mod/github.com/gotk3/gotk3@v0.6.1/gtk/gtk.go:5719 +0x72 fp=0xc0000d1d50 sp=0xc0000d1d18 pc=0x81e732
github.com/gotk3/gotk3/gtk.(*Image).SetFromPixbuf(0x1392da0?, 0xc0001ae008?)
	/home/dev1/go/pkg/mod/github.com/gotk3/gotk3@v0.6.1/gtk/gtk.go:5719 +0x32 fp=0xc0000d1d78 sp=0xc0000d1d50 pc=0x81e692
myproject/client/src/utils.SetData({0x1259e80?, 0xc000014078?}, {0x1169a20, 0xc000304080})
	/myprojectpath/client/src/utils/gtk.go:788 +0x729 fp=0xc0000d1e80 sp=0xc0000d1d78 pc=0xde8a69
myproject/client/src/utils.SetFormData(0xc000368260?, 0xc00025ac90)
	/myprojectpath/client/src/utils/gtk.go:880 +0x13d fp=0xc0000d1f40 sp=0xc0000d1e80 pc=0xde925d

```
**SetFormData** function is designed to set the data into the info box, taking my window builder and a map containing row data. The map includes a key-value pair where the key represents the name of the widget, and the value here is the image data stored in a buffer. Inside this function, it iterates over the map entries, retrieves the corresponding GTK object associated to the key, and invokes the SetData function to set the data of the GTK object.

**SetData** function is responsible for setting data inside a widget. It takes a GTK object and the data as parameters. Depending on the type of the widget, it performs the appropriate action to set the data. In this case, ithe widget is of type *gtk.Image, it then uses the SetFromPixbuf function to set the image data on the widget.

**Environment:**
gogtk3 latest 
go version: go1.20.4 linux/amd64
os: Debian GNU/Linux 12 (bookworm)

**Comment by la-ref** [comment]
Okay so after a deep search i finally fixed the issue.
The problem was that for loading images and to not block the main loop i was using a goroutines with a mutex .
BUT native GTK is not thread safe, and this could be used by multiple goroutines even with a mutex.
So instead of calling the function directly, i called it with glib.IdleAdd() that will run in the GTK main loop when it is in an idle.
I hope this will help someone one day!

**Comment by sqp** [comment]
GTK is mono thread, so while you're in a widget callback, you're safe. But as soon as you start a routine, you have to force every gtk action through a glib idle call.
An alternative for pixbufs is the pixbuf loader
