### ISSUE TITLE
Make everything interface based to facilitate testing

### ISSUE THREAD

**Issue by olabini** [gotk3/gotk3#90]
When doing unit testing, the gotk3 package is a bit problematic - it is large and compiles slowly, and it builds real GUIs on the screen. 

My proposal is that in order to facilitate testing, we make use of Golang interfaces - we publish interfaces in a different package, such as gotk3/gtk/interfaces - and then use these interfaces instead of the real names of the types. We make all the top level functions part of interfaces as well. In that way, you can mock out the whole gtk subsystem in tests if you want to. We could also supply empty mock implementations of all interfaces, but that's less urgent.

There shouldn't be a noticeable performance impact from this - doing interface dispatch in golang is fairly efficient when there is only one implementor around.

The initial effort to make this happen would be large, but if this is something the team thinks would be good, I'm fine with doing it. The ongoing effort is small - just make sure every time we change the signature or add a method we also add it to the corresponding interface.

Thoughts?

**Comment by yamnikov-oleg** [comment]
Would that cost an effort? I mean, how many gotk3 functions can be tested with mocks? Majority of them are plain C calls and you can't imitate gtk for gtk itself.

**Comment by olabini** [comment]
Sorry, I wasn't very clear - I didn't mean testing for gotk3 - I meant testing for client applications using gotk3. As an example, our CoyIM application has a huge chunk of GUI code that is very hard to test - if everything was interface based it would be much easier.

**Comment by yamnikov-oleg** [comment]
Proper testing functionality would be a nice feature which many packages have lack of... I don't mind.

**Comment by andre-hub** [comment]
Should then as by look [QT](https://github.com/visualfc/goqt/blob/master/ui/qt_interface.go)?
I find this a little confusing. When i show ours [list of gotk functions](https://godoc.org/github.com/gotk3/gotk3/gtk#pkg-index), this is not a little list..

what were with interface for the init and mapping function? you can mock the both functions and any calls go to the mocks.

indeed when the effort for the change is very little, then is ok. but for newcomer is this a new obstacle/convention.

**Comment by olabini** [comment]
Agreed, these would be large interfaces. But on the other hand, after the initial work is done to create them, keeping them updated would be very little effort, and I think I can generate that automatically.

How could I mock the init and mapping function? The problem is that the gtk classes are all over an implementation, so how do you test that without running the real gtk? It also takes about a minute to compile gtk now, which means it would be very hard to run fast unit tests.

But if you're against it, we shouldn't do it.

**Comment by andre-hub** [comment]
can we make a script or other way for create the interface. we need this later for check / recreating the new functions. when not, then not. i think for the futher is the effort better we have the interfaces.

I am not generally against, there is a paradigm shift and should be reviewed shortly :-)
