### ISSUE TITLE
Cairo Text rendering wrapper broken

### ISSUE THREAD

**Issue by axel-freesp** [gotk3/gotk3#92]
Hi,

it seems that with the recent activity to break down cairo.go into smaller pieces, this commit has been lost:

https://github.com/gotk3/gotk3/commit/24f3a1feb2c2dc30c957041ea3f130cfe25ee6f4

which adds text rendering to cairo.

I will add a text.go to cairo having the exact same content as the commit above.

Cheers
Axel

**Comment by andre-hub** [comment]
have you error message or better example code

**Comment by axel-freesp** [comment]
Currently I come up with my project https://github.com/axel-freesp/sge which depends on gotk3 bindings and raises this bug. When time permits, I can add an example to the gotk3-examples...

**Comment by axel-freesp** [comment]
97abdca696d3a0eadf4d6c94303175cdf516774b contains the fix.
