### ISSUE TITLE
[Project question] is gio.Task available?

### ISSUE THREAD

**Issue by decentral1se** [gotk3/gotk3#924]
From https://discourse.gnome.org/t/what-is-the-proper-way-to-run-event-functions-without-freezing-the-main-thread/7499

> If you have a long running operation, you can use [GTask 56](https://docs.gtk.org/gio/class.Task.html), which will run a function in a thread and, once the function returns a value or an error, will invoke a callback in the thread that created the GTask instance. This, typically, means you create a task in response to an event or any other signal; run it; and then update the UI once the task terminates.

I only saw examples with `IdleAdd` but this slows down my UI. I think I need to use `Task`.

Thanks for all the work, `gotk3` is amazin' 💘

**Comment by pekim** [comment]
Maybe I'm misunderstanding your requirement, but won't something like this be sufficient?

```go
func myLongRunningOperation() {
    // Do whatever takes a long time.
    // It won't block ui processing as it's running in a goroutine, and therefore not on
    // the same thread as the main event loop.
    ...
    ...

    // The long operation has finished, and we're ready to update the ui.

    glib.IdleAdd(func () {
        // This is running in the main event loop context, the main thread.
        // So it is safe to update the ui in here.
        ...
    })
}


go myLongRunningOperation()
````

**Comment by decentral1se** [comment]
Indeed, tysm @pekim! Much appreciated ✌️
